// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: industries/loosh/yutani/v1/layout.proto

package yutani

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FlexAddItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     *SessionId             `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	FlexId        *WidgetId              `protobuf:"bytes,2,opt,name=flex_id,json=flexId,proto3" json:"flex_id,omitempty"`
	ItemId        *WidgetId              `protobuf:"bytes,3,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Proportion    int32                  `protobuf:"varint,4,opt,name=proportion,proto3" json:"proportion,omitempty"`                // 0 for fixed size, >0 for proportional
	FixedSize     int32                  `protobuf:"varint,5,opt,name=fixed_size,json=fixedSize,proto3" json:"fixed_size,omitempty"` // Used when proportion is 0
	Focus         bool                   `protobuf:"varint,6,opt,name=focus,proto3" json:"focus,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlexAddItemRequest) Reset() {
	*x = FlexAddItemRequest{}
	mi := &file_industries_loosh_yutani_v1_layout_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlexAddItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlexAddItemRequest) ProtoMessage() {}

func (x *FlexAddItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_industries_loosh_yutani_v1_layout_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlexAddItemRequest.ProtoReflect.Descriptor instead.
func (*FlexAddItemRequest) Descriptor() ([]byte, []int) {
	return file_industries_loosh_yutani_v1_layout_proto_rawDescGZIP(), []int{0}
}

func (x *FlexAddItemRequest) GetSessionId() *SessionId {
	if x != nil {
		return x.SessionId
	}
	return nil
}

func (x *FlexAddItemRequest) GetFlexId() *WidgetId {
	if x != nil {
		return x.FlexId
	}
	return nil
}

func (x *FlexAddItemRequest) GetItemId() *WidgetId {
	if x != nil {
		return x.ItemId
	}
	return nil
}

func (x *FlexAddItemRequest) GetProportion() int32 {
	if x != nil {
		return x.Proportion
	}
	return 0
}

func (x *FlexAddItemRequest) GetFixedSize() int32 {
	if x != nil {
		return x.FixedSize
	}
	return 0
}

func (x *FlexAddItemRequest) GetFocus() bool {
	if x != nil {
		return x.Focus
	}
	return false
}

type FlexAddItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlexAddItemResponse) Reset() {
	*x = FlexAddItemResponse{}
	mi := &file_industries_loosh_yutani_v1_layout_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlexAddItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlexAddItemResponse) ProtoMessage() {}

func (x *FlexAddItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_industries_loosh_yutani_v1_layout_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlexAddItemResponse.ProtoReflect.Descriptor instead.
func (*FlexAddItemResponse) Descriptor() ([]byte, []int) {
	return file_industries_loosh_yutani_v1_layout_proto_rawDescGZIP(), []int{1}
}

func (x *FlexAddItemResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type FlexRemoveItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     *SessionId             `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	FlexId        *WidgetId              `protobuf:"bytes,2,opt,name=flex_id,json=flexId,proto3" json:"flex_id,omitempty"`
	ItemId        *WidgetId              `protobuf:"bytes,3,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlexRemoveItemRequest) Reset() {
	*x = FlexRemoveItemRequest{}
	mi := &file_industries_loosh_yutani_v1_layout_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlexRemoveItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlexRemoveItemRequest) ProtoMessage() {}

func (x *FlexRemoveItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_industries_loosh_yutani_v1_layout_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlexRemoveItemRequest.ProtoReflect.Descriptor instead.
func (*FlexRemoveItemRequest) Descriptor() ([]byte, []int) {
	return file_industries_loosh_yutani_v1_layout_proto_rawDescGZIP(), []int{2}
}

func (x *FlexRemoveItemRequest) GetSessionId() *SessionId {
	if x != nil {
		return x.SessionId
	}
	return nil
}

func (x *FlexRemoveItemRequest) GetFlexId() *WidgetId {
	if x != nil {
		return x.FlexId
	}
	return nil
}

func (x *FlexRemoveItemRequest) GetItemId() *WidgetId {
	if x != nil {
		return x.ItemId
	}
	return nil
}

type FlexRemoveItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlexRemoveItemResponse) Reset() {
	*x = FlexRemoveItemResponse{}
	mi := &file_industries_loosh_yutani_v1_layout_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlexRemoveItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlexRemoveItemResponse) ProtoMessage() {}

func (x *FlexRemoveItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_industries_loosh_yutani_v1_layout_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlexRemoveItemResponse.ProtoReflect.Descriptor instead.
func (*FlexRemoveItemResponse) Descriptor() ([]byte, []int) {
	return file_industries_loosh_yutani_v1_layout_proto_rawDescGZIP(), []int{3}
}

func (x *FlexRemoveItemResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type FlexSetDirectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     *SessionId             `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	FlexId        *WidgetId              `protobuf:"bytes,2,opt,name=flex_id,json=flexId,proto3" json:"flex_id,omitempty"`
	Direction     FlexDirection          `protobuf:"varint,3,opt,name=direction,proto3,enum=industries.loosh.yutani.v1.FlexDirection" json:"direction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlexSetDirectionRequest) Reset() {
	*x = FlexSetDirectionRequest{}
	mi := &file_industries_loosh_yutani_v1_layout_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlexSetDirectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlexSetDirectionRequest) ProtoMessage() {}

func (x *FlexSetDirectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_industries_loosh_yutani_v1_layout_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlexSetDirectionRequest.ProtoReflect.Descriptor instead.
func (*FlexSetDirectionRequest) Descriptor() ([]byte, []int) {
	return file_industries_loosh_yutani_v1_layout_proto_rawDescGZIP(), []int{4}
}

func (x *FlexSetDirectionRequest) GetSessionId() *SessionId {
	if x != nil {
		return x.SessionId
	}
	return nil
}

func (x *FlexSetDirectionRequest) GetFlexId() *WidgetId {
	if x != nil {
		return x.FlexId
	}
	return nil
}

func (x *FlexSetDirectionRequest) GetDirection() FlexDirection {
	if x != nil {
		return x.Direction
	}
	return FlexDirection_FLEX_ROW
}

type FlexSetDirectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlexSetDirectionResponse) Reset() {
	*x = FlexSetDirectionResponse{}
	mi := &file_industries_loosh_yutani_v1_layout_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlexSetDirectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlexSetDirectionResponse) ProtoMessage() {}

func (x *FlexSetDirectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_industries_loosh_yutani_v1_layout_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlexSetDirectionResponse.ProtoReflect.Descriptor instead.
func (*FlexSetDirectionResponse) Descriptor() ([]byte, []int) {
	return file_industries_loosh_yutani_v1_layout_proto_rawDescGZIP(), []int{5}
}

func (x *FlexSetDirectionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GridAddItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     *SessionId             `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	GridId        *WidgetId              `protobuf:"bytes,2,opt,name=grid_id,json=gridId,proto3" json:"grid_id,omitempty"`
	ItemId        *WidgetId              `protobuf:"bytes,3,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Row           int32                  `protobuf:"varint,4,opt,name=row,proto3" json:"row,omitempty"`
	Column        int32                  `protobuf:"varint,5,opt,name=column,proto3" json:"column,omitempty"`
	RowSpan       int32                  `protobuf:"varint,6,opt,name=row_span,json=rowSpan,proto3" json:"row_span,omitempty"`
	ColumnSpan    int32                  `protobuf:"varint,7,opt,name=column_span,json=columnSpan,proto3" json:"column_span,omitempty"`
	MinWidth      int32                  `protobuf:"varint,8,opt,name=min_width,json=minWidth,proto3" json:"min_width,omitempty"`
	MinHeight     int32                  `protobuf:"varint,9,opt,name=min_height,json=minHeight,proto3" json:"min_height,omitempty"`
	Focus         bool                   `protobuf:"varint,10,opt,name=focus,proto3" json:"focus,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GridAddItemRequest) Reset() {
	*x = GridAddItemRequest{}
	mi := &file_industries_loosh_yutani_v1_layout_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GridAddItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GridAddItemRequest) ProtoMessage() {}

func (x *GridAddItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_industries_loosh_yutani_v1_layout_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GridAddItemRequest.ProtoReflect.Descriptor instead.
func (*GridAddItemRequest) Descriptor() ([]byte, []int) {
	return file_industries_loosh_yutani_v1_layout_proto_rawDescGZIP(), []int{6}
}

func (x *GridAddItemRequest) GetSessionId() *SessionId {
	if x != nil {
		return x.SessionId
	}
	return nil
}

func (x *GridAddItemRequest) GetGridId() *WidgetId {
	if x != nil {
		return x.GridId
	}
	return nil
}

func (x *GridAddItemRequest) GetItemId() *WidgetId {
	if x != nil {
		return x.ItemId
	}
	return nil
}

func (x *GridAddItemRequest) GetRow() int32 {
	if x != nil {
		return x.Row
	}
	return 0
}

func (x *GridAddItemRequest) GetColumn() int32 {
	if x != nil {
		return x.Column
	}
	return 0
}

func (x *GridAddItemRequest) GetRowSpan() int32 {
	if x != nil {
		return x.RowSpan
	}
	return 0
}

func (x *GridAddItemRequest) GetColumnSpan() int32 {
	if x != nil {
		return x.ColumnSpan
	}
	return 0
}

func (x *GridAddItemRequest) GetMinWidth() int32 {
	if x != nil {
		return x.MinWidth
	}
	return 0
}

func (x *GridAddItemRequest) GetMinHeight() int32 {
	if x != nil {
		return x.MinHeight
	}
	return 0
}

func (x *GridAddItemRequest) GetFocus() bool {
	if x != nil {
		return x.Focus
	}
	return false
}

type GridAddItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GridAddItemResponse) Reset() {
	*x = GridAddItemResponse{}
	mi := &file_industries_loosh_yutani_v1_layout_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GridAddItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GridAddItemResponse) ProtoMessage() {}

func (x *GridAddItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_industries_loosh_yutani_v1_layout_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GridAddItemResponse.ProtoReflect.Descriptor instead.
func (*GridAddItemResponse) Descriptor() ([]byte, []int) {
	return file_industries_loosh_yutani_v1_layout_proto_rawDescGZIP(), []int{7}
}

func (x *GridAddItemResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GridRemoveItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     *SessionId             `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	GridId        *WidgetId              `protobuf:"bytes,2,opt,name=grid_id,json=gridId,proto3" json:"grid_id,omitempty"`
	ItemId        *WidgetId              `protobuf:"bytes,3,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GridRemoveItemRequest) Reset() {
	*x = GridRemoveItemRequest{}
	mi := &file_industries_loosh_yutani_v1_layout_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GridRemoveItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GridRemoveItemRequest) ProtoMessage() {}

func (x *GridRemoveItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_industries_loosh_yutani_v1_layout_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GridRemoveItemRequest.ProtoReflect.Descriptor instead.
func (*GridRemoveItemRequest) Descriptor() ([]byte, []int) {
	return file_industries_loosh_yutani_v1_layout_proto_rawDescGZIP(), []int{8}
}

func (x *GridRemoveItemRequest) GetSessionId() *SessionId {
	if x != nil {
		return x.SessionId
	}
	return nil
}

func (x *GridRemoveItemRequest) GetGridId() *WidgetId {
	if x != nil {
		return x.GridId
	}
	return nil
}

func (x *GridRemoveItemRequest) GetItemId() *WidgetId {
	if x != nil {
		return x.ItemId
	}
	return nil
}

type GridRemoveItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GridRemoveItemResponse) Reset() {
	*x = GridRemoveItemResponse{}
	mi := &file_industries_loosh_yutani_v1_layout_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GridRemoveItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GridRemoveItemResponse) ProtoMessage() {}

func (x *GridRemoveItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_industries_loosh_yutani_v1_layout_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GridRemoveItemResponse.ProtoReflect.Descriptor instead.
func (*GridRemoveItemResponse) Descriptor() ([]byte, []int) {
	return file_industries_loosh_yutani_v1_layout_proto_rawDescGZIP(), []int{9}
}

func (x *GridRemoveItemResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GridSetRowsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     *SessionId             `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	GridId        *WidgetId              `protobuf:"bytes,2,opt,name=grid_id,json=gridId,proto3" json:"grid_id,omitempty"`
	RowSizes      []int32                `protobuf:"varint,3,rep,packed,name=row_sizes,json=rowSizes,proto3" json:"row_sizes,omitempty"` // Negative for proportional, positive for fixed
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GridSetRowsRequest) Reset() {
	*x = GridSetRowsRequest{}
	mi := &file_industries_loosh_yutani_v1_layout_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GridSetRowsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GridSetRowsRequest) ProtoMessage() {}

func (x *GridSetRowsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_industries_loosh_yutani_v1_layout_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GridSetRowsRequest.ProtoReflect.Descriptor instead.
func (*GridSetRowsRequest) Descriptor() ([]byte, []int) {
	return file_industries_loosh_yutani_v1_layout_proto_rawDescGZIP(), []int{10}
}

func (x *GridSetRowsRequest) GetSessionId() *SessionId {
	if x != nil {
		return x.SessionId
	}
	return nil
}

func (x *GridSetRowsRequest) GetGridId() *WidgetId {
	if x != nil {
		return x.GridId
	}
	return nil
}

func (x *GridSetRowsRequest) GetRowSizes() []int32 {
	if x != nil {
		return x.RowSizes
	}
	return nil
}

type GridSetRowsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GridSetRowsResponse) Reset() {
	*x = GridSetRowsResponse{}
	mi := &file_industries_loosh_yutani_v1_layout_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GridSetRowsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GridSetRowsResponse) ProtoMessage() {}

func (x *GridSetRowsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_industries_loosh_yutani_v1_layout_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GridSetRowsResponse.ProtoReflect.Descriptor instead.
func (*GridSetRowsResponse) Descriptor() ([]byte, []int) {
	return file_industries_loosh_yutani_v1_layout_proto_rawDescGZIP(), []int{11}
}

func (x *GridSetRowsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GridSetColumnsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     *SessionId             `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	GridId        *WidgetId              `protobuf:"bytes,2,opt,name=grid_id,json=gridId,proto3" json:"grid_id,omitempty"`
	ColumnSizes   []int32                `protobuf:"varint,3,rep,packed,name=column_sizes,json=columnSizes,proto3" json:"column_sizes,omitempty"` // Negative for proportional, positive for fixed
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GridSetColumnsRequest) Reset() {
	*x = GridSetColumnsRequest{}
	mi := &file_industries_loosh_yutani_v1_layout_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GridSetColumnsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GridSetColumnsRequest) ProtoMessage() {}

func (x *GridSetColumnsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_industries_loosh_yutani_v1_layout_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GridSetColumnsRequest.ProtoReflect.Descriptor instead.
func (*GridSetColumnsRequest) Descriptor() ([]byte, []int) {
	return file_industries_loosh_yutani_v1_layout_proto_rawDescGZIP(), []int{12}
}

func (x *GridSetColumnsRequest) GetSessionId() *SessionId {
	if x != nil {
		return x.SessionId
	}
	return nil
}

func (x *GridSetColumnsRequest) GetGridId() *WidgetId {
	if x != nil {
		return x.GridId
	}
	return nil
}

func (x *GridSetColumnsRequest) GetColumnSizes() []int32 {
	if x != nil {
		return x.ColumnSizes
	}
	return nil
}

type GridSetColumnsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GridSetColumnsResponse) Reset() {
	*x = GridSetColumnsResponse{}
	mi := &file_industries_loosh_yutani_v1_layout_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GridSetColumnsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GridSetColumnsResponse) ProtoMessage() {}

func (x *GridSetColumnsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_industries_loosh_yutani_v1_layout_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GridSetColumnsResponse.ProtoReflect.Descriptor instead.
func (*GridSetColumnsResponse) Descriptor() ([]byte, []int) {
	return file_industries_loosh_yutani_v1_layout_proto_rawDescGZIP(), []int{13}
}

func (x *GridSetColumnsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type PagesAddPageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     *SessionId             `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	PagesId       *WidgetId              `protobuf:"bytes,2,opt,name=pages_id,json=pagesId,proto3" json:"pages_id,omitempty"`
	PageName      string                 `protobuf:"bytes,3,opt,name=page_name,json=pageName,proto3" json:"page_name,omitempty"`
	ItemId        *WidgetId              `protobuf:"bytes,4,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Resize        bool                   `protobuf:"varint,5,opt,name=resize,proto3" json:"resize,omitempty"`
	Visible       bool                   `protobuf:"varint,6,opt,name=visible,proto3" json:"visible,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PagesAddPageRequest) Reset() {
	*x = PagesAddPageRequest{}
	mi := &file_industries_loosh_yutani_v1_layout_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PagesAddPageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PagesAddPageRequest) ProtoMessage() {}

func (x *PagesAddPageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_industries_loosh_yutani_v1_layout_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PagesAddPageRequest.ProtoReflect.Descriptor instead.
func (*PagesAddPageRequest) Descriptor() ([]byte, []int) {
	return file_industries_loosh_yutani_v1_layout_proto_rawDescGZIP(), []int{14}
}

func (x *PagesAddPageRequest) GetSessionId() *SessionId {
	if x != nil {
		return x.SessionId
	}
	return nil
}

func (x *PagesAddPageRequest) GetPagesId() *WidgetId {
	if x != nil {
		return x.PagesId
	}
	return nil
}

func (x *PagesAddPageRequest) GetPageName() string {
	if x != nil {
		return x.PageName
	}
	return ""
}

func (x *PagesAddPageRequest) GetItemId() *WidgetId {
	if x != nil {
		return x.ItemId
	}
	return nil
}

func (x *PagesAddPageRequest) GetResize() bool {
	if x != nil {
		return x.Resize
	}
	return false
}

func (x *PagesAddPageRequest) GetVisible() bool {
	if x != nil {
		return x.Visible
	}
	return false
}

type PagesAddPageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PagesAddPageResponse) Reset() {
	*x = PagesAddPageResponse{}
	mi := &file_industries_loosh_yutani_v1_layout_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PagesAddPageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PagesAddPageResponse) ProtoMessage() {}

func (x *PagesAddPageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_industries_loosh_yutani_v1_layout_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PagesAddPageResponse.ProtoReflect.Descriptor instead.
func (*PagesAddPageResponse) Descriptor() ([]byte, []int) {
	return file_industries_loosh_yutani_v1_layout_proto_rawDescGZIP(), []int{15}
}

func (x *PagesAddPageResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type PagesRemovePageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     *SessionId             `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	PagesId       *WidgetId              `protobuf:"bytes,2,opt,name=pages_id,json=pagesId,proto3" json:"pages_id,omitempty"`
	PageName      string                 `protobuf:"bytes,3,opt,name=page_name,json=pageName,proto3" json:"page_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PagesRemovePageRequest) Reset() {
	*x = PagesRemovePageRequest{}
	mi := &file_industries_loosh_yutani_v1_layout_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PagesRemovePageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PagesRemovePageRequest) ProtoMessage() {}

func (x *PagesRemovePageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_industries_loosh_yutani_v1_layout_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PagesRemovePageRequest.ProtoReflect.Descriptor instead.
func (*PagesRemovePageRequest) Descriptor() ([]byte, []int) {
	return file_industries_loosh_yutani_v1_layout_proto_rawDescGZIP(), []int{16}
}

func (x *PagesRemovePageRequest) GetSessionId() *SessionId {
	if x != nil {
		return x.SessionId
	}
	return nil
}

func (x *PagesRemovePageRequest) GetPagesId() *WidgetId {
	if x != nil {
		return x.PagesId
	}
	return nil
}

func (x *PagesRemovePageRequest) GetPageName() string {
	if x != nil {
		return x.PageName
	}
	return ""
}

type PagesRemovePageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PagesRemovePageResponse) Reset() {
	*x = PagesRemovePageResponse{}
	mi := &file_industries_loosh_yutani_v1_layout_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PagesRemovePageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PagesRemovePageResponse) ProtoMessage() {}

func (x *PagesRemovePageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_industries_loosh_yutani_v1_layout_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PagesRemovePageResponse.ProtoReflect.Descriptor instead.
func (*PagesRemovePageResponse) Descriptor() ([]byte, []int) {
	return file_industries_loosh_yutani_v1_layout_proto_rawDescGZIP(), []int{17}
}

func (x *PagesRemovePageResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type PagesShowPageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     *SessionId             `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	PagesId       *WidgetId              `protobuf:"bytes,2,opt,name=pages_id,json=pagesId,proto3" json:"pages_id,omitempty"`
	PageName      string                 `protobuf:"bytes,3,opt,name=page_name,json=pageName,proto3" json:"page_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PagesShowPageRequest) Reset() {
	*x = PagesShowPageRequest{}
	mi := &file_industries_loosh_yutani_v1_layout_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PagesShowPageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PagesShowPageRequest) ProtoMessage() {}

func (x *PagesShowPageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_industries_loosh_yutani_v1_layout_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PagesShowPageRequest.ProtoReflect.Descriptor instead.
func (*PagesShowPageRequest) Descriptor() ([]byte, []int) {
	return file_industries_loosh_yutani_v1_layout_proto_rawDescGZIP(), []int{18}
}

func (x *PagesShowPageRequest) GetSessionId() *SessionId {
	if x != nil {
		return x.SessionId
	}
	return nil
}

func (x *PagesShowPageRequest) GetPagesId() *WidgetId {
	if x != nil {
		return x.PagesId
	}
	return nil
}

func (x *PagesShowPageRequest) GetPageName() string {
	if x != nil {
		return x.PageName
	}
	return ""
}

type PagesShowPageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PagesShowPageResponse) Reset() {
	*x = PagesShowPageResponse{}
	mi := &file_industries_loosh_yutani_v1_layout_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PagesShowPageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PagesShowPageResponse) ProtoMessage() {}

func (x *PagesShowPageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_industries_loosh_yutani_v1_layout_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PagesShowPageResponse.ProtoReflect.Descriptor instead.
func (*PagesShowPageResponse) Descriptor() ([]byte, []int) {
	return file_industries_loosh_yutani_v1_layout_proto_rawDescGZIP(), []int{19}
}

func (x *PagesShowPageResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type PagesGetCurrentPageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     *SessionId             `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	PagesId       *WidgetId              `protobuf:"bytes,2,opt,name=pages_id,json=pagesId,proto3" json:"pages_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PagesGetCurrentPageRequest) Reset() {
	*x = PagesGetCurrentPageRequest{}
	mi := &file_industries_loosh_yutani_v1_layout_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PagesGetCurrentPageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PagesGetCurrentPageRequest) ProtoMessage() {}

func (x *PagesGetCurrentPageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_industries_loosh_yutani_v1_layout_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PagesGetCurrentPageRequest.ProtoReflect.Descriptor instead.
func (*PagesGetCurrentPageRequest) Descriptor() ([]byte, []int) {
	return file_industries_loosh_yutani_v1_layout_proto_rawDescGZIP(), []int{20}
}

func (x *PagesGetCurrentPageRequest) GetSessionId() *SessionId {
	if x != nil {
		return x.SessionId
	}
	return nil
}

func (x *PagesGetCurrentPageRequest) GetPagesId() *WidgetId {
	if x != nil {
		return x.PagesId
	}
	return nil
}

type PagesGetCurrentPageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageName      string                 `protobuf:"bytes,1,opt,name=page_name,json=pageName,proto3" json:"page_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PagesGetCurrentPageResponse) Reset() {
	*x = PagesGetCurrentPageResponse{}
	mi := &file_industries_loosh_yutani_v1_layout_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PagesGetCurrentPageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PagesGetCurrentPageResponse) ProtoMessage() {}

func (x *PagesGetCurrentPageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_industries_loosh_yutani_v1_layout_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PagesGetCurrentPageResponse.ProtoReflect.Descriptor instead.
func (*PagesGetCurrentPageResponse) Descriptor() ([]byte, []int) {
	return file_industries_loosh_yutani_v1_layout_proto_rawDescGZIP(), []int{21}
}

func (x *PagesGetCurrentPageResponse) GetPageName() string {
	if x != nil {
		return x.PageName
	}
	return ""
}

var File_industries_loosh_yutani_v1_layout_proto protoreflect.FileDescriptor

const file_industries_loosh_yutani_v1_layout_proto_rawDesc = "" +
	"\n" +
	"'industries/loosh/yutani/v1/layout.proto\x12\x1aindustries.loosh.yutani.v1\x1a&industries/loosh/yutani/v1/types.proto\"\xad\x02\n" +
	"\x12FlexAddItemRequest\x12D\n" +
	"\n" +
	"session_id\x18\x01 \x01(\v2%.industries.loosh.yutani.v1.SessionIdR\tsessionId\x12=\n" +
	"\aflex_id\x18\x02 \x01(\v2$.industries.loosh.yutani.v1.WidgetIdR\x06flexId\x12=\n" +
	"\aitem_id\x18\x03 \x01(\v2$.industries.loosh.yutani.v1.WidgetIdR\x06itemId\x12\x1e\n" +
	"\n" +
	"proportion\x18\x04 \x01(\x05R\n" +
	"proportion\x12\x1d\n" +
	"\n" +
	"fixed_size\x18\x05 \x01(\x05R\tfixedSize\x12\x14\n" +
	"\x05focus\x18\x06 \x01(\bR\x05focus\"/\n" +
	"\x13FlexAddItemResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xdb\x01\n" +
	"\x15FlexRemoveItemRequest\x12D\n" +
	"\n" +
	"session_id\x18\x01 \x01(\v2%.industries.loosh.yutani.v1.SessionIdR\tsessionId\x12=\n" +
	"\aflex_id\x18\x02 \x01(\v2$.industries.loosh.yutani.v1.WidgetIdR\x06flexId\x12=\n" +
	"\aitem_id\x18\x03 \x01(\v2$.industries.loosh.yutani.v1.WidgetIdR\x06itemId\"2\n" +
	"\x16FlexRemoveItemResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xe7\x01\n" +
	"\x17FlexSetDirectionRequest\x12D\n" +
	"\n" +
	"session_id\x18\x01 \x01(\v2%.industries.loosh.yutani.v1.SessionIdR\tsessionId\x12=\n" +
	"\aflex_id\x18\x02 \x01(\v2$.industries.loosh.yutani.v1.WidgetIdR\x06flexId\x12G\n" +
	"\tdirection\x18\x03 \x01(\x0e2).industries.loosh.yutani.v1.FlexDirectionR\tdirection\"4\n" +
	"\x18FlexSetDirectionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x90\x03\n" +
	"\x12GridAddItemRequest\x12D\n" +
	"\n" +
	"session_id\x18\x01 \x01(\v2%.industries.loosh.yutani.v1.SessionIdR\tsessionId\x12=\n" +
	"\agrid_id\x18\x02 \x01(\v2$.industries.loosh.yutani.v1.WidgetIdR\x06gridId\x12=\n" +
	"\aitem_id\x18\x03 \x01(\v2$.industries.loosh.yutani.v1.WidgetIdR\x06itemId\x12\x10\n" +
	"\x03row\x18\x04 \x01(\x05R\x03row\x12\x16\n" +
	"\x06column\x18\x05 \x01(\x05R\x06column\x12\x19\n" +
	"\brow_span\x18\x06 \x01(\x05R\arowSpan\x12\x1f\n" +
	"\vcolumn_span\x18\a \x01(\x05R\n" +
	"columnSpan\x12\x1b\n" +
	"\tmin_width\x18\b \x01(\x05R\bminWidth\x12\x1d\n" +
	"\n" +
	"min_height\x18\t \x01(\x05R\tminHeight\x12\x14\n" +
	"\x05focus\x18\n" +
	" \x01(\bR\x05focus\"/\n" +
	"\x13GridAddItemResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xdb\x01\n" +
	"\x15GridRemoveItemRequest\x12D\n" +
	"\n" +
	"session_id\x18\x01 \x01(\v2%.industries.loosh.yutani.v1.SessionIdR\tsessionId\x12=\n" +
	"\agrid_id\x18\x02 \x01(\v2$.industries.loosh.yutani.v1.WidgetIdR\x06gridId\x12=\n" +
	"\aitem_id\x18\x03 \x01(\v2$.industries.loosh.yutani.v1.WidgetIdR\x06itemId\"2\n" +
	"\x16GridRemoveItemResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xb6\x01\n" +
	"\x12GridSetRowsRequest\x12D\n" +
	"\n" +
	"session_id\x18\x01 \x01(\v2%.industries.loosh.yutani.v1.SessionIdR\tsessionId\x12=\n" +
	"\agrid_id\x18\x02 \x01(\v2$.industries.loosh.yutani.v1.WidgetIdR\x06gridId\x12\x1b\n" +
	"\trow_sizes\x18\x03 \x03(\x05R\browSizes\"/\n" +
	"\x13GridSetRowsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xbf\x01\n" +
	"\x15GridSetColumnsRequest\x12D\n" +
	"\n" +
	"session_id\x18\x01 \x01(\v2%.industries.loosh.yutani.v1.SessionIdR\tsessionId\x12=\n" +
	"\agrid_id\x18\x02 \x01(\v2$.industries.loosh.yutani.v1.WidgetIdR\x06gridId\x12!\n" +
	"\fcolumn_sizes\x18\x03 \x03(\x05R\vcolumnSizes\"2\n" +
	"\x16GridSetColumnsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xaa\x02\n" +
	"\x13PagesAddPageRequest\x12D\n" +
	"\n" +
	"session_id\x18\x01 \x01(\v2%.industries.loosh.yutani.v1.SessionIdR\tsessionId\x12?\n" +
	"\bpages_id\x18\x02 \x01(\v2$.industries.loosh.yutani.v1.WidgetIdR\apagesId\x12\x1b\n" +
	"\tpage_name\x18\x03 \x01(\tR\bpageName\x12=\n" +
	"\aitem_id\x18\x04 \x01(\v2$.industries.loosh.yutani.v1.WidgetIdR\x06itemId\x12\x16\n" +
	"\x06resize\x18\x05 \x01(\bR\x06resize\x12\x18\n" +
	"\avisible\x18\x06 \x01(\bR\avisible\"0\n" +
	"\x14PagesAddPageResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xbc\x01\n" +
	"\x16PagesRemovePageRequest\x12D\n" +
	"\n" +
	"session_id\x18\x01 \x01(\v2%.industries.loosh.yutani.v1.SessionIdR\tsessionId\x12?\n" +
	"\bpages_id\x18\x02 \x01(\v2$.industries.loosh.yutani.v1.WidgetIdR\apagesId\x12\x1b\n" +
	"\tpage_name\x18\x03 \x01(\tR\bpageName\"3\n" +
	"\x17PagesRemovePageResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xba\x01\n" +
	"\x14PagesShowPageRequest\x12D\n" +
	"\n" +
	"session_id\x18\x01 \x01(\v2%.industries.loosh.yutani.v1.SessionIdR\tsessionId\x12?\n" +
	"\bpages_id\x18\x02 \x01(\v2$.industries.loosh.yutani.v1.WidgetIdR\apagesId\x12\x1b\n" +
	"\tpage_name\x18\x03 \x01(\tR\bpageName\"1\n" +
	"\x15PagesShowPageResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xa3\x01\n" +
	"\x1aPagesGetCurrentPageRequest\x12D\n" +
	"\n" +
	"session_id\x18\x01 \x01(\v2%.industries.loosh.yutani.v1.SessionIdR\tsessionId\x12?\n" +
	"\bpages_id\x18\x02 \x01(\v2$.industries.loosh.yutani.v1.WidgetIdR\apagesId\":\n" +
	"\x1bPagesGetCurrentPageResponse\x12\x1b\n" +
	"\tpage_name\x18\x01 \x01(\tR\bpageName2\xb7\n" +
	"\n" +
	"\rLayoutService\x12n\n" +
	"\vFlexAddItem\x12..industries.loosh.yutani.v1.FlexAddItemRequest\x1a/.industries.loosh.yutani.v1.FlexAddItemResponse\x12w\n" +
	"\x0eFlexRemoveItem\x121.industries.loosh.yutani.v1.FlexRemoveItemRequest\x1a2.industries.loosh.yutani.v1.FlexRemoveItemResponse\x12}\n" +
	"\x10FlexSetDirection\x123.industries.loosh.yutani.v1.FlexSetDirectionRequest\x1a4.industries.loosh.yutani.v1.FlexSetDirectionResponse\x12n\n" +
	"\vGridAddItem\x12..industries.loosh.yutani.v1.GridAddItemRequest\x1a/.industries.loosh.yutani.v1.GridAddItemResponse\x12w\n" +
	"\x0eGridRemoveItem\x121.industries.loosh.yutani.v1.GridRemoveItemRequest\x1a2.industries.loosh.yutani.v1.GridRemoveItemResponse\x12n\n" +
	"\vGridSetRows\x12..industries.loosh.yutani.v1.GridSetRowsRequest\x1a/.industries.loosh.yutani.v1.GridSetRowsResponse\x12w\n" +
	"\x0eGridSetColumns\x121.industries.loosh.yutani.v1.GridSetColumnsRequest\x1a2.industries.loosh.yutani.v1.GridSetColumnsResponse\x12q\n" +
	"\fPagesAddPage\x12/.industries.loosh.yutani.v1.PagesAddPageRequest\x1a0.industries.loosh.yutani.v1.PagesAddPageResponse\x12z\n" +
	"\x0fPagesRemovePage\x122.industries.loosh.yutani.v1.PagesRemovePageRequest\x1a3.industries.loosh.yutani.v1.PagesRemovePageResponse\x12t\n" +
	"\rPagesShowPage\x120.industries.loosh.yutani.v1.PagesShowPageRequest\x1a1.industries.loosh.yutani.v1.PagesShowPageResponse\x12\x86\x01\n" +
	"\x13PagesGetCurrentPage\x126.industries.loosh.yutani.v1.PagesGetCurrentPageRequest\x1a7.industries.loosh.yutani.v1.PagesGetCurrentPageResponseB*Z(github.com/chazu/yutani/pkg/proto/yutanib\x06proto3"

var (
	file_industries_loosh_yutani_v1_layout_proto_rawDescOnce sync.Once
	file_industries_loosh_yutani_v1_layout_proto_rawDescData []byte
)

func file_industries_loosh_yutani_v1_layout_proto_rawDescGZIP() []byte {
	file_industries_loosh_yutani_v1_layout_proto_rawDescOnce.Do(func() {
		file_industries_loosh_yutani_v1_layout_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_industries_loosh_yutani_v1_layout_proto_rawDesc), len(file_industries_loosh_yutani_v1_layout_proto_rawDesc)))
	})
	return file_industries_loosh_yutani_v1_layout_proto_rawDescData
}

var file_industries_loosh_yutani_v1_layout_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_industries_loosh_yutani_v1_layout_proto_goTypes = []any{
	(*FlexAddItemRequest)(nil),          // 0: industries.loosh.yutani.v1.FlexAddItemRequest
	(*FlexAddItemResponse)(nil),         // 1: industries.loosh.yutani.v1.FlexAddItemResponse
	(*FlexRemoveItemRequest)(nil),       // 2: industries.loosh.yutani.v1.FlexRemoveItemRequest
	(*FlexRemoveItemResponse)(nil),      // 3: industries.loosh.yutani.v1.FlexRemoveItemResponse
	(*FlexSetDirectionRequest)(nil),     // 4: industries.loosh.yutani.v1.FlexSetDirectionRequest
	(*FlexSetDirectionResponse)(nil),    // 5: industries.loosh.yutani.v1.FlexSetDirectionResponse
	(*GridAddItemRequest)(nil),          // 6: industries.loosh.yutani.v1.GridAddItemRequest
	(*GridAddItemResponse)(nil),         // 7: industries.loosh.yutani.v1.GridAddItemResponse
	(*GridRemoveItemRequest)(nil),       // 8: industries.loosh.yutani.v1.GridRemoveItemRequest
	(*GridRemoveItemResponse)(nil),      // 9: industries.loosh.yutani.v1.GridRemoveItemResponse
	(*GridSetRowsRequest)(nil),          // 10: industries.loosh.yutani.v1.GridSetRowsRequest
	(*GridSetRowsResponse)(nil),         // 11: industries.loosh.yutani.v1.GridSetRowsResponse
	(*GridSetColumnsRequest)(nil),       // 12: industries.loosh.yutani.v1.GridSetColumnsRequest
	(*GridSetColumnsResponse)(nil),      // 13: industries.loosh.yutani.v1.GridSetColumnsResponse
	(*PagesAddPageRequest)(nil),         // 14: industries.loosh.yutani.v1.PagesAddPageRequest
	(*PagesAddPageResponse)(nil),        // 15: industries.loosh.yutani.v1.PagesAddPageResponse
	(*PagesRemovePageRequest)(nil),      // 16: industries.loosh.yutani.v1.PagesRemovePageRequest
	(*PagesRemovePageResponse)(nil),     // 17: industries.loosh.yutani.v1.PagesRemovePageResponse
	(*PagesShowPageRequest)(nil),        // 18: industries.loosh.yutani.v1.PagesShowPageRequest
	(*PagesShowPageResponse)(nil),       // 19: industries.loosh.yutani.v1.PagesShowPageResponse
	(*PagesGetCurrentPageRequest)(nil),  // 20: industries.loosh.yutani.v1.PagesGetCurrentPageRequest
	(*PagesGetCurrentPageResponse)(nil), // 21: industries.loosh.yutani.v1.PagesGetCurrentPageResponse
	(*SessionId)(nil),                   // 22: industries.loosh.yutani.v1.SessionId
	(*WidgetId)(nil),                    // 23: industries.loosh.yutani.v1.WidgetId
	(FlexDirection)(0),                  // 24: industries.loosh.yutani.v1.FlexDirection
}
var file_industries_loosh_yutani_v1_layout_proto_depIdxs = []int32{
	22, // 0: industries.loosh.yutani.v1.FlexAddItemRequest.session_id:type_name -> industries.loosh.yutani.v1.SessionId
	23, // 1: industries.loosh.yutani.v1.FlexAddItemRequest.flex_id:type_name -> industries.loosh.yutani.v1.WidgetId
	23, // 2: industries.loosh.yutani.v1.FlexAddItemRequest.item_id:type_name -> industries.loosh.yutani.v1.WidgetId
	22, // 3: industries.loosh.yutani.v1.FlexRemoveItemRequest.session_id:type_name -> industries.loosh.yutani.v1.SessionId
	23, // 4: industries.loosh.yutani.v1.FlexRemoveItemRequest.flex_id:type_name -> industries.loosh.yutani.v1.WidgetId
	23, // 5: industries.loosh.yutani.v1.FlexRemoveItemRequest.item_id:type_name -> industries.loosh.yutani.v1.WidgetId
	22, // 6: industries.loosh.yutani.v1.FlexSetDirectionRequest.session_id:type_name -> industries.loosh.yutani.v1.SessionId
	23, // 7: industries.loosh.yutani.v1.FlexSetDirectionRequest.flex_id:type_name -> industries.loosh.yutani.v1.WidgetId
	24, // 8: industries.loosh.yutani.v1.FlexSetDirectionRequest.direction:type_name -> industries.loosh.yutani.v1.FlexDirection
	22, // 9: industries.loosh.yutani.v1.GridAddItemRequest.session_id:type_name -> industries.loosh.yutani.v1.SessionId
	23, // 10: industries.loosh.yutani.v1.GridAddItemRequest.grid_id:type_name -> industries.loosh.yutani.v1.WidgetId
	23, // 11: industries.loosh.yutani.v1.GridAddItemRequest.item_id:type_name -> industries.loosh.yutani.v1.WidgetId
	22, // 12: industries.loosh.yutani.v1.GridRemoveItemRequest.session_id:type_name -> industries.loosh.yutani.v1.SessionId
	23, // 13: industries.loosh.yutani.v1.GridRemoveItemRequest.grid_id:type_name -> industries.loosh.yutani.v1.WidgetId
	23, // 14: industries.loosh.yutani.v1.GridRemoveItemRequest.item_id:type_name -> industries.loosh.yutani.v1.WidgetId
	22, // 15: industries.loosh.yutani.v1.GridSetRowsRequest.session_id:type_name -> industries.loosh.yutani.v1.SessionId
	23, // 16: industries.loosh.yutani.v1.GridSetRowsRequest.grid_id:type_name -> industries.loosh.yutani.v1.WidgetId
	22, // 17: industries.loosh.yutani.v1.GridSetColumnsRequest.session_id:type_name -> industries.loosh.yutani.v1.SessionId
	23, // 18: industries.loosh.yutani.v1.GridSetColumnsRequest.grid_id:type_name -> industries.loosh.yutani.v1.WidgetId
	22, // 19: industries.loosh.yutani.v1.PagesAddPageRequest.session_id:type_name -> industries.loosh.yutani.v1.SessionId
	23, // 20: industries.loosh.yutani.v1.PagesAddPageRequest.pages_id:type_name -> industries.loosh.yutani.v1.WidgetId
	23, // 21: industries.loosh.yutani.v1.PagesAddPageRequest.item_id:type_name -> industries.loosh.yutani.v1.WidgetId
	22, // 22: industries.loosh.yutani.v1.PagesRemovePageRequest.session_id:type_name -> industries.loosh.yutani.v1.SessionId
	23, // 23: industries.loosh.yutani.v1.PagesRemovePageRequest.pages_id:type_name -> industries.loosh.yutani.v1.WidgetId
	22, // 24: industries.loosh.yutani.v1.PagesShowPageRequest.session_id:type_name -> industries.loosh.yutani.v1.SessionId
	23, // 25: industries.loosh.yutani.v1.PagesShowPageRequest.pages_id:type_name -> industries.loosh.yutani.v1.WidgetId
	22, // 26: industries.loosh.yutani.v1.PagesGetCurrentPageRequest.session_id:type_name -> industries.loosh.yutani.v1.SessionId
	23, // 27: industries.loosh.yutani.v1.PagesGetCurrentPageRequest.pages_id:type_name -> industries.loosh.yutani.v1.WidgetId
	0,  // 28: industries.loosh.yutani.v1.LayoutService.FlexAddItem:input_type -> industries.loosh.yutani.v1.FlexAddItemRequest
	2,  // 29: industries.loosh.yutani.v1.LayoutService.FlexRemoveItem:input_type -> industries.loosh.yutani.v1.FlexRemoveItemRequest
	4,  // 30: industries.loosh.yutani.v1.LayoutService.FlexSetDirection:input_type -> industries.loosh.yutani.v1.FlexSetDirectionRequest
	6,  // 31: industries.loosh.yutani.v1.LayoutService.GridAddItem:input_type -> industries.loosh.yutani.v1.GridAddItemRequest
	8,  // 32: industries.loosh.yutani.v1.LayoutService.GridRemoveItem:input_type -> industries.loosh.yutani.v1.GridRemoveItemRequest
	10, // 33: industries.loosh.yutani.v1.LayoutService.GridSetRows:input_type -> industries.loosh.yutani.v1.GridSetRowsRequest
	12, // 34: industries.loosh.yutani.v1.LayoutService.GridSetColumns:input_type -> industries.loosh.yutani.v1.GridSetColumnsRequest
	14, // 35: industries.loosh.yutani.v1.LayoutService.PagesAddPage:input_type -> industries.loosh.yutani.v1.PagesAddPageRequest
	16, // 36: industries.loosh.yutani.v1.LayoutService.PagesRemovePage:input_type -> industries.loosh.yutani.v1.PagesRemovePageRequest
	18, // 37: industries.loosh.yutani.v1.LayoutService.PagesShowPage:input_type -> industries.loosh.yutani.v1.PagesShowPageRequest
	20, // 38: industries.loosh.yutani.v1.LayoutService.PagesGetCurrentPage:input_type -> industries.loosh.yutani.v1.PagesGetCurrentPageRequest
	1,  // 39: industries.loosh.yutani.v1.LayoutService.FlexAddItem:output_type -> industries.loosh.yutani.v1.FlexAddItemResponse
	3,  // 40: industries.loosh.yutani.v1.LayoutService.FlexRemoveItem:output_type -> industries.loosh.yutani.v1.FlexRemoveItemResponse
	5,  // 41: industries.loosh.yutani.v1.LayoutService.FlexSetDirection:output_type -> industries.loosh.yutani.v1.FlexSetDirectionResponse
	7,  // 42: industries.loosh.yutani.v1.LayoutService.GridAddItem:output_type -> industries.loosh.yutani.v1.GridAddItemResponse
	9,  // 43: industries.loosh.yutani.v1.LayoutService.GridRemoveItem:output_type -> industries.loosh.yutani.v1.GridRemoveItemResponse
	11, // 44: industries.loosh.yutani.v1.LayoutService.GridSetRows:output_type -> industries.loosh.yutani.v1.GridSetRowsResponse
	13, // 45: industries.loosh.yutani.v1.LayoutService.GridSetColumns:output_type -> industries.loosh.yutani.v1.GridSetColumnsResponse
	15, // 46: industries.loosh.yutani.v1.LayoutService.PagesAddPage:output_type -> industries.loosh.yutani.v1.PagesAddPageResponse
	17, // 47: industries.loosh.yutani.v1.LayoutService.PagesRemovePage:output_type -> industries.loosh.yutani.v1.PagesRemovePageResponse
	19, // 48: industries.loosh.yutani.v1.LayoutService.PagesShowPage:output_type -> industries.loosh.yutani.v1.PagesShowPageResponse
	21, // 49: industries.loosh.yutani.v1.LayoutService.PagesGetCurrentPage:output_type -> industries.loosh.yutani.v1.PagesGetCurrentPageResponse
	39, // [39:50] is the sub-list for method output_type
	28, // [28:39] is the sub-list for method input_type
	28, // [28:28] is the sub-list for extension type_name
	28, // [28:28] is the sub-list for extension extendee
	0,  // [0:28] is the sub-list for field type_name
}

func init() { file_industries_loosh_yutani_v1_layout_proto_init() }
func file_industries_loosh_yutani_v1_layout_proto_init() {
	if File_industries_loosh_yutani_v1_layout_proto != nil {
		return
	}
	file_industries_loosh_yutani_v1_types_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_industries_loosh_yutani_v1_layout_proto_rawDesc), len(file_industries_loosh_yutani_v1_layout_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_industries_loosh_yutani_v1_layout_proto_goTypes,
		DependencyIndexes: file_industries_loosh_yutani_v1_layout_proto_depIdxs,
		MessageInfos:      file_industries_loosh_yutani_v1_layout_proto_msgTypes,
	}.Build()
	File_industries_loosh_yutani_v1_layout_proto = out.File
	file_industries_loosh_yutani_v1_layout_proto_goTypes = nil
	file_industries_loosh_yutani_v1_layout_proto_depIdxs = nil
}
