// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v5.29.3
// source: industries/loosh/yutani/v1/layout.proto

package yutani

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LayoutService_FlexAddItem_FullMethodName         = "/industries.loosh.yutani.v1.LayoutService/FlexAddItem"
	LayoutService_FlexRemoveItem_FullMethodName      = "/industries.loosh.yutani.v1.LayoutService/FlexRemoveItem"
	LayoutService_FlexSetDirection_FullMethodName    = "/industries.loosh.yutani.v1.LayoutService/FlexSetDirection"
	LayoutService_GridAddItem_FullMethodName         = "/industries.loosh.yutani.v1.LayoutService/GridAddItem"
	LayoutService_GridRemoveItem_FullMethodName      = "/industries.loosh.yutani.v1.LayoutService/GridRemoveItem"
	LayoutService_GridSetRows_FullMethodName         = "/industries.loosh.yutani.v1.LayoutService/GridSetRows"
	LayoutService_GridSetColumns_FullMethodName      = "/industries.loosh.yutani.v1.LayoutService/GridSetColumns"
	LayoutService_PagesAddPage_FullMethodName        = "/industries.loosh.yutani.v1.LayoutService/PagesAddPage"
	LayoutService_PagesRemovePage_FullMethodName     = "/industries.loosh.yutani.v1.LayoutService/PagesRemovePage"
	LayoutService_PagesShowPage_FullMethodName       = "/industries.loosh.yutani.v1.LayoutService/PagesShowPage"
	LayoutService_PagesGetCurrentPage_FullMethodName = "/industries.loosh.yutani.v1.LayoutService/PagesGetCurrentPage"
)

// LayoutServiceClient is the client API for LayoutService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// LayoutService provides operations for layout containers (Flex, Grid, Pages)
type LayoutServiceClient interface {
	// Flex operations
	FlexAddItem(ctx context.Context, in *FlexAddItemRequest, opts ...grpc.CallOption) (*FlexAddItemResponse, error)
	FlexRemoveItem(ctx context.Context, in *FlexRemoveItemRequest, opts ...grpc.CallOption) (*FlexRemoveItemResponse, error)
	FlexSetDirection(ctx context.Context, in *FlexSetDirectionRequest, opts ...grpc.CallOption) (*FlexSetDirectionResponse, error)
	// Grid operations
	GridAddItem(ctx context.Context, in *GridAddItemRequest, opts ...grpc.CallOption) (*GridAddItemResponse, error)
	GridRemoveItem(ctx context.Context, in *GridRemoveItemRequest, opts ...grpc.CallOption) (*GridRemoveItemResponse, error)
	GridSetRows(ctx context.Context, in *GridSetRowsRequest, opts ...grpc.CallOption) (*GridSetRowsResponse, error)
	GridSetColumns(ctx context.Context, in *GridSetColumnsRequest, opts ...grpc.CallOption) (*GridSetColumnsResponse, error)
	// Pages operations
	PagesAddPage(ctx context.Context, in *PagesAddPageRequest, opts ...grpc.CallOption) (*PagesAddPageResponse, error)
	PagesRemovePage(ctx context.Context, in *PagesRemovePageRequest, opts ...grpc.CallOption) (*PagesRemovePageResponse, error)
	PagesShowPage(ctx context.Context, in *PagesShowPageRequest, opts ...grpc.CallOption) (*PagesShowPageResponse, error)
	PagesGetCurrentPage(ctx context.Context, in *PagesGetCurrentPageRequest, opts ...grpc.CallOption) (*PagesGetCurrentPageResponse, error)
}

type layoutServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLayoutServiceClient(cc grpc.ClientConnInterface) LayoutServiceClient {
	return &layoutServiceClient{cc}
}

func (c *layoutServiceClient) FlexAddItem(ctx context.Context, in *FlexAddItemRequest, opts ...grpc.CallOption) (*FlexAddItemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FlexAddItemResponse)
	err := c.cc.Invoke(ctx, LayoutService_FlexAddItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *layoutServiceClient) FlexRemoveItem(ctx context.Context, in *FlexRemoveItemRequest, opts ...grpc.CallOption) (*FlexRemoveItemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FlexRemoveItemResponse)
	err := c.cc.Invoke(ctx, LayoutService_FlexRemoveItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *layoutServiceClient) FlexSetDirection(ctx context.Context, in *FlexSetDirectionRequest, opts ...grpc.CallOption) (*FlexSetDirectionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FlexSetDirectionResponse)
	err := c.cc.Invoke(ctx, LayoutService_FlexSetDirection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *layoutServiceClient) GridAddItem(ctx context.Context, in *GridAddItemRequest, opts ...grpc.CallOption) (*GridAddItemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GridAddItemResponse)
	err := c.cc.Invoke(ctx, LayoutService_GridAddItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *layoutServiceClient) GridRemoveItem(ctx context.Context, in *GridRemoveItemRequest, opts ...grpc.CallOption) (*GridRemoveItemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GridRemoveItemResponse)
	err := c.cc.Invoke(ctx, LayoutService_GridRemoveItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *layoutServiceClient) GridSetRows(ctx context.Context, in *GridSetRowsRequest, opts ...grpc.CallOption) (*GridSetRowsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GridSetRowsResponse)
	err := c.cc.Invoke(ctx, LayoutService_GridSetRows_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *layoutServiceClient) GridSetColumns(ctx context.Context, in *GridSetColumnsRequest, opts ...grpc.CallOption) (*GridSetColumnsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GridSetColumnsResponse)
	err := c.cc.Invoke(ctx, LayoutService_GridSetColumns_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *layoutServiceClient) PagesAddPage(ctx context.Context, in *PagesAddPageRequest, opts ...grpc.CallOption) (*PagesAddPageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PagesAddPageResponse)
	err := c.cc.Invoke(ctx, LayoutService_PagesAddPage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *layoutServiceClient) PagesRemovePage(ctx context.Context, in *PagesRemovePageRequest, opts ...grpc.CallOption) (*PagesRemovePageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PagesRemovePageResponse)
	err := c.cc.Invoke(ctx, LayoutService_PagesRemovePage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *layoutServiceClient) PagesShowPage(ctx context.Context, in *PagesShowPageRequest, opts ...grpc.CallOption) (*PagesShowPageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PagesShowPageResponse)
	err := c.cc.Invoke(ctx, LayoutService_PagesShowPage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *layoutServiceClient) PagesGetCurrentPage(ctx context.Context, in *PagesGetCurrentPageRequest, opts ...grpc.CallOption) (*PagesGetCurrentPageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PagesGetCurrentPageResponse)
	err := c.cc.Invoke(ctx, LayoutService_PagesGetCurrentPage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LayoutServiceServer is the server API for LayoutService service.
// All implementations must embed UnimplementedLayoutServiceServer
// for forward compatibility.
//
// LayoutService provides operations for layout containers (Flex, Grid, Pages)
type LayoutServiceServer interface {
	// Flex operations
	FlexAddItem(context.Context, *FlexAddItemRequest) (*FlexAddItemResponse, error)
	FlexRemoveItem(context.Context, *FlexRemoveItemRequest) (*FlexRemoveItemResponse, error)
	FlexSetDirection(context.Context, *FlexSetDirectionRequest) (*FlexSetDirectionResponse, error)
	// Grid operations
	GridAddItem(context.Context, *GridAddItemRequest) (*GridAddItemResponse, error)
	GridRemoveItem(context.Context, *GridRemoveItemRequest) (*GridRemoveItemResponse, error)
	GridSetRows(context.Context, *GridSetRowsRequest) (*GridSetRowsResponse, error)
	GridSetColumns(context.Context, *GridSetColumnsRequest) (*GridSetColumnsResponse, error)
	// Pages operations
	PagesAddPage(context.Context, *PagesAddPageRequest) (*PagesAddPageResponse, error)
	PagesRemovePage(context.Context, *PagesRemovePageRequest) (*PagesRemovePageResponse, error)
	PagesShowPage(context.Context, *PagesShowPageRequest) (*PagesShowPageResponse, error)
	PagesGetCurrentPage(context.Context, *PagesGetCurrentPageRequest) (*PagesGetCurrentPageResponse, error)
	mustEmbedUnimplementedLayoutServiceServer()
}

// UnimplementedLayoutServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLayoutServiceServer struct{}

func (UnimplementedLayoutServiceServer) FlexAddItem(context.Context, *FlexAddItemRequest) (*FlexAddItemResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FlexAddItem not implemented")
}
func (UnimplementedLayoutServiceServer) FlexRemoveItem(context.Context, *FlexRemoveItemRequest) (*FlexRemoveItemResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FlexRemoveItem not implemented")
}
func (UnimplementedLayoutServiceServer) FlexSetDirection(context.Context, *FlexSetDirectionRequest) (*FlexSetDirectionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FlexSetDirection not implemented")
}
func (UnimplementedLayoutServiceServer) GridAddItem(context.Context, *GridAddItemRequest) (*GridAddItemResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GridAddItem not implemented")
}
func (UnimplementedLayoutServiceServer) GridRemoveItem(context.Context, *GridRemoveItemRequest) (*GridRemoveItemResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GridRemoveItem not implemented")
}
func (UnimplementedLayoutServiceServer) GridSetRows(context.Context, *GridSetRowsRequest) (*GridSetRowsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GridSetRows not implemented")
}
func (UnimplementedLayoutServiceServer) GridSetColumns(context.Context, *GridSetColumnsRequest) (*GridSetColumnsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GridSetColumns not implemented")
}
func (UnimplementedLayoutServiceServer) PagesAddPage(context.Context, *PagesAddPageRequest) (*PagesAddPageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PagesAddPage not implemented")
}
func (UnimplementedLayoutServiceServer) PagesRemovePage(context.Context, *PagesRemovePageRequest) (*PagesRemovePageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PagesRemovePage not implemented")
}
func (UnimplementedLayoutServiceServer) PagesShowPage(context.Context, *PagesShowPageRequest) (*PagesShowPageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PagesShowPage not implemented")
}
func (UnimplementedLayoutServiceServer) PagesGetCurrentPage(context.Context, *PagesGetCurrentPageRequest) (*PagesGetCurrentPageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PagesGetCurrentPage not implemented")
}
func (UnimplementedLayoutServiceServer) mustEmbedUnimplementedLayoutServiceServer() {}
func (UnimplementedLayoutServiceServer) testEmbeddedByValue()                       {}

// UnsafeLayoutServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LayoutServiceServer will
// result in compilation errors.
type UnsafeLayoutServiceServer interface {
	mustEmbedUnimplementedLayoutServiceServer()
}

func RegisterLayoutServiceServer(s grpc.ServiceRegistrar, srv LayoutServiceServer) {
	// If the following call panics, it indicates UnimplementedLayoutServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LayoutService_ServiceDesc, srv)
}

func _LayoutService_FlexAddItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FlexAddItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LayoutServiceServer).FlexAddItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LayoutService_FlexAddItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LayoutServiceServer).FlexAddItem(ctx, req.(*FlexAddItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LayoutService_FlexRemoveItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FlexRemoveItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LayoutServiceServer).FlexRemoveItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LayoutService_FlexRemoveItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LayoutServiceServer).FlexRemoveItem(ctx, req.(*FlexRemoveItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LayoutService_FlexSetDirection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FlexSetDirectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LayoutServiceServer).FlexSetDirection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LayoutService_FlexSetDirection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LayoutServiceServer).FlexSetDirection(ctx, req.(*FlexSetDirectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LayoutService_GridAddItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GridAddItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LayoutServiceServer).GridAddItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LayoutService_GridAddItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LayoutServiceServer).GridAddItem(ctx, req.(*GridAddItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LayoutService_GridRemoveItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GridRemoveItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LayoutServiceServer).GridRemoveItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LayoutService_GridRemoveItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LayoutServiceServer).GridRemoveItem(ctx, req.(*GridRemoveItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LayoutService_GridSetRows_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GridSetRowsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LayoutServiceServer).GridSetRows(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LayoutService_GridSetRows_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LayoutServiceServer).GridSetRows(ctx, req.(*GridSetRowsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LayoutService_GridSetColumns_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GridSetColumnsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LayoutServiceServer).GridSetColumns(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LayoutService_GridSetColumns_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LayoutServiceServer).GridSetColumns(ctx, req.(*GridSetColumnsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LayoutService_PagesAddPage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PagesAddPageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LayoutServiceServer).PagesAddPage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LayoutService_PagesAddPage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LayoutServiceServer).PagesAddPage(ctx, req.(*PagesAddPageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LayoutService_PagesRemovePage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PagesRemovePageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LayoutServiceServer).PagesRemovePage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LayoutService_PagesRemovePage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LayoutServiceServer).PagesRemovePage(ctx, req.(*PagesRemovePageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LayoutService_PagesShowPage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PagesShowPageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LayoutServiceServer).PagesShowPage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LayoutService_PagesShowPage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LayoutServiceServer).PagesShowPage(ctx, req.(*PagesShowPageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LayoutService_PagesGetCurrentPage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PagesGetCurrentPageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LayoutServiceServer).PagesGetCurrentPage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LayoutService_PagesGetCurrentPage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LayoutServiceServer).PagesGetCurrentPage(ctx, req.(*PagesGetCurrentPageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LayoutService_ServiceDesc is the grpc.ServiceDesc for LayoutService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LayoutService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "industries.loosh.yutani.v1.LayoutService",
	HandlerType: (*LayoutServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FlexAddItem",
			Handler:    _LayoutService_FlexAddItem_Handler,
		},
		{
			MethodName: "FlexRemoveItem",
			Handler:    _LayoutService_FlexRemoveItem_Handler,
		},
		{
			MethodName: "FlexSetDirection",
			Handler:    _LayoutService_FlexSetDirection_Handler,
		},
		{
			MethodName: "GridAddItem",
			Handler:    _LayoutService_GridAddItem_Handler,
		},
		{
			MethodName: "GridRemoveItem",
			Handler:    _LayoutService_GridRemoveItem_Handler,
		},
		{
			MethodName: "GridSetRows",
			Handler:    _LayoutService_GridSetRows_Handler,
		},
		{
			MethodName: "GridSetColumns",
			Handler:    _LayoutService_GridSetColumns_Handler,
		},
		{
			MethodName: "PagesAddPage",
			Handler:    _LayoutService_PagesAddPage_Handler,
		},
		{
			MethodName: "PagesRemovePage",
			Handler:    _LayoutService_PagesRemovePage_Handler,
		},
		{
			MethodName: "PagesShowPage",
			Handler:    _LayoutService_PagesShowPage_Handler,
		},
		{
			MethodName: "PagesGetCurrentPage",
			Handler:    _LayoutService_PagesGetCurrentPage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "industries/loosh/yutani/v1/layout.proto",
}
