// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: industries/loosh/yutani/v1/list.proto

package yutani

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListAddItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     *SessionId             `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	WidgetId      *WidgetId              `protobuf:"bytes,2,opt,name=widget_id,json=widgetId,proto3" json:"widget_id,omitempty"`
	MainText      string                 `protobuf:"bytes,3,opt,name=main_text,json=mainText,proto3" json:"main_text,omitempty"`
	SecondaryText string                 `protobuf:"bytes,4,opt,name=secondary_text,json=secondaryText,proto3" json:"secondary_text,omitempty"`
	Shortcut      *string                `protobuf:"bytes,5,opt,name=shortcut,proto3,oneof" json:"shortcut,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAddItemRequest) Reset() {
	*x = ListAddItemRequest{}
	mi := &file_industries_loosh_yutani_v1_list_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAddItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAddItemRequest) ProtoMessage() {}

func (x *ListAddItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_industries_loosh_yutani_v1_list_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAddItemRequest.ProtoReflect.Descriptor instead.
func (*ListAddItemRequest) Descriptor() ([]byte, []int) {
	return file_industries_loosh_yutani_v1_list_proto_rawDescGZIP(), []int{0}
}

func (x *ListAddItemRequest) GetSessionId() *SessionId {
	if x != nil {
		return x.SessionId
	}
	return nil
}

func (x *ListAddItemRequest) GetWidgetId() *WidgetId {
	if x != nil {
		return x.WidgetId
	}
	return nil
}

func (x *ListAddItemRequest) GetMainText() string {
	if x != nil {
		return x.MainText
	}
	return ""
}

func (x *ListAddItemRequest) GetSecondaryText() string {
	if x != nil {
		return x.SecondaryText
	}
	return ""
}

func (x *ListAddItemRequest) GetShortcut() string {
	if x != nil && x.Shortcut != nil {
		return *x.Shortcut
	}
	return ""
}

type ListAddItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Index         int32                  `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"` // Index of the added item
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAddItemResponse) Reset() {
	*x = ListAddItemResponse{}
	mi := &file_industries_loosh_yutani_v1_list_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAddItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAddItemResponse) ProtoMessage() {}

func (x *ListAddItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_industries_loosh_yutani_v1_list_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAddItemResponse.ProtoReflect.Descriptor instead.
func (*ListAddItemResponse) Descriptor() ([]byte, []int) {
	return file_industries_loosh_yutani_v1_list_proto_rawDescGZIP(), []int{1}
}

func (x *ListAddItemResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ListAddItemResponse) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

type ListRemoveItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     *SessionId             `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	WidgetId      *WidgetId              `protobuf:"bytes,2,opt,name=widget_id,json=widgetId,proto3" json:"widget_id,omitempty"`
	Index         int32                  `protobuf:"varint,3,opt,name=index,proto3" json:"index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRemoveItemRequest) Reset() {
	*x = ListRemoveItemRequest{}
	mi := &file_industries_loosh_yutani_v1_list_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRemoveItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRemoveItemRequest) ProtoMessage() {}

func (x *ListRemoveItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_industries_loosh_yutani_v1_list_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRemoveItemRequest.ProtoReflect.Descriptor instead.
func (*ListRemoveItemRequest) Descriptor() ([]byte, []int) {
	return file_industries_loosh_yutani_v1_list_proto_rawDescGZIP(), []int{2}
}

func (x *ListRemoveItemRequest) GetSessionId() *SessionId {
	if x != nil {
		return x.SessionId
	}
	return nil
}

func (x *ListRemoveItemRequest) GetWidgetId() *WidgetId {
	if x != nil {
		return x.WidgetId
	}
	return nil
}

func (x *ListRemoveItemRequest) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

type ListRemoveItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRemoveItemResponse) Reset() {
	*x = ListRemoveItemResponse{}
	mi := &file_industries_loosh_yutani_v1_list_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRemoveItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRemoveItemResponse) ProtoMessage() {}

func (x *ListRemoveItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_industries_loosh_yutani_v1_list_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRemoveItemResponse.ProtoReflect.Descriptor instead.
func (*ListRemoveItemResponse) Descriptor() ([]byte, []int) {
	return file_industries_loosh_yutani_v1_list_proto_rawDescGZIP(), []int{3}
}

func (x *ListRemoveItemResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ListClearRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     *SessionId             `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	WidgetId      *WidgetId              `protobuf:"bytes,2,opt,name=widget_id,json=widgetId,proto3" json:"widget_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListClearRequest) Reset() {
	*x = ListClearRequest{}
	mi := &file_industries_loosh_yutani_v1_list_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListClearRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListClearRequest) ProtoMessage() {}

func (x *ListClearRequest) ProtoReflect() protoreflect.Message {
	mi := &file_industries_loosh_yutani_v1_list_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListClearRequest.ProtoReflect.Descriptor instead.
func (*ListClearRequest) Descriptor() ([]byte, []int) {
	return file_industries_loosh_yutani_v1_list_proto_rawDescGZIP(), []int{4}
}

func (x *ListClearRequest) GetSessionId() *SessionId {
	if x != nil {
		return x.SessionId
	}
	return nil
}

func (x *ListClearRequest) GetWidgetId() *WidgetId {
	if x != nil {
		return x.WidgetId
	}
	return nil
}

type ListClearResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListClearResponse) Reset() {
	*x = ListClearResponse{}
	mi := &file_industries_loosh_yutani_v1_list_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListClearResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListClearResponse) ProtoMessage() {}

func (x *ListClearResponse) ProtoReflect() protoreflect.Message {
	mi := &file_industries_loosh_yutani_v1_list_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListClearResponse.ProtoReflect.Descriptor instead.
func (*ListClearResponse) Descriptor() ([]byte, []int) {
	return file_industries_loosh_yutani_v1_list_proto_rawDescGZIP(), []int{5}
}

func (x *ListClearResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ListGetItemCountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     *SessionId             `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	WidgetId      *WidgetId              `protobuf:"bytes,2,opt,name=widget_id,json=widgetId,proto3" json:"widget_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGetItemCountRequest) Reset() {
	*x = ListGetItemCountRequest{}
	mi := &file_industries_loosh_yutani_v1_list_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGetItemCountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGetItemCountRequest) ProtoMessage() {}

func (x *ListGetItemCountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_industries_loosh_yutani_v1_list_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGetItemCountRequest.ProtoReflect.Descriptor instead.
func (*ListGetItemCountRequest) Descriptor() ([]byte, []int) {
	return file_industries_loosh_yutani_v1_list_proto_rawDescGZIP(), []int{6}
}

func (x *ListGetItemCountRequest) GetSessionId() *SessionId {
	if x != nil {
		return x.SessionId
	}
	return nil
}

func (x *ListGetItemCountRequest) GetWidgetId() *WidgetId {
	if x != nil {
		return x.WidgetId
	}
	return nil
}

type ListGetItemCountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int32                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGetItemCountResponse) Reset() {
	*x = ListGetItemCountResponse{}
	mi := &file_industries_loosh_yutani_v1_list_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGetItemCountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGetItemCountResponse) ProtoMessage() {}

func (x *ListGetItemCountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_industries_loosh_yutani_v1_list_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGetItemCountResponse.ProtoReflect.Descriptor instead.
func (*ListGetItemCountResponse) Descriptor() ([]byte, []int) {
	return file_industries_loosh_yutani_v1_list_proto_rawDescGZIP(), []int{7}
}

func (x *ListGetItemCountResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type ListGetSelectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     *SessionId             `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	WidgetId      *WidgetId              `protobuf:"bytes,2,opt,name=widget_id,json=widgetId,proto3" json:"widget_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGetSelectionRequest) Reset() {
	*x = ListGetSelectionRequest{}
	mi := &file_industries_loosh_yutani_v1_list_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGetSelectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGetSelectionRequest) ProtoMessage() {}

func (x *ListGetSelectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_industries_loosh_yutani_v1_list_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGetSelectionRequest.ProtoReflect.Descriptor instead.
func (*ListGetSelectionRequest) Descriptor() ([]byte, []int) {
	return file_industries_loosh_yutani_v1_list_proto_rawDescGZIP(), []int{8}
}

func (x *ListGetSelectionRequest) GetSessionId() *SessionId {
	if x != nil {
		return x.SessionId
	}
	return nil
}

func (x *ListGetSelectionRequest) GetWidgetId() *WidgetId {
	if x != nil {
		return x.WidgetId
	}
	return nil
}

type ListGetSelectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         int32                  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"` // -1 if no selection
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGetSelectionResponse) Reset() {
	*x = ListGetSelectionResponse{}
	mi := &file_industries_loosh_yutani_v1_list_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGetSelectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGetSelectionResponse) ProtoMessage() {}

func (x *ListGetSelectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_industries_loosh_yutani_v1_list_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGetSelectionResponse.ProtoReflect.Descriptor instead.
func (*ListGetSelectionResponse) Descriptor() ([]byte, []int) {
	return file_industries_loosh_yutani_v1_list_proto_rawDescGZIP(), []int{9}
}

func (x *ListGetSelectionResponse) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

type ListSetSelectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     *SessionId             `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	WidgetId      *WidgetId              `protobuf:"bytes,2,opt,name=widget_id,json=widgetId,proto3" json:"widget_id,omitempty"`
	Index         int32                  `protobuf:"varint,3,opt,name=index,proto3" json:"index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSetSelectionRequest) Reset() {
	*x = ListSetSelectionRequest{}
	mi := &file_industries_loosh_yutani_v1_list_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSetSelectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSetSelectionRequest) ProtoMessage() {}

func (x *ListSetSelectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_industries_loosh_yutani_v1_list_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSetSelectionRequest.ProtoReflect.Descriptor instead.
func (*ListSetSelectionRequest) Descriptor() ([]byte, []int) {
	return file_industries_loosh_yutani_v1_list_proto_rawDescGZIP(), []int{10}
}

func (x *ListSetSelectionRequest) GetSessionId() *SessionId {
	if x != nil {
		return x.SessionId
	}
	return nil
}

func (x *ListSetSelectionRequest) GetWidgetId() *WidgetId {
	if x != nil {
		return x.WidgetId
	}
	return nil
}

func (x *ListSetSelectionRequest) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

type ListSetSelectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSetSelectionResponse) Reset() {
	*x = ListSetSelectionResponse{}
	mi := &file_industries_loosh_yutani_v1_list_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSetSelectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSetSelectionResponse) ProtoMessage() {}

func (x *ListSetSelectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_industries_loosh_yutani_v1_list_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSetSelectionResponse.ProtoReflect.Descriptor instead.
func (*ListSetSelectionResponse) Descriptor() ([]byte, []int) {
	return file_industries_loosh_yutani_v1_list_proto_rawDescGZIP(), []int{11}
}

func (x *ListSetSelectionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ListGetItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     *SessionId             `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	WidgetId      *WidgetId              `protobuf:"bytes,2,opt,name=widget_id,json=widgetId,proto3" json:"widget_id,omitempty"`
	Index         int32                  `protobuf:"varint,3,opt,name=index,proto3" json:"index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGetItemRequest) Reset() {
	*x = ListGetItemRequest{}
	mi := &file_industries_loosh_yutani_v1_list_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGetItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGetItemRequest) ProtoMessage() {}

func (x *ListGetItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_industries_loosh_yutani_v1_list_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGetItemRequest.ProtoReflect.Descriptor instead.
func (*ListGetItemRequest) Descriptor() ([]byte, []int) {
	return file_industries_loosh_yutani_v1_list_proto_rawDescGZIP(), []int{12}
}

func (x *ListGetItemRequest) GetSessionId() *SessionId {
	if x != nil {
		return x.SessionId
	}
	return nil
}

func (x *ListGetItemRequest) GetWidgetId() *WidgetId {
	if x != nil {
		return x.WidgetId
	}
	return nil
}

func (x *ListGetItemRequest) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

type ListGetItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MainText      string                 `protobuf:"bytes,1,opt,name=main_text,json=mainText,proto3" json:"main_text,omitempty"`
	SecondaryText string                 `protobuf:"bytes,2,opt,name=secondary_text,json=secondaryText,proto3" json:"secondary_text,omitempty"`
	Shortcut      string                 `protobuf:"bytes,3,opt,name=shortcut,proto3" json:"shortcut,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGetItemResponse) Reset() {
	*x = ListGetItemResponse{}
	mi := &file_industries_loosh_yutani_v1_list_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGetItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGetItemResponse) ProtoMessage() {}

func (x *ListGetItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_industries_loosh_yutani_v1_list_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGetItemResponse.ProtoReflect.Descriptor instead.
func (*ListGetItemResponse) Descriptor() ([]byte, []int) {
	return file_industries_loosh_yutani_v1_list_proto_rawDescGZIP(), []int{13}
}

func (x *ListGetItemResponse) GetMainText() string {
	if x != nil {
		return x.MainText
	}
	return ""
}

func (x *ListGetItemResponse) GetSecondaryText() string {
	if x != nil {
		return x.SecondaryText
	}
	return ""
}

func (x *ListGetItemResponse) GetShortcut() string {
	if x != nil {
		return x.Shortcut
	}
	return ""
}

var File_industries_loosh_yutani_v1_list_proto protoreflect.FileDescriptor

const file_industries_loosh_yutani_v1_list_proto_rawDesc = "" +
	"\n" +
	"%industries/loosh/yutani/v1/list.proto\x12\x1aindustries.loosh.yutani.v1\x1a&industries/loosh/yutani/v1/types.proto\"\x8f\x02\n" +
	"\x12ListAddItemRequest\x12D\n" +
	"\n" +
	"session_id\x18\x01 \x01(\v2%.industries.loosh.yutani.v1.SessionIdR\tsessionId\x12A\n" +
	"\twidget_id\x18\x02 \x01(\v2$.industries.loosh.yutani.v1.WidgetIdR\bwidgetId\x12\x1b\n" +
	"\tmain_text\x18\x03 \x01(\tR\bmainText\x12%\n" +
	"\x0esecondary_text\x18\x04 \x01(\tR\rsecondaryText\x12\x1f\n" +
	"\bshortcut\x18\x05 \x01(\tH\x00R\bshortcut\x88\x01\x01B\v\n" +
	"\t_shortcut\"E\n" +
	"\x13ListAddItemResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05index\x18\x02 \x01(\x05R\x05index\"\xb6\x01\n" +
	"\x15ListRemoveItemRequest\x12D\n" +
	"\n" +
	"session_id\x18\x01 \x01(\v2%.industries.loosh.yutani.v1.SessionIdR\tsessionId\x12A\n" +
	"\twidget_id\x18\x02 \x01(\v2$.industries.loosh.yutani.v1.WidgetIdR\bwidgetId\x12\x14\n" +
	"\x05index\x18\x03 \x01(\x05R\x05index\"2\n" +
	"\x16ListRemoveItemResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x9b\x01\n" +
	"\x10ListClearRequest\x12D\n" +
	"\n" +
	"session_id\x18\x01 \x01(\v2%.industries.loosh.yutani.v1.SessionIdR\tsessionId\x12A\n" +
	"\twidget_id\x18\x02 \x01(\v2$.industries.loosh.yutani.v1.WidgetIdR\bwidgetId\"-\n" +
	"\x11ListClearResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xa2\x01\n" +
	"\x17ListGetItemCountRequest\x12D\n" +
	"\n" +
	"session_id\x18\x01 \x01(\v2%.industries.loosh.yutani.v1.SessionIdR\tsessionId\x12A\n" +
	"\twidget_id\x18\x02 \x01(\v2$.industries.loosh.yutani.v1.WidgetIdR\bwidgetId\"0\n" +
	"\x18ListGetItemCountResponse\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x05R\x05count\"\xa2\x01\n" +
	"\x17ListGetSelectionRequest\x12D\n" +
	"\n" +
	"session_id\x18\x01 \x01(\v2%.industries.loosh.yutani.v1.SessionIdR\tsessionId\x12A\n" +
	"\twidget_id\x18\x02 \x01(\v2$.industries.loosh.yutani.v1.WidgetIdR\bwidgetId\"0\n" +
	"\x18ListGetSelectionResponse\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x05R\x05index\"\xb8\x01\n" +
	"\x17ListSetSelectionRequest\x12D\n" +
	"\n" +
	"session_id\x18\x01 \x01(\v2%.industries.loosh.yutani.v1.SessionIdR\tsessionId\x12A\n" +
	"\twidget_id\x18\x02 \x01(\v2$.industries.loosh.yutani.v1.WidgetIdR\bwidgetId\x12\x14\n" +
	"\x05index\x18\x03 \x01(\x05R\x05index\"4\n" +
	"\x18ListSetSelectionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xb3\x01\n" +
	"\x12ListGetItemRequest\x12D\n" +
	"\n" +
	"session_id\x18\x01 \x01(\v2%.industries.loosh.yutani.v1.SessionIdR\tsessionId\x12A\n" +
	"\twidget_id\x18\x02 \x01(\v2$.industries.loosh.yutani.v1.WidgetIdR\bwidgetId\x12\x14\n" +
	"\x05index\x18\x03 \x01(\x05R\x05index\"u\n" +
	"\x13ListGetItemResponse\x12\x1b\n" +
	"\tmain_text\x18\x01 \x01(\tR\bmainText\x12%\n" +
	"\x0esecondary_text\x18\x02 \x01(\tR\rsecondaryText\x12\x1a\n" +
	"\bshortcut\x18\x03 \x01(\tR\bshortcut2\xb1\x06\n" +
	"\vListService\x12j\n" +
	"\aAddItem\x12..industries.loosh.yutani.v1.ListAddItemRequest\x1a/.industries.loosh.yutani.v1.ListAddItemResponse\x12s\n" +
	"\n" +
	"RemoveItem\x121.industries.loosh.yutani.v1.ListRemoveItemRequest\x1a2.industries.loosh.yutani.v1.ListRemoveItemResponse\x12d\n" +
	"\x05Clear\x12,.industries.loosh.yutani.v1.ListClearRequest\x1a-.industries.loosh.yutani.v1.ListClearResponse\x12y\n" +
	"\fGetItemCount\x123.industries.loosh.yutani.v1.ListGetItemCountRequest\x1a4.industries.loosh.yutani.v1.ListGetItemCountResponse\x12y\n" +
	"\fGetSelection\x123.industries.loosh.yutani.v1.ListGetSelectionRequest\x1a4.industries.loosh.yutani.v1.ListGetSelectionResponse\x12y\n" +
	"\fSetSelection\x123.industries.loosh.yutani.v1.ListSetSelectionRequest\x1a4.industries.loosh.yutani.v1.ListSetSelectionResponse\x12j\n" +
	"\aGetItem\x12..industries.loosh.yutani.v1.ListGetItemRequest\x1a/.industries.loosh.yutani.v1.ListGetItemResponseB*Z(github.com/chazu/yutani/pkg/proto/yutanib\x06proto3"

var (
	file_industries_loosh_yutani_v1_list_proto_rawDescOnce sync.Once
	file_industries_loosh_yutani_v1_list_proto_rawDescData []byte
)

func file_industries_loosh_yutani_v1_list_proto_rawDescGZIP() []byte {
	file_industries_loosh_yutani_v1_list_proto_rawDescOnce.Do(func() {
		file_industries_loosh_yutani_v1_list_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_industries_loosh_yutani_v1_list_proto_rawDesc), len(file_industries_loosh_yutani_v1_list_proto_rawDesc)))
	})
	return file_industries_loosh_yutani_v1_list_proto_rawDescData
}

var file_industries_loosh_yutani_v1_list_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_industries_loosh_yutani_v1_list_proto_goTypes = []any{
	(*ListAddItemRequest)(nil),       // 0: industries.loosh.yutani.v1.ListAddItemRequest
	(*ListAddItemResponse)(nil),      // 1: industries.loosh.yutani.v1.ListAddItemResponse
	(*ListRemoveItemRequest)(nil),    // 2: industries.loosh.yutani.v1.ListRemoveItemRequest
	(*ListRemoveItemResponse)(nil),   // 3: industries.loosh.yutani.v1.ListRemoveItemResponse
	(*ListClearRequest)(nil),         // 4: industries.loosh.yutani.v1.ListClearRequest
	(*ListClearResponse)(nil),        // 5: industries.loosh.yutani.v1.ListClearResponse
	(*ListGetItemCountRequest)(nil),  // 6: industries.loosh.yutani.v1.ListGetItemCountRequest
	(*ListGetItemCountResponse)(nil), // 7: industries.loosh.yutani.v1.ListGetItemCountResponse
	(*ListGetSelectionRequest)(nil),  // 8: industries.loosh.yutani.v1.ListGetSelectionRequest
	(*ListGetSelectionResponse)(nil), // 9: industries.loosh.yutani.v1.ListGetSelectionResponse
	(*ListSetSelectionRequest)(nil),  // 10: industries.loosh.yutani.v1.ListSetSelectionRequest
	(*ListSetSelectionResponse)(nil), // 11: industries.loosh.yutani.v1.ListSetSelectionResponse
	(*ListGetItemRequest)(nil),       // 12: industries.loosh.yutani.v1.ListGetItemRequest
	(*ListGetItemResponse)(nil),      // 13: industries.loosh.yutani.v1.ListGetItemResponse
	(*SessionId)(nil),                // 14: industries.loosh.yutani.v1.SessionId
	(*WidgetId)(nil),                 // 15: industries.loosh.yutani.v1.WidgetId
}
var file_industries_loosh_yutani_v1_list_proto_depIdxs = []int32{
	14, // 0: industries.loosh.yutani.v1.ListAddItemRequest.session_id:type_name -> industries.loosh.yutani.v1.SessionId
	15, // 1: industries.loosh.yutani.v1.ListAddItemRequest.widget_id:type_name -> industries.loosh.yutani.v1.WidgetId
	14, // 2: industries.loosh.yutani.v1.ListRemoveItemRequest.session_id:type_name -> industries.loosh.yutani.v1.SessionId
	15, // 3: industries.loosh.yutani.v1.ListRemoveItemRequest.widget_id:type_name -> industries.loosh.yutani.v1.WidgetId
	14, // 4: industries.loosh.yutani.v1.ListClearRequest.session_id:type_name -> industries.loosh.yutani.v1.SessionId
	15, // 5: industries.loosh.yutani.v1.ListClearRequest.widget_id:type_name -> industries.loosh.yutani.v1.WidgetId
	14, // 6: industries.loosh.yutani.v1.ListGetItemCountRequest.session_id:type_name -> industries.loosh.yutani.v1.SessionId
	15, // 7: industries.loosh.yutani.v1.ListGetItemCountRequest.widget_id:type_name -> industries.loosh.yutani.v1.WidgetId
	14, // 8: industries.loosh.yutani.v1.ListGetSelectionRequest.session_id:type_name -> industries.loosh.yutani.v1.SessionId
	15, // 9: industries.loosh.yutani.v1.ListGetSelectionRequest.widget_id:type_name -> industries.loosh.yutani.v1.WidgetId
	14, // 10: industries.loosh.yutani.v1.ListSetSelectionRequest.session_id:type_name -> industries.loosh.yutani.v1.SessionId
	15, // 11: industries.loosh.yutani.v1.ListSetSelectionRequest.widget_id:type_name -> industries.loosh.yutani.v1.WidgetId
	14, // 12: industries.loosh.yutani.v1.ListGetItemRequest.session_id:type_name -> industries.loosh.yutani.v1.SessionId
	15, // 13: industries.loosh.yutani.v1.ListGetItemRequest.widget_id:type_name -> industries.loosh.yutani.v1.WidgetId
	0,  // 14: industries.loosh.yutani.v1.ListService.AddItem:input_type -> industries.loosh.yutani.v1.ListAddItemRequest
	2,  // 15: industries.loosh.yutani.v1.ListService.RemoveItem:input_type -> industries.loosh.yutani.v1.ListRemoveItemRequest
	4,  // 16: industries.loosh.yutani.v1.ListService.Clear:input_type -> industries.loosh.yutani.v1.ListClearRequest
	6,  // 17: industries.loosh.yutani.v1.ListService.GetItemCount:input_type -> industries.loosh.yutani.v1.ListGetItemCountRequest
	8,  // 18: industries.loosh.yutani.v1.ListService.GetSelection:input_type -> industries.loosh.yutani.v1.ListGetSelectionRequest
	10, // 19: industries.loosh.yutani.v1.ListService.SetSelection:input_type -> industries.loosh.yutani.v1.ListSetSelectionRequest
	12, // 20: industries.loosh.yutani.v1.ListService.GetItem:input_type -> industries.loosh.yutani.v1.ListGetItemRequest
	1,  // 21: industries.loosh.yutani.v1.ListService.AddItem:output_type -> industries.loosh.yutani.v1.ListAddItemResponse
	3,  // 22: industries.loosh.yutani.v1.ListService.RemoveItem:output_type -> industries.loosh.yutani.v1.ListRemoveItemResponse
	5,  // 23: industries.loosh.yutani.v1.ListService.Clear:output_type -> industries.loosh.yutani.v1.ListClearResponse
	7,  // 24: industries.loosh.yutani.v1.ListService.GetItemCount:output_type -> industries.loosh.yutani.v1.ListGetItemCountResponse
	9,  // 25: industries.loosh.yutani.v1.ListService.GetSelection:output_type -> industries.loosh.yutani.v1.ListGetSelectionResponse
	11, // 26: industries.loosh.yutani.v1.ListService.SetSelection:output_type -> industries.loosh.yutani.v1.ListSetSelectionResponse
	13, // 27: industries.loosh.yutani.v1.ListService.GetItem:output_type -> industries.loosh.yutani.v1.ListGetItemResponse
	21, // [21:28] is the sub-list for method output_type
	14, // [14:21] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_industries_loosh_yutani_v1_list_proto_init() }
func file_industries_loosh_yutani_v1_list_proto_init() {
	if File_industries_loosh_yutani_v1_list_proto != nil {
		return
	}
	file_industries_loosh_yutani_v1_types_proto_init()
	file_industries_loosh_yutani_v1_list_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_industries_loosh_yutani_v1_list_proto_rawDesc), len(file_industries_loosh_yutani_v1_list_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_industries_loosh_yutani_v1_list_proto_goTypes,
		DependencyIndexes: file_industries_loosh_yutani_v1_list_proto_depIdxs,
		MessageInfos:      file_industries_loosh_yutani_v1_list_proto_msgTypes,
	}.Build()
	File_industries_loosh_yutani_v1_list_proto = out.File
	file_industries_loosh_yutani_v1_list_proto_goTypes = nil
	file_industries_loosh_yutani_v1_list_proto_depIdxs = nil
}
