// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v5.29.3
// source: industries/loosh/yutani/v1/menu.proto

package yutani

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MenuService_AddMenu_FullMethodName        = "/industries.loosh.yutani.v1.MenuService/AddMenu"
	MenuService_AddMenuItem_FullMethodName    = "/industries.loosh.yutani.v1.MenuService/AddMenuItem"
	MenuService_RemoveMenuItem_FullMethodName = "/industries.loosh.yutani.v1.MenuService/RemoveMenuItem"
)

// MenuServiceClient is the client API for MenuService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MenuService manages menu bar, menu, and menu item relationships
type MenuServiceClient interface {
	// Add a menu to a menu bar
	AddMenu(ctx context.Context, in *MenuAddMenuRequest, opts ...grpc.CallOption) (*MenuAddMenuResponse, error)
	// Add a menu item to a menu
	AddMenuItem(ctx context.Context, in *MenuAddMenuItemRequest, opts ...grpc.CallOption) (*MenuAddMenuItemResponse, error)
	// Remove a menu item from a menu
	RemoveMenuItem(ctx context.Context, in *MenuRemoveMenuItemRequest, opts ...grpc.CallOption) (*MenuRemoveMenuItemResponse, error)
}

type menuServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMenuServiceClient(cc grpc.ClientConnInterface) MenuServiceClient {
	return &menuServiceClient{cc}
}

func (c *menuServiceClient) AddMenu(ctx context.Context, in *MenuAddMenuRequest, opts ...grpc.CallOption) (*MenuAddMenuResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MenuAddMenuResponse)
	err := c.cc.Invoke(ctx, MenuService_AddMenu_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *menuServiceClient) AddMenuItem(ctx context.Context, in *MenuAddMenuItemRequest, opts ...grpc.CallOption) (*MenuAddMenuItemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MenuAddMenuItemResponse)
	err := c.cc.Invoke(ctx, MenuService_AddMenuItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *menuServiceClient) RemoveMenuItem(ctx context.Context, in *MenuRemoveMenuItemRequest, opts ...grpc.CallOption) (*MenuRemoveMenuItemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MenuRemoveMenuItemResponse)
	err := c.cc.Invoke(ctx, MenuService_RemoveMenuItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MenuServiceServer is the server API for MenuService service.
// All implementations must embed UnimplementedMenuServiceServer
// for forward compatibility.
//
// MenuService manages menu bar, menu, and menu item relationships
type MenuServiceServer interface {
	// Add a menu to a menu bar
	AddMenu(context.Context, *MenuAddMenuRequest) (*MenuAddMenuResponse, error)
	// Add a menu item to a menu
	AddMenuItem(context.Context, *MenuAddMenuItemRequest) (*MenuAddMenuItemResponse, error)
	// Remove a menu item from a menu
	RemoveMenuItem(context.Context, *MenuRemoveMenuItemRequest) (*MenuRemoveMenuItemResponse, error)
	mustEmbedUnimplementedMenuServiceServer()
}

// UnimplementedMenuServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMenuServiceServer struct{}

func (UnimplementedMenuServiceServer) AddMenu(context.Context, *MenuAddMenuRequest) (*MenuAddMenuResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddMenu not implemented")
}
func (UnimplementedMenuServiceServer) AddMenuItem(context.Context, *MenuAddMenuItemRequest) (*MenuAddMenuItemResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddMenuItem not implemented")
}
func (UnimplementedMenuServiceServer) RemoveMenuItem(context.Context, *MenuRemoveMenuItemRequest) (*MenuRemoveMenuItemResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveMenuItem not implemented")
}
func (UnimplementedMenuServiceServer) mustEmbedUnimplementedMenuServiceServer() {}
func (UnimplementedMenuServiceServer) testEmbeddedByValue()                     {}

// UnsafeMenuServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MenuServiceServer will
// result in compilation errors.
type UnsafeMenuServiceServer interface {
	mustEmbedUnimplementedMenuServiceServer()
}

func RegisterMenuServiceServer(s grpc.ServiceRegistrar, srv MenuServiceServer) {
	// If the following call panics, it indicates UnimplementedMenuServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MenuService_ServiceDesc, srv)
}

func _MenuService_AddMenu_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MenuAddMenuRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MenuServiceServer).AddMenu(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MenuService_AddMenu_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MenuServiceServer).AddMenu(ctx, req.(*MenuAddMenuRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MenuService_AddMenuItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MenuAddMenuItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MenuServiceServer).AddMenuItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MenuService_AddMenuItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MenuServiceServer).AddMenuItem(ctx, req.(*MenuAddMenuItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MenuService_RemoveMenuItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MenuRemoveMenuItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MenuServiceServer).RemoveMenuItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MenuService_RemoveMenuItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MenuServiceServer).RemoveMenuItem(ctx, req.(*MenuRemoveMenuItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MenuService_ServiceDesc is the grpc.ServiceDesc for MenuService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MenuService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "industries.loosh.yutani.v1.MenuService",
	HandlerType: (*MenuServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddMenu",
			Handler:    _MenuService_AddMenu_Handler,
		},
		{
			MethodName: "AddMenuItem",
			Handler:    _MenuService_AddMenuItem_Handler,
		},
		{
			MethodName: "RemoveMenuItem",
			Handler:    _MenuService_RemoveMenuItem_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "industries/loosh/yutani/v1/menu.proto",
}
