// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: industries/loosh/yutani/v1/session.proto

package yutani

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateSessionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional client identifier
	ClientName string `protobuf:"bytes,1,opt,name=client_name,json=clientName,proto3" json:"client_name,omitempty"`
	// Optional session preferences
	Preferences   *SessionPreferences `protobuf:"bytes,2,opt,name=preferences,proto3" json:"preferences,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSessionRequest) Reset() {
	*x = CreateSessionRequest{}
	mi := &file_industries_loosh_yutani_v1_session_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionRequest) ProtoMessage() {}

func (x *CreateSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_industries_loosh_yutani_v1_session_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionRequest.ProtoReflect.Descriptor instead.
func (*CreateSessionRequest) Descriptor() ([]byte, []int) {
	return file_industries_loosh_yutani_v1_session_proto_rawDescGZIP(), []int{0}
}

func (x *CreateSessionRequest) GetClientName() string {
	if x != nil {
		return x.ClientName
	}
	return ""
}

func (x *CreateSessionRequest) GetPreferences() *SessionPreferences {
	if x != nil {
		return x.Preferences
	}
	return nil
}

type SessionPreferences struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Event filtering preferences (for Phase 2)
	ReceiveMouseEvents  bool `protobuf:"varint,1,opt,name=receive_mouse_events,json=receiveMouseEvents,proto3" json:"receive_mouse_events,omitempty"`
	ReceiveKeyEvents    bool `protobuf:"varint,2,opt,name=receive_key_events,json=receiveKeyEvents,proto3" json:"receive_key_events,omitempty"`
	ReceiveResizeEvents bool `protobuf:"varint,3,opt,name=receive_resize_events,json=receiveResizeEvents,proto3" json:"receive_resize_events,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *SessionPreferences) Reset() {
	*x = SessionPreferences{}
	mi := &file_industries_loosh_yutani_v1_session_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionPreferences) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionPreferences) ProtoMessage() {}

func (x *SessionPreferences) ProtoReflect() protoreflect.Message {
	mi := &file_industries_loosh_yutani_v1_session_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionPreferences.ProtoReflect.Descriptor instead.
func (*SessionPreferences) Descriptor() ([]byte, []int) {
	return file_industries_loosh_yutani_v1_session_proto_rawDescGZIP(), []int{1}
}

func (x *SessionPreferences) GetReceiveMouseEvents() bool {
	if x != nil {
		return x.ReceiveMouseEvents
	}
	return false
}

func (x *SessionPreferences) GetReceiveKeyEvents() bool {
	if x != nil {
		return x.ReceiveKeyEvents
	}
	return false
}

func (x *SessionPreferences) GetReceiveResizeEvents() bool {
	if x != nil {
		return x.ReceiveResizeEvents
	}
	return false
}

type CreateSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     *SessionId             `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ServerVersion string                 `protobuf:"bytes,2,opt,name=server_version,json=serverVersion,proto3" json:"server_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSessionResponse) Reset() {
	*x = CreateSessionResponse{}
	mi := &file_industries_loosh_yutani_v1_session_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionResponse) ProtoMessage() {}

func (x *CreateSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_industries_loosh_yutani_v1_session_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionResponse.ProtoReflect.Descriptor instead.
func (*CreateSessionResponse) Descriptor() ([]byte, []int) {
	return file_industries_loosh_yutani_v1_session_proto_rawDescGZIP(), []int{2}
}

func (x *CreateSessionResponse) GetSessionId() *SessionId {
	if x != nil {
		return x.SessionId
	}
	return nil
}

func (x *CreateSessionResponse) GetServerVersion() string {
	if x != nil {
		return x.ServerVersion
	}
	return ""
}

type DestroySessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     *SessionId             `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DestroySessionRequest) Reset() {
	*x = DestroySessionRequest{}
	mi := &file_industries_loosh_yutani_v1_session_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestroySessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroySessionRequest) ProtoMessage() {}

func (x *DestroySessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_industries_loosh_yutani_v1_session_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroySessionRequest.ProtoReflect.Descriptor instead.
func (*DestroySessionRequest) Descriptor() ([]byte, []int) {
	return file_industries_loosh_yutani_v1_session_proto_rawDescGZIP(), []int{3}
}

func (x *DestroySessionRequest) GetSessionId() *SessionId {
	if x != nil {
		return x.SessionId
	}
	return nil
}

type DestroySessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DestroySessionResponse) Reset() {
	*x = DestroySessionResponse{}
	mi := &file_industries_loosh_yutani_v1_session_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestroySessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroySessionResponse) ProtoMessage() {}

func (x *DestroySessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_industries_loosh_yutani_v1_session_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroySessionResponse.ProtoReflect.Descriptor instead.
func (*DestroySessionResponse) Descriptor() ([]byte, []int) {
	return file_industries_loosh_yutani_v1_session_proto_rawDescGZIP(), []int{4}
}

func (x *DestroySessionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ListSessionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsRequest) Reset() {
	*x = ListSessionsRequest{}
	mi := &file_industries_loosh_yutani_v1_session_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsRequest) ProtoMessage() {}

func (x *ListSessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_industries_loosh_yutani_v1_session_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsRequest.ProtoReflect.Descriptor instead.
func (*ListSessionsRequest) Descriptor() ([]byte, []int) {
	return file_industries_loosh_yutani_v1_session_proto_rawDescGZIP(), []int{5}
}

type ListSessionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sessions      []*SessionInfo         `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsResponse) Reset() {
	*x = ListSessionsResponse{}
	mi := &file_industries_loosh_yutani_v1_session_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsResponse) ProtoMessage() {}

func (x *ListSessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_industries_loosh_yutani_v1_session_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsResponse.ProtoReflect.Descriptor instead.
func (*ListSessionsResponse) Descriptor() ([]byte, []int) {
	return file_industries_loosh_yutani_v1_session_proto_rawDescGZIP(), []int{6}
}

func (x *ListSessionsResponse) GetSessions() []*SessionInfo {
	if x != nil {
		return x.Sessions
	}
	return nil
}

type SessionInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     *SessionId             `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ClientName    string                 `protobuf:"bytes,2,opt,name=client_name,json=clientName,proto3" json:"client_name,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // Unix timestamp in nanoseconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionInfo) Reset() {
	*x = SessionInfo{}
	mi := &file_industries_loosh_yutani_v1_session_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionInfo) ProtoMessage() {}

func (x *SessionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_industries_loosh_yutani_v1_session_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionInfo.ProtoReflect.Descriptor instead.
func (*SessionInfo) Descriptor() ([]byte, []int) {
	return file_industries_loosh_yutani_v1_session_proto_rawDescGZIP(), []int{7}
}

func (x *SessionInfo) GetSessionId() *SessionId {
	if x != nil {
		return x.SessionId
	}
	return nil
}

func (x *SessionInfo) GetClientName() string {
	if x != nil {
		return x.ClientName
	}
	return ""
}

func (x *SessionInfo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type GetServerInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServerInfoRequest) Reset() {
	*x = GetServerInfoRequest{}
	mi := &file_industries_loosh_yutani_v1_session_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServerInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServerInfoRequest) ProtoMessage() {}

func (x *GetServerInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_industries_loosh_yutani_v1_session_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServerInfoRequest.ProtoReflect.Descriptor instead.
func (*GetServerInfoRequest) Descriptor() ([]byte, []int) {
	return file_industries_loosh_yutani_v1_session_proto_rawDescGZIP(), []int{8}
}

type GetServerInfoResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Version        string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	ActiveSessions int32                  `protobuf:"varint,2,opt,name=active_sessions,json=activeSessions,proto3" json:"active_sessions,omitempty"`
	MaxSessions    int32                  `protobuf:"varint,3,opt,name=max_sessions,json=maxSessions,proto3" json:"max_sessions,omitempty"`
	ScreenSize     *Size                  `protobuf:"bytes,4,opt,name=screen_size,json=screenSize,proto3" json:"screen_size,omitempty"`
	Capabilities   *ServerCapabilities    `protobuf:"bytes,5,opt,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetServerInfoResponse) Reset() {
	*x = GetServerInfoResponse{}
	mi := &file_industries_loosh_yutani_v1_session_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServerInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServerInfoResponse) ProtoMessage() {}

func (x *GetServerInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_industries_loosh_yutani_v1_session_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServerInfoResponse.ProtoReflect.Descriptor instead.
func (*GetServerInfoResponse) Descriptor() ([]byte, []int) {
	return file_industries_loosh_yutani_v1_session_proto_rawDescGZIP(), []int{9}
}

func (x *GetServerInfoResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *GetServerInfoResponse) GetActiveSessions() int32 {
	if x != nil {
		return x.ActiveSessions
	}
	return 0
}

func (x *GetServerInfoResponse) GetMaxSessions() int32 {
	if x != nil {
		return x.MaxSessions
	}
	return 0
}

func (x *GetServerInfoResponse) GetScreenSize() *Size {
	if x != nil {
		return x.ScreenSize
	}
	return nil
}

func (x *GetServerInfoResponse) GetCapabilities() *ServerCapabilities {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type ServerCapabilities struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	MouseSupport     bool                   `protobuf:"varint,1,opt,name=mouse_support,json=mouseSupport,proto3" json:"mouse_support,omitempty"`
	PasteSupport     bool                   `protobuf:"varint,2,opt,name=paste_support,json=pasteSupport,proto3" json:"paste_support,omitempty"`
	TrueColor        bool                   `protobuf:"varint,3,opt,name=true_color,json=trueColor,proto3" json:"true_color,omitempty"`
	SupportedWidgets []string               `protobuf:"bytes,4,rep,name=supported_widgets,json=supportedWidgets,proto3" json:"supported_widgets,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ServerCapabilities) Reset() {
	*x = ServerCapabilities{}
	mi := &file_industries_loosh_yutani_v1_session_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerCapabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerCapabilities) ProtoMessage() {}

func (x *ServerCapabilities) ProtoReflect() protoreflect.Message {
	mi := &file_industries_loosh_yutani_v1_session_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerCapabilities.ProtoReflect.Descriptor instead.
func (*ServerCapabilities) Descriptor() ([]byte, []int) {
	return file_industries_loosh_yutani_v1_session_proto_rawDescGZIP(), []int{10}
}

func (x *ServerCapabilities) GetMouseSupport() bool {
	if x != nil {
		return x.MouseSupport
	}
	return false
}

func (x *ServerCapabilities) GetPasteSupport() bool {
	if x != nil {
		return x.PasteSupport
	}
	return false
}

func (x *ServerCapabilities) GetTrueColor() bool {
	if x != nil {
		return x.TrueColor
	}
	return false
}

func (x *ServerCapabilities) GetSupportedWidgets() []string {
	if x != nil {
		return x.SupportedWidgets
	}
	return nil
}

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_industries_loosh_yutani_v1_session_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_industries_loosh_yutani_v1_session_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_industries_loosh_yutani_v1_session_proto_rawDescGZIP(), []int{11}
}

func (x *PingRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type PingResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Timestamp       int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ServerTimestamp int64                  `protobuf:"varint,2,opt,name=server_timestamp,json=serverTimestamp,proto3" json:"server_timestamp,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_industries_loosh_yutani_v1_session_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_industries_loosh_yutani_v1_session_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_industries_loosh_yutani_v1_session_proto_rawDescGZIP(), []int{12}
}

func (x *PingResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *PingResponse) GetServerTimestamp() int64 {
	if x != nil {
		return x.ServerTimestamp
	}
	return 0
}

var File_industries_loosh_yutani_v1_session_proto protoreflect.FileDescriptor

const file_industries_loosh_yutani_v1_session_proto_rawDesc = "" +
	"\n" +
	"(industries/loosh/yutani/v1/session.proto\x12\x1aindustries.loosh.yutani.v1\x1a&industries/loosh/yutani/v1/types.proto\"\x89\x01\n" +
	"\x14CreateSessionRequest\x12\x1f\n" +
	"\vclient_name\x18\x01 \x01(\tR\n" +
	"clientName\x12P\n" +
	"\vpreferences\x18\x02 \x01(\v2..industries.loosh.yutani.v1.SessionPreferencesR\vpreferences\"\xa8\x01\n" +
	"\x12SessionPreferences\x120\n" +
	"\x14receive_mouse_events\x18\x01 \x01(\bR\x12receiveMouseEvents\x12,\n" +
	"\x12receive_key_events\x18\x02 \x01(\bR\x10receiveKeyEvents\x122\n" +
	"\x15receive_resize_events\x18\x03 \x01(\bR\x13receiveResizeEvents\"\x84\x01\n" +
	"\x15CreateSessionResponse\x12D\n" +
	"\n" +
	"session_id\x18\x01 \x01(\v2%.industries.loosh.yutani.v1.SessionIdR\tsessionId\x12%\n" +
	"\x0eserver_version\x18\x02 \x01(\tR\rserverVersion\"]\n" +
	"\x15DestroySessionRequest\x12D\n" +
	"\n" +
	"session_id\x18\x01 \x01(\v2%.industries.loosh.yutani.v1.SessionIdR\tsessionId\"2\n" +
	"\x16DestroySessionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x15\n" +
	"\x13ListSessionsRequest\"[\n" +
	"\x14ListSessionsResponse\x12C\n" +
	"\bsessions\x18\x01 \x03(\v2'.industries.loosh.yutani.v1.SessionInfoR\bsessions\"\x93\x01\n" +
	"\vSessionInfo\x12D\n" +
	"\n" +
	"session_id\x18\x01 \x01(\v2%.industries.loosh.yutani.v1.SessionIdR\tsessionId\x12\x1f\n" +
	"\vclient_name\x18\x02 \x01(\tR\n" +
	"clientName\x12\x1d\n" +
	"\n" +
	"created_at\x18\x03 \x01(\x03R\tcreatedAt\"\x16\n" +
	"\x14GetServerInfoRequest\"\x94\x02\n" +
	"\x15GetServerInfoResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12'\n" +
	"\x0factive_sessions\x18\x02 \x01(\x05R\x0eactiveSessions\x12!\n" +
	"\fmax_sessions\x18\x03 \x01(\x05R\vmaxSessions\x12A\n" +
	"\vscreen_size\x18\x04 \x01(\v2 .industries.loosh.yutani.v1.SizeR\n" +
	"screenSize\x12R\n" +
	"\fcapabilities\x18\x05 \x01(\v2..industries.loosh.yutani.v1.ServerCapabilitiesR\fcapabilities\"\xaa\x01\n" +
	"\x12ServerCapabilities\x12#\n" +
	"\rmouse_support\x18\x01 \x01(\bR\fmouseSupport\x12#\n" +
	"\rpaste_support\x18\x02 \x01(\bR\fpasteSupport\x12\x1d\n" +
	"\n" +
	"true_color\x18\x03 \x01(\bR\ttrueColor\x12+\n" +
	"\x11supported_widgets\x18\x04 \x03(\tR\x10supportedWidgets\"+\n" +
	"\vPingRequest\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\"W\n" +
	"\fPingResponse\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12)\n" +
	"\x10server_timestamp\x18\x02 \x01(\x03R\x0fserverTimestamp2\xc3\x04\n" +
	"\x0eSessionService\x12t\n" +
	"\rCreateSession\x120.industries.loosh.yutani.v1.CreateSessionRequest\x1a1.industries.loosh.yutani.v1.CreateSessionResponse\x12w\n" +
	"\x0eDestroySession\x121.industries.loosh.yutani.v1.DestroySessionRequest\x1a2.industries.loosh.yutani.v1.DestroySessionResponse\x12q\n" +
	"\fListSessions\x12/.industries.loosh.yutani.v1.ListSessionsRequest\x1a0.industries.loosh.yutani.v1.ListSessionsResponse\x12t\n" +
	"\rGetServerInfo\x120.industries.loosh.yutani.v1.GetServerInfoRequest\x1a1.industries.loosh.yutani.v1.GetServerInfoResponse\x12Y\n" +
	"\x04Ping\x12'.industries.loosh.yutani.v1.PingRequest\x1a(.industries.loosh.yutani.v1.PingResponseB*Z(github.com/chazu/yutani/pkg/proto/yutanib\x06proto3"

var (
	file_industries_loosh_yutani_v1_session_proto_rawDescOnce sync.Once
	file_industries_loosh_yutani_v1_session_proto_rawDescData []byte
)

func file_industries_loosh_yutani_v1_session_proto_rawDescGZIP() []byte {
	file_industries_loosh_yutani_v1_session_proto_rawDescOnce.Do(func() {
		file_industries_loosh_yutani_v1_session_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_industries_loosh_yutani_v1_session_proto_rawDesc), len(file_industries_loosh_yutani_v1_session_proto_rawDesc)))
	})
	return file_industries_loosh_yutani_v1_session_proto_rawDescData
}

var file_industries_loosh_yutani_v1_session_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_industries_loosh_yutani_v1_session_proto_goTypes = []any{
	(*CreateSessionRequest)(nil),   // 0: industries.loosh.yutani.v1.CreateSessionRequest
	(*SessionPreferences)(nil),     // 1: industries.loosh.yutani.v1.SessionPreferences
	(*CreateSessionResponse)(nil),  // 2: industries.loosh.yutani.v1.CreateSessionResponse
	(*DestroySessionRequest)(nil),  // 3: industries.loosh.yutani.v1.DestroySessionRequest
	(*DestroySessionResponse)(nil), // 4: industries.loosh.yutani.v1.DestroySessionResponse
	(*ListSessionsRequest)(nil),    // 5: industries.loosh.yutani.v1.ListSessionsRequest
	(*ListSessionsResponse)(nil),   // 6: industries.loosh.yutani.v1.ListSessionsResponse
	(*SessionInfo)(nil),            // 7: industries.loosh.yutani.v1.SessionInfo
	(*GetServerInfoRequest)(nil),   // 8: industries.loosh.yutani.v1.GetServerInfoRequest
	(*GetServerInfoResponse)(nil),  // 9: industries.loosh.yutani.v1.GetServerInfoResponse
	(*ServerCapabilities)(nil),     // 10: industries.loosh.yutani.v1.ServerCapabilities
	(*PingRequest)(nil),            // 11: industries.loosh.yutani.v1.PingRequest
	(*PingResponse)(nil),           // 12: industries.loosh.yutani.v1.PingResponse
	(*SessionId)(nil),              // 13: industries.loosh.yutani.v1.SessionId
	(*Size)(nil),                   // 14: industries.loosh.yutani.v1.Size
}
var file_industries_loosh_yutani_v1_session_proto_depIdxs = []int32{
	1,  // 0: industries.loosh.yutani.v1.CreateSessionRequest.preferences:type_name -> industries.loosh.yutani.v1.SessionPreferences
	13, // 1: industries.loosh.yutani.v1.CreateSessionResponse.session_id:type_name -> industries.loosh.yutani.v1.SessionId
	13, // 2: industries.loosh.yutani.v1.DestroySessionRequest.session_id:type_name -> industries.loosh.yutani.v1.SessionId
	7,  // 3: industries.loosh.yutani.v1.ListSessionsResponse.sessions:type_name -> industries.loosh.yutani.v1.SessionInfo
	13, // 4: industries.loosh.yutani.v1.SessionInfo.session_id:type_name -> industries.loosh.yutani.v1.SessionId
	14, // 5: industries.loosh.yutani.v1.GetServerInfoResponse.screen_size:type_name -> industries.loosh.yutani.v1.Size
	10, // 6: industries.loosh.yutani.v1.GetServerInfoResponse.capabilities:type_name -> industries.loosh.yutani.v1.ServerCapabilities
	0,  // 7: industries.loosh.yutani.v1.SessionService.CreateSession:input_type -> industries.loosh.yutani.v1.CreateSessionRequest
	3,  // 8: industries.loosh.yutani.v1.SessionService.DestroySession:input_type -> industries.loosh.yutani.v1.DestroySessionRequest
	5,  // 9: industries.loosh.yutani.v1.SessionService.ListSessions:input_type -> industries.loosh.yutani.v1.ListSessionsRequest
	8,  // 10: industries.loosh.yutani.v1.SessionService.GetServerInfo:input_type -> industries.loosh.yutani.v1.GetServerInfoRequest
	11, // 11: industries.loosh.yutani.v1.SessionService.Ping:input_type -> industries.loosh.yutani.v1.PingRequest
	2,  // 12: industries.loosh.yutani.v1.SessionService.CreateSession:output_type -> industries.loosh.yutani.v1.CreateSessionResponse
	4,  // 13: industries.loosh.yutani.v1.SessionService.DestroySession:output_type -> industries.loosh.yutani.v1.DestroySessionResponse
	6,  // 14: industries.loosh.yutani.v1.SessionService.ListSessions:output_type -> industries.loosh.yutani.v1.ListSessionsResponse
	9,  // 15: industries.loosh.yutani.v1.SessionService.GetServerInfo:output_type -> industries.loosh.yutani.v1.GetServerInfoResponse
	12, // 16: industries.loosh.yutani.v1.SessionService.Ping:output_type -> industries.loosh.yutani.v1.PingResponse
	12, // [12:17] is the sub-list for method output_type
	7,  // [7:12] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_industries_loosh_yutani_v1_session_proto_init() }
func file_industries_loosh_yutani_v1_session_proto_init() {
	if File_industries_loosh_yutani_v1_session_proto != nil {
		return
	}
	file_industries_loosh_yutani_v1_types_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_industries_loosh_yutani_v1_session_proto_rawDesc), len(file_industries_loosh_yutani_v1_session_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_industries_loosh_yutani_v1_session_proto_goTypes,
		DependencyIndexes: file_industries_loosh_yutani_v1_session_proto_depIdxs,
		MessageInfos:      file_industries_loosh_yutani_v1_session_proto_msgTypes,
	}.Build()
	File_industries_loosh_yutani_v1_session_proto = out.File
	file_industries_loosh_yutani_v1_session_proto_goTypes = nil
	file_industries_loosh_yutani_v1_session_proto_depIdxs = nil
}
