// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v5.29.3
// source: industries/loosh/yutani/v1/table.proto

package yutani

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TableService_SetCell_FullMethodName       = "/industries.loosh.yutani.v1.TableService/SetCell"
	TableService_GetCell_FullMethodName       = "/industries.loosh.yutani.v1.TableService/GetCell"
	TableService_SetCells_FullMethodName      = "/industries.loosh.yutani.v1.TableService/SetCells"
	TableService_Clear_FullMethodName         = "/industries.loosh.yutani.v1.TableService/Clear"
	TableService_GetDimensions_FullMethodName = "/industries.loosh.yutani.v1.TableService/GetDimensions"
	TableService_GetSelection_FullMethodName  = "/industries.loosh.yutani.v1.TableService/GetSelection"
	TableService_SetSelection_FullMethodName  = "/industries.loosh.yutani.v1.TableService/SetSelection"
	TableService_SetFixed_FullMethodName      = "/industries.loosh.yutani.v1.TableService/SetFixed"
)

// TableServiceClient is the client API for TableService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// TableService provides operations for Table widgets
type TableServiceClient interface {
	// Set a single cell's content
	SetCell(ctx context.Context, in *SetTableCellRequest, opts ...grpc.CallOption) (*SetTableCellResponse, error)
	// Get a single cell's content
	GetCell(ctx context.Context, in *GetTableCellRequest, opts ...grpc.CallOption) (*GetTableCellResponse, error)
	// Set multiple cells (batch operation)
	SetCells(ctx context.Context, in *SetTableCellsRequest, opts ...grpc.CallOption) (*SetTableCellsResponse, error)
	// Clear the table
	Clear(ctx context.Context, in *TableClearRequest, opts ...grpc.CallOption) (*TableClearResponse, error)
	// Get table dimensions (rows, columns)
	GetDimensions(ctx context.Context, in *TableGetDimensionsRequest, opts ...grpc.CallOption) (*TableGetDimensionsResponse, error)
	// Get current selection
	GetSelection(ctx context.Context, in *TableGetSelectionRequest, opts ...grpc.CallOption) (*TableGetSelectionResponse, error)
	// Set current selection
	SetSelection(ctx context.Context, in *TableSetSelectionRequest, opts ...grpc.CallOption) (*TableSetSelectionResponse, error)
	// Set fixed rows/columns (headers)
	SetFixed(ctx context.Context, in *TableSetFixedRequest, opts ...grpc.CallOption) (*TableSetFixedResponse, error)
}

type tableServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTableServiceClient(cc grpc.ClientConnInterface) TableServiceClient {
	return &tableServiceClient{cc}
}

func (c *tableServiceClient) SetCell(ctx context.Context, in *SetTableCellRequest, opts ...grpc.CallOption) (*SetTableCellResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetTableCellResponse)
	err := c.cc.Invoke(ctx, TableService_SetCell_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tableServiceClient) GetCell(ctx context.Context, in *GetTableCellRequest, opts ...grpc.CallOption) (*GetTableCellResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTableCellResponse)
	err := c.cc.Invoke(ctx, TableService_GetCell_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tableServiceClient) SetCells(ctx context.Context, in *SetTableCellsRequest, opts ...grpc.CallOption) (*SetTableCellsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetTableCellsResponse)
	err := c.cc.Invoke(ctx, TableService_SetCells_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tableServiceClient) Clear(ctx context.Context, in *TableClearRequest, opts ...grpc.CallOption) (*TableClearResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TableClearResponse)
	err := c.cc.Invoke(ctx, TableService_Clear_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tableServiceClient) GetDimensions(ctx context.Context, in *TableGetDimensionsRequest, opts ...grpc.CallOption) (*TableGetDimensionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TableGetDimensionsResponse)
	err := c.cc.Invoke(ctx, TableService_GetDimensions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tableServiceClient) GetSelection(ctx context.Context, in *TableGetSelectionRequest, opts ...grpc.CallOption) (*TableGetSelectionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TableGetSelectionResponse)
	err := c.cc.Invoke(ctx, TableService_GetSelection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tableServiceClient) SetSelection(ctx context.Context, in *TableSetSelectionRequest, opts ...grpc.CallOption) (*TableSetSelectionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TableSetSelectionResponse)
	err := c.cc.Invoke(ctx, TableService_SetSelection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tableServiceClient) SetFixed(ctx context.Context, in *TableSetFixedRequest, opts ...grpc.CallOption) (*TableSetFixedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TableSetFixedResponse)
	err := c.cc.Invoke(ctx, TableService_SetFixed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TableServiceServer is the server API for TableService service.
// All implementations must embed UnimplementedTableServiceServer
// for forward compatibility.
//
// TableService provides operations for Table widgets
type TableServiceServer interface {
	// Set a single cell's content
	SetCell(context.Context, *SetTableCellRequest) (*SetTableCellResponse, error)
	// Get a single cell's content
	GetCell(context.Context, *GetTableCellRequest) (*GetTableCellResponse, error)
	// Set multiple cells (batch operation)
	SetCells(context.Context, *SetTableCellsRequest) (*SetTableCellsResponse, error)
	// Clear the table
	Clear(context.Context, *TableClearRequest) (*TableClearResponse, error)
	// Get table dimensions (rows, columns)
	GetDimensions(context.Context, *TableGetDimensionsRequest) (*TableGetDimensionsResponse, error)
	// Get current selection
	GetSelection(context.Context, *TableGetSelectionRequest) (*TableGetSelectionResponse, error)
	// Set current selection
	SetSelection(context.Context, *TableSetSelectionRequest) (*TableSetSelectionResponse, error)
	// Set fixed rows/columns (headers)
	SetFixed(context.Context, *TableSetFixedRequest) (*TableSetFixedResponse, error)
	mustEmbedUnimplementedTableServiceServer()
}

// UnimplementedTableServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTableServiceServer struct{}

func (UnimplementedTableServiceServer) SetCell(context.Context, *SetTableCellRequest) (*SetTableCellResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetCell not implemented")
}
func (UnimplementedTableServiceServer) GetCell(context.Context, *GetTableCellRequest) (*GetTableCellResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCell not implemented")
}
func (UnimplementedTableServiceServer) SetCells(context.Context, *SetTableCellsRequest) (*SetTableCellsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetCells not implemented")
}
func (UnimplementedTableServiceServer) Clear(context.Context, *TableClearRequest) (*TableClearResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Clear not implemented")
}
func (UnimplementedTableServiceServer) GetDimensions(context.Context, *TableGetDimensionsRequest) (*TableGetDimensionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDimensions not implemented")
}
func (UnimplementedTableServiceServer) GetSelection(context.Context, *TableGetSelectionRequest) (*TableGetSelectionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSelection not implemented")
}
func (UnimplementedTableServiceServer) SetSelection(context.Context, *TableSetSelectionRequest) (*TableSetSelectionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetSelection not implemented")
}
func (UnimplementedTableServiceServer) SetFixed(context.Context, *TableSetFixedRequest) (*TableSetFixedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetFixed not implemented")
}
func (UnimplementedTableServiceServer) mustEmbedUnimplementedTableServiceServer() {}
func (UnimplementedTableServiceServer) testEmbeddedByValue()                      {}

// UnsafeTableServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TableServiceServer will
// result in compilation errors.
type UnsafeTableServiceServer interface {
	mustEmbedUnimplementedTableServiceServer()
}

func RegisterTableServiceServer(s grpc.ServiceRegistrar, srv TableServiceServer) {
	// If the following call panics, it indicates UnimplementedTableServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TableService_ServiceDesc, srv)
}

func _TableService_SetCell_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetTableCellRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TableServiceServer).SetCell(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TableService_SetCell_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TableServiceServer).SetCell(ctx, req.(*SetTableCellRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TableService_GetCell_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTableCellRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TableServiceServer).GetCell(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TableService_GetCell_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TableServiceServer).GetCell(ctx, req.(*GetTableCellRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TableService_SetCells_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetTableCellsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TableServiceServer).SetCells(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TableService_SetCells_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TableServiceServer).SetCells(ctx, req.(*SetTableCellsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TableService_Clear_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TableClearRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TableServiceServer).Clear(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TableService_Clear_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TableServiceServer).Clear(ctx, req.(*TableClearRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TableService_GetDimensions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TableGetDimensionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TableServiceServer).GetDimensions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TableService_GetDimensions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TableServiceServer).GetDimensions(ctx, req.(*TableGetDimensionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TableService_GetSelection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TableGetSelectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TableServiceServer).GetSelection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TableService_GetSelection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TableServiceServer).GetSelection(ctx, req.(*TableGetSelectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TableService_SetSelection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TableSetSelectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TableServiceServer).SetSelection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TableService_SetSelection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TableServiceServer).SetSelection(ctx, req.(*TableSetSelectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TableService_SetFixed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TableSetFixedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TableServiceServer).SetFixed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TableService_SetFixed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TableServiceServer).SetFixed(ctx, req.(*TableSetFixedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TableService_ServiceDesc is the grpc.ServiceDesc for TableService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TableService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "industries.loosh.yutani.v1.TableService",
	HandlerType: (*TableServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetCell",
			Handler:    _TableService_SetCell_Handler,
		},
		{
			MethodName: "GetCell",
			Handler:    _TableService_GetCell_Handler,
		},
		{
			MethodName: "SetCells",
			Handler:    _TableService_SetCells_Handler,
		},
		{
			MethodName: "Clear",
			Handler:    _TableService_Clear_Handler,
		},
		{
			MethodName: "GetDimensions",
			Handler:    _TableService_GetDimensions_Handler,
		},
		{
			MethodName: "GetSelection",
			Handler:    _TableService_GetSelection_Handler,
		},
		{
			MethodName: "SetSelection",
			Handler:    _TableService_SetSelection_Handler,
		},
		{
			MethodName: "SetFixed",
			Handler:    _TableService_SetFixed_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "industries/loosh/yutani/v1/table.proto",
}
