// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: industries/loosh/yutani/v1/table.proto

package yutani

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Table cell definition
type TableCell struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Color         *Color                 `protobuf:"bytes,2,opt,name=color,proto3,oneof" json:"color,omitempty"`
	Align         *Alignment             `protobuf:"varint,3,opt,name=align,proto3,enum=industries.loosh.yutani.v1.Alignment,oneof" json:"align,omitempty"`
	Selectable    *bool                  `protobuf:"varint,4,opt,name=selectable,proto3,oneof" json:"selectable,omitempty"`
	Expansion     *int32                 `protobuf:"varint,5,opt,name=expansion,proto3,oneof" json:"expansion,omitempty"` // Column expansion factor
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TableCell) Reset() {
	*x = TableCell{}
	mi := &file_industries_loosh_yutani_v1_table_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TableCell) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableCell) ProtoMessage() {}

func (x *TableCell) ProtoReflect() protoreflect.Message {
	mi := &file_industries_loosh_yutani_v1_table_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableCell.ProtoReflect.Descriptor instead.
func (*TableCell) Descriptor() ([]byte, []int) {
	return file_industries_loosh_yutani_v1_table_proto_rawDescGZIP(), []int{0}
}

func (x *TableCell) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *TableCell) GetColor() *Color {
	if x != nil {
		return x.Color
	}
	return nil
}

func (x *TableCell) GetAlign() Alignment {
	if x != nil && x.Align != nil {
		return *x.Align
	}
	return Alignment_ALIGN_LEFT
}

func (x *TableCell) GetSelectable() bool {
	if x != nil && x.Selectable != nil {
		return *x.Selectable
	}
	return false
}

func (x *TableCell) GetExpansion() int32 {
	if x != nil && x.Expansion != nil {
		return *x.Expansion
	}
	return 0
}

type SetTableCellRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     *SessionId             `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	WidgetId      *WidgetId              `protobuf:"bytes,2,opt,name=widget_id,json=widgetId,proto3" json:"widget_id,omitempty"`
	Row           int32                  `protobuf:"varint,3,opt,name=row,proto3" json:"row,omitempty"`
	Column        int32                  `protobuf:"varint,4,opt,name=column,proto3" json:"column,omitempty"`
	Cell          *TableCell             `protobuf:"bytes,5,opt,name=cell,proto3" json:"cell,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetTableCellRequest) Reset() {
	*x = SetTableCellRequest{}
	mi := &file_industries_loosh_yutani_v1_table_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetTableCellRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetTableCellRequest) ProtoMessage() {}

func (x *SetTableCellRequest) ProtoReflect() protoreflect.Message {
	mi := &file_industries_loosh_yutani_v1_table_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetTableCellRequest.ProtoReflect.Descriptor instead.
func (*SetTableCellRequest) Descriptor() ([]byte, []int) {
	return file_industries_loosh_yutani_v1_table_proto_rawDescGZIP(), []int{1}
}

func (x *SetTableCellRequest) GetSessionId() *SessionId {
	if x != nil {
		return x.SessionId
	}
	return nil
}

func (x *SetTableCellRequest) GetWidgetId() *WidgetId {
	if x != nil {
		return x.WidgetId
	}
	return nil
}

func (x *SetTableCellRequest) GetRow() int32 {
	if x != nil {
		return x.Row
	}
	return 0
}

func (x *SetTableCellRequest) GetColumn() int32 {
	if x != nil {
		return x.Column
	}
	return 0
}

func (x *SetTableCellRequest) GetCell() *TableCell {
	if x != nil {
		return x.Cell
	}
	return nil
}

type SetTableCellResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetTableCellResponse) Reset() {
	*x = SetTableCellResponse{}
	mi := &file_industries_loosh_yutani_v1_table_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetTableCellResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetTableCellResponse) ProtoMessage() {}

func (x *SetTableCellResponse) ProtoReflect() protoreflect.Message {
	mi := &file_industries_loosh_yutani_v1_table_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetTableCellResponse.ProtoReflect.Descriptor instead.
func (*SetTableCellResponse) Descriptor() ([]byte, []int) {
	return file_industries_loosh_yutani_v1_table_proto_rawDescGZIP(), []int{2}
}

func (x *SetTableCellResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetTableCellRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     *SessionId             `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	WidgetId      *WidgetId              `protobuf:"bytes,2,opt,name=widget_id,json=widgetId,proto3" json:"widget_id,omitempty"`
	Row           int32                  `protobuf:"varint,3,opt,name=row,proto3" json:"row,omitempty"`
	Column        int32                  `protobuf:"varint,4,opt,name=column,proto3" json:"column,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTableCellRequest) Reset() {
	*x = GetTableCellRequest{}
	mi := &file_industries_loosh_yutani_v1_table_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTableCellRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTableCellRequest) ProtoMessage() {}

func (x *GetTableCellRequest) ProtoReflect() protoreflect.Message {
	mi := &file_industries_loosh_yutani_v1_table_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTableCellRequest.ProtoReflect.Descriptor instead.
func (*GetTableCellRequest) Descriptor() ([]byte, []int) {
	return file_industries_loosh_yutani_v1_table_proto_rawDescGZIP(), []int{3}
}

func (x *GetTableCellRequest) GetSessionId() *SessionId {
	if x != nil {
		return x.SessionId
	}
	return nil
}

func (x *GetTableCellRequest) GetWidgetId() *WidgetId {
	if x != nil {
		return x.WidgetId
	}
	return nil
}

func (x *GetTableCellRequest) GetRow() int32 {
	if x != nil {
		return x.Row
	}
	return 0
}

func (x *GetTableCellRequest) GetColumn() int32 {
	if x != nil {
		return x.Column
	}
	return 0
}

type GetTableCellResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cell          *TableCell             `protobuf:"bytes,1,opt,name=cell,proto3" json:"cell,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTableCellResponse) Reset() {
	*x = GetTableCellResponse{}
	mi := &file_industries_loosh_yutani_v1_table_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTableCellResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTableCellResponse) ProtoMessage() {}

func (x *GetTableCellResponse) ProtoReflect() protoreflect.Message {
	mi := &file_industries_loosh_yutani_v1_table_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTableCellResponse.ProtoReflect.Descriptor instead.
func (*GetTableCellResponse) Descriptor() ([]byte, []int) {
	return file_industries_loosh_yutani_v1_table_proto_rawDescGZIP(), []int{4}
}

func (x *GetTableCellResponse) GetCell() *TableCell {
	if x != nil {
		return x.Cell
	}
	return nil
}

type SetTableCellsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     *SessionId             `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	WidgetId      *WidgetId              `protobuf:"bytes,2,opt,name=widget_id,json=widgetId,proto3" json:"widget_id,omitempty"`
	Cells         []*TableCellUpdate     `protobuf:"bytes,3,rep,name=cells,proto3" json:"cells,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetTableCellsRequest) Reset() {
	*x = SetTableCellsRequest{}
	mi := &file_industries_loosh_yutani_v1_table_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetTableCellsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetTableCellsRequest) ProtoMessage() {}

func (x *SetTableCellsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_industries_loosh_yutani_v1_table_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetTableCellsRequest.ProtoReflect.Descriptor instead.
func (*SetTableCellsRequest) Descriptor() ([]byte, []int) {
	return file_industries_loosh_yutani_v1_table_proto_rawDescGZIP(), []int{5}
}

func (x *SetTableCellsRequest) GetSessionId() *SessionId {
	if x != nil {
		return x.SessionId
	}
	return nil
}

func (x *SetTableCellsRequest) GetWidgetId() *WidgetId {
	if x != nil {
		return x.WidgetId
	}
	return nil
}

func (x *SetTableCellsRequest) GetCells() []*TableCellUpdate {
	if x != nil {
		return x.Cells
	}
	return nil
}

type TableCellUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Row           int32                  `protobuf:"varint,1,opt,name=row,proto3" json:"row,omitempty"`
	Column        int32                  `protobuf:"varint,2,opt,name=column,proto3" json:"column,omitempty"`
	Cell          *TableCell             `protobuf:"bytes,3,opt,name=cell,proto3" json:"cell,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TableCellUpdate) Reset() {
	*x = TableCellUpdate{}
	mi := &file_industries_loosh_yutani_v1_table_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TableCellUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableCellUpdate) ProtoMessage() {}

func (x *TableCellUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_industries_loosh_yutani_v1_table_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableCellUpdate.ProtoReflect.Descriptor instead.
func (*TableCellUpdate) Descriptor() ([]byte, []int) {
	return file_industries_loosh_yutani_v1_table_proto_rawDescGZIP(), []int{6}
}

func (x *TableCellUpdate) GetRow() int32 {
	if x != nil {
		return x.Row
	}
	return 0
}

func (x *TableCellUpdate) GetColumn() int32 {
	if x != nil {
		return x.Column
	}
	return 0
}

func (x *TableCellUpdate) GetCell() *TableCell {
	if x != nil {
		return x.Cell
	}
	return nil
}

type SetTableCellsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	CellsSet      int32                  `protobuf:"varint,2,opt,name=cells_set,json=cellsSet,proto3" json:"cells_set,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetTableCellsResponse) Reset() {
	*x = SetTableCellsResponse{}
	mi := &file_industries_loosh_yutani_v1_table_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetTableCellsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetTableCellsResponse) ProtoMessage() {}

func (x *SetTableCellsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_industries_loosh_yutani_v1_table_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetTableCellsResponse.ProtoReflect.Descriptor instead.
func (*SetTableCellsResponse) Descriptor() ([]byte, []int) {
	return file_industries_loosh_yutani_v1_table_proto_rawDescGZIP(), []int{7}
}

func (x *SetTableCellsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SetTableCellsResponse) GetCellsSet() int32 {
	if x != nil {
		return x.CellsSet
	}
	return 0
}

type ClearTableRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     *SessionId             `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	WidgetId      *WidgetId              `protobuf:"bytes,2,opt,name=widget_id,json=widgetId,proto3" json:"widget_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearTableRequest) Reset() {
	*x = ClearTableRequest{}
	mi := &file_industries_loosh_yutani_v1_table_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearTableRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearTableRequest) ProtoMessage() {}

func (x *ClearTableRequest) ProtoReflect() protoreflect.Message {
	mi := &file_industries_loosh_yutani_v1_table_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearTableRequest.ProtoReflect.Descriptor instead.
func (*ClearTableRequest) Descriptor() ([]byte, []int) {
	return file_industries_loosh_yutani_v1_table_proto_rawDescGZIP(), []int{8}
}

func (x *ClearTableRequest) GetSessionId() *SessionId {
	if x != nil {
		return x.SessionId
	}
	return nil
}

func (x *ClearTableRequest) GetWidgetId() *WidgetId {
	if x != nil {
		return x.WidgetId
	}
	return nil
}

type ClearTableResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearTableResponse) Reset() {
	*x = ClearTableResponse{}
	mi := &file_industries_loosh_yutani_v1_table_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearTableResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearTableResponse) ProtoMessage() {}

func (x *ClearTableResponse) ProtoReflect() protoreflect.Message {
	mi := &file_industries_loosh_yutani_v1_table_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearTableResponse.ProtoReflect.Descriptor instead.
func (*ClearTableResponse) Descriptor() ([]byte, []int) {
	return file_industries_loosh_yutani_v1_table_proto_rawDescGZIP(), []int{9}
}

func (x *ClearTableResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetDimensionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     *SessionId             `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	WidgetId      *WidgetId              `protobuf:"bytes,2,opt,name=widget_id,json=widgetId,proto3" json:"widget_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDimensionsRequest) Reset() {
	*x = GetDimensionsRequest{}
	mi := &file_industries_loosh_yutani_v1_table_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDimensionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDimensionsRequest) ProtoMessage() {}

func (x *GetDimensionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_industries_loosh_yutani_v1_table_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDimensionsRequest.ProtoReflect.Descriptor instead.
func (*GetDimensionsRequest) Descriptor() ([]byte, []int) {
	return file_industries_loosh_yutani_v1_table_proto_rawDescGZIP(), []int{10}
}

func (x *GetDimensionsRequest) GetSessionId() *SessionId {
	if x != nil {
		return x.SessionId
	}
	return nil
}

func (x *GetDimensionsRequest) GetWidgetId() *WidgetId {
	if x != nil {
		return x.WidgetId
	}
	return nil
}

type GetDimensionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rows          int32                  `protobuf:"varint,1,opt,name=rows,proto3" json:"rows,omitempty"`
	Columns       int32                  `protobuf:"varint,2,opt,name=columns,proto3" json:"columns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDimensionsResponse) Reset() {
	*x = GetDimensionsResponse{}
	mi := &file_industries_loosh_yutani_v1_table_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDimensionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDimensionsResponse) ProtoMessage() {}

func (x *GetDimensionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_industries_loosh_yutani_v1_table_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDimensionsResponse.ProtoReflect.Descriptor instead.
func (*GetDimensionsResponse) Descriptor() ([]byte, []int) {
	return file_industries_loosh_yutani_v1_table_proto_rawDescGZIP(), []int{11}
}

func (x *GetDimensionsResponse) GetRows() int32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

func (x *GetDimensionsResponse) GetColumns() int32 {
	if x != nil {
		return x.Columns
	}
	return 0
}

type GetSelectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     *SessionId             `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	WidgetId      *WidgetId              `protobuf:"bytes,2,opt,name=widget_id,json=widgetId,proto3" json:"widget_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSelectionRequest) Reset() {
	*x = GetSelectionRequest{}
	mi := &file_industries_loosh_yutani_v1_table_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSelectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSelectionRequest) ProtoMessage() {}

func (x *GetSelectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_industries_loosh_yutani_v1_table_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSelectionRequest.ProtoReflect.Descriptor instead.
func (*GetSelectionRequest) Descriptor() ([]byte, []int) {
	return file_industries_loosh_yutani_v1_table_proto_rawDescGZIP(), []int{12}
}

func (x *GetSelectionRequest) GetSessionId() *SessionId {
	if x != nil {
		return x.SessionId
	}
	return nil
}

func (x *GetSelectionRequest) GetWidgetId() *WidgetId {
	if x != nil {
		return x.WidgetId
	}
	return nil
}

type GetSelectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Row           int32                  `protobuf:"varint,1,opt,name=row,proto3" json:"row,omitempty"`
	Column        int32                  `protobuf:"varint,2,opt,name=column,proto3" json:"column,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSelectionResponse) Reset() {
	*x = GetSelectionResponse{}
	mi := &file_industries_loosh_yutani_v1_table_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSelectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSelectionResponse) ProtoMessage() {}

func (x *GetSelectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_industries_loosh_yutani_v1_table_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSelectionResponse.ProtoReflect.Descriptor instead.
func (*GetSelectionResponse) Descriptor() ([]byte, []int) {
	return file_industries_loosh_yutani_v1_table_proto_rawDescGZIP(), []int{13}
}

func (x *GetSelectionResponse) GetRow() int32 {
	if x != nil {
		return x.Row
	}
	return 0
}

func (x *GetSelectionResponse) GetColumn() int32 {
	if x != nil {
		return x.Column
	}
	return 0
}

type SetSelectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     *SessionId             `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	WidgetId      *WidgetId              `protobuf:"bytes,2,opt,name=widget_id,json=widgetId,proto3" json:"widget_id,omitempty"`
	Row           int32                  `protobuf:"varint,3,opt,name=row,proto3" json:"row,omitempty"`
	Column        int32                  `protobuf:"varint,4,opt,name=column,proto3" json:"column,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetSelectionRequest) Reset() {
	*x = SetSelectionRequest{}
	mi := &file_industries_loosh_yutani_v1_table_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetSelectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetSelectionRequest) ProtoMessage() {}

func (x *SetSelectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_industries_loosh_yutani_v1_table_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetSelectionRequest.ProtoReflect.Descriptor instead.
func (*SetSelectionRequest) Descriptor() ([]byte, []int) {
	return file_industries_loosh_yutani_v1_table_proto_rawDescGZIP(), []int{14}
}

func (x *SetSelectionRequest) GetSessionId() *SessionId {
	if x != nil {
		return x.SessionId
	}
	return nil
}

func (x *SetSelectionRequest) GetWidgetId() *WidgetId {
	if x != nil {
		return x.WidgetId
	}
	return nil
}

func (x *SetSelectionRequest) GetRow() int32 {
	if x != nil {
		return x.Row
	}
	return 0
}

func (x *SetSelectionRequest) GetColumn() int32 {
	if x != nil {
		return x.Column
	}
	return 0
}

type SetSelectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetSelectionResponse) Reset() {
	*x = SetSelectionResponse{}
	mi := &file_industries_loosh_yutani_v1_table_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetSelectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetSelectionResponse) ProtoMessage() {}

func (x *SetSelectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_industries_loosh_yutani_v1_table_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetSelectionResponse.ProtoReflect.Descriptor instead.
func (*SetSelectionResponse) Descriptor() ([]byte, []int) {
	return file_industries_loosh_yutani_v1_table_proto_rawDescGZIP(), []int{15}
}

func (x *SetSelectionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type SetFixedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     *SessionId             `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	WidgetId      *WidgetId              `protobuf:"bytes,2,opt,name=widget_id,json=widgetId,proto3" json:"widget_id,omitempty"`
	FixedRows     int32                  `protobuf:"varint,3,opt,name=fixed_rows,json=fixedRows,proto3" json:"fixed_rows,omitempty"`
	FixedColumns  int32                  `protobuf:"varint,4,opt,name=fixed_columns,json=fixedColumns,proto3" json:"fixed_columns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetFixedRequest) Reset() {
	*x = SetFixedRequest{}
	mi := &file_industries_loosh_yutani_v1_table_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetFixedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetFixedRequest) ProtoMessage() {}

func (x *SetFixedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_industries_loosh_yutani_v1_table_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetFixedRequest.ProtoReflect.Descriptor instead.
func (*SetFixedRequest) Descriptor() ([]byte, []int) {
	return file_industries_loosh_yutani_v1_table_proto_rawDescGZIP(), []int{16}
}

func (x *SetFixedRequest) GetSessionId() *SessionId {
	if x != nil {
		return x.SessionId
	}
	return nil
}

func (x *SetFixedRequest) GetWidgetId() *WidgetId {
	if x != nil {
		return x.WidgetId
	}
	return nil
}

func (x *SetFixedRequest) GetFixedRows() int32 {
	if x != nil {
		return x.FixedRows
	}
	return 0
}

func (x *SetFixedRequest) GetFixedColumns() int32 {
	if x != nil {
		return x.FixedColumns
	}
	return 0
}

type SetFixedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetFixedResponse) Reset() {
	*x = SetFixedResponse{}
	mi := &file_industries_loosh_yutani_v1_table_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetFixedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetFixedResponse) ProtoMessage() {}

func (x *SetFixedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_industries_loosh_yutani_v1_table_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetFixedResponse.ProtoReflect.Descriptor instead.
func (*SetFixedResponse) Descriptor() ([]byte, []int) {
	return file_industries_loosh_yutani_v1_table_proto_rawDescGZIP(), []int{17}
}

func (x *SetFixedResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_industries_loosh_yutani_v1_table_proto protoreflect.FileDescriptor

const file_industries_loosh_yutani_v1_table_proto_rawDesc = "" +
	"\n" +
	"&industries/loosh/yutani/v1/table.proto\x12\x1aindustries.loosh.yutani.v1\x1a&industries/loosh/yutani/v1/types.proto\"\x98\x02\n" +
	"\tTableCell\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12<\n" +
	"\x05color\x18\x02 \x01(\v2!.industries.loosh.yutani.v1.ColorH\x00R\x05color\x88\x01\x01\x12@\n" +
	"\x05align\x18\x03 \x01(\x0e2%.industries.loosh.yutani.v1.AlignmentH\x01R\x05align\x88\x01\x01\x12#\n" +
	"\n" +
	"selectable\x18\x04 \x01(\bH\x02R\n" +
	"selectable\x88\x01\x01\x12!\n" +
	"\texpansion\x18\x05 \x01(\x05H\x03R\texpansion\x88\x01\x01B\b\n" +
	"\x06_colorB\b\n" +
	"\x06_alignB\r\n" +
	"\v_selectableB\f\n" +
	"\n" +
	"_expansion\"\x83\x02\n" +
	"\x13SetTableCellRequest\x12D\n" +
	"\n" +
	"session_id\x18\x01 \x01(\v2%.industries.loosh.yutani.v1.SessionIdR\tsessionId\x12A\n" +
	"\twidget_id\x18\x02 \x01(\v2$.industries.loosh.yutani.v1.WidgetIdR\bwidgetId\x12\x10\n" +
	"\x03row\x18\x03 \x01(\x05R\x03row\x12\x16\n" +
	"\x06column\x18\x04 \x01(\x05R\x06column\x129\n" +
	"\x04cell\x18\x05 \x01(\v2%.industries.loosh.yutani.v1.TableCellR\x04cell\"0\n" +
	"\x14SetTableCellResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xc8\x01\n" +
	"\x13GetTableCellRequest\x12D\n" +
	"\n" +
	"session_id\x18\x01 \x01(\v2%.industries.loosh.yutani.v1.SessionIdR\tsessionId\x12A\n" +
	"\twidget_id\x18\x02 \x01(\v2$.industries.loosh.yutani.v1.WidgetIdR\bwidgetId\x12\x10\n" +
	"\x03row\x18\x03 \x01(\x05R\x03row\x12\x16\n" +
	"\x06column\x18\x04 \x01(\x05R\x06column\"Q\n" +
	"\x14GetTableCellResponse\x129\n" +
	"\x04cell\x18\x01 \x01(\v2%.industries.loosh.yutani.v1.TableCellR\x04cell\"\xe2\x01\n" +
	"\x14SetTableCellsRequest\x12D\n" +
	"\n" +
	"session_id\x18\x01 \x01(\v2%.industries.loosh.yutani.v1.SessionIdR\tsessionId\x12A\n" +
	"\twidget_id\x18\x02 \x01(\v2$.industries.loosh.yutani.v1.WidgetIdR\bwidgetId\x12A\n" +
	"\x05cells\x18\x03 \x03(\v2+.industries.loosh.yutani.v1.TableCellUpdateR\x05cells\"v\n" +
	"\x0fTableCellUpdate\x12\x10\n" +
	"\x03row\x18\x01 \x01(\x05R\x03row\x12\x16\n" +
	"\x06column\x18\x02 \x01(\x05R\x06column\x129\n" +
	"\x04cell\x18\x03 \x01(\v2%.industries.loosh.yutani.v1.TableCellR\x04cell\"N\n" +
	"\x15SetTableCellsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1b\n" +
	"\tcells_set\x18\x02 \x01(\x05R\bcellsSet\"\x9c\x01\n" +
	"\x11ClearTableRequest\x12D\n" +
	"\n" +
	"session_id\x18\x01 \x01(\v2%.industries.loosh.yutani.v1.SessionIdR\tsessionId\x12A\n" +
	"\twidget_id\x18\x02 \x01(\v2$.industries.loosh.yutani.v1.WidgetIdR\bwidgetId\".\n" +
	"\x12ClearTableResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x9f\x01\n" +
	"\x14GetDimensionsRequest\x12D\n" +
	"\n" +
	"session_id\x18\x01 \x01(\v2%.industries.loosh.yutani.v1.SessionIdR\tsessionId\x12A\n" +
	"\twidget_id\x18\x02 \x01(\v2$.industries.loosh.yutani.v1.WidgetIdR\bwidgetId\"E\n" +
	"\x15GetDimensionsResponse\x12\x12\n" +
	"\x04rows\x18\x01 \x01(\x05R\x04rows\x12\x18\n" +
	"\acolumns\x18\x02 \x01(\x05R\acolumns\"\x9e\x01\n" +
	"\x13GetSelectionRequest\x12D\n" +
	"\n" +
	"session_id\x18\x01 \x01(\v2%.industries.loosh.yutani.v1.SessionIdR\tsessionId\x12A\n" +
	"\twidget_id\x18\x02 \x01(\v2$.industries.loosh.yutani.v1.WidgetIdR\bwidgetId\"@\n" +
	"\x14GetSelectionResponse\x12\x10\n" +
	"\x03row\x18\x01 \x01(\x05R\x03row\x12\x16\n" +
	"\x06column\x18\x02 \x01(\x05R\x06column\"\xc8\x01\n" +
	"\x13SetSelectionRequest\x12D\n" +
	"\n" +
	"session_id\x18\x01 \x01(\v2%.industries.loosh.yutani.v1.SessionIdR\tsessionId\x12A\n" +
	"\twidget_id\x18\x02 \x01(\v2$.industries.loosh.yutani.v1.WidgetIdR\bwidgetId\x12\x10\n" +
	"\x03row\x18\x03 \x01(\x05R\x03row\x12\x16\n" +
	"\x06column\x18\x04 \x01(\x05R\x06column\"0\n" +
	"\x14SetSelectionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xde\x01\n" +
	"\x0fSetFixedRequest\x12D\n" +
	"\n" +
	"session_id\x18\x01 \x01(\v2%.industries.loosh.yutani.v1.SessionIdR\tsessionId\x12A\n" +
	"\twidget_id\x18\x02 \x01(\v2$.industries.loosh.yutani.v1.WidgetIdR\bwidgetId\x12\x1d\n" +
	"\n" +
	"fixed_rows\x18\x03 \x01(\x05R\tfixedRows\x12#\n" +
	"\rfixed_columns\x18\x04 \x01(\x05R\ffixedColumns\",\n" +
	"\x10SetFixedResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\x86\a\n" +
	"\fTableService\x12l\n" +
	"\aSetCell\x12/.industries.loosh.yutani.v1.SetTableCellRequest\x1a0.industries.loosh.yutani.v1.SetTableCellResponse\x12l\n" +
	"\aGetCell\x12/.industries.loosh.yutani.v1.GetTableCellRequest\x1a0.industries.loosh.yutani.v1.GetTableCellResponse\x12o\n" +
	"\bSetCells\x120.industries.loosh.yutani.v1.SetTableCellsRequest\x1a1.industries.loosh.yutani.v1.SetTableCellsResponse\x12f\n" +
	"\x05Clear\x12-.industries.loosh.yutani.v1.ClearTableRequest\x1a..industries.loosh.yutani.v1.ClearTableResponse\x12t\n" +
	"\rGetDimensions\x120.industries.loosh.yutani.v1.GetDimensionsRequest\x1a1.industries.loosh.yutani.v1.GetDimensionsResponse\x12q\n" +
	"\fGetSelection\x12/.industries.loosh.yutani.v1.GetSelectionRequest\x1a0.industries.loosh.yutani.v1.GetSelectionResponse\x12q\n" +
	"\fSetSelection\x12/.industries.loosh.yutani.v1.SetSelectionRequest\x1a0.industries.loosh.yutani.v1.SetSelectionResponse\x12e\n" +
	"\bSetFixed\x12+.industries.loosh.yutani.v1.SetFixedRequest\x1a,.industries.loosh.yutani.v1.SetFixedResponseB*Z(github.com/chazu/yutani/pkg/proto/yutanib\x06proto3"

var (
	file_industries_loosh_yutani_v1_table_proto_rawDescOnce sync.Once
	file_industries_loosh_yutani_v1_table_proto_rawDescData []byte
)

func file_industries_loosh_yutani_v1_table_proto_rawDescGZIP() []byte {
	file_industries_loosh_yutani_v1_table_proto_rawDescOnce.Do(func() {
		file_industries_loosh_yutani_v1_table_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_industries_loosh_yutani_v1_table_proto_rawDesc), len(file_industries_loosh_yutani_v1_table_proto_rawDesc)))
	})
	return file_industries_loosh_yutani_v1_table_proto_rawDescData
}

var file_industries_loosh_yutani_v1_table_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_industries_loosh_yutani_v1_table_proto_goTypes = []any{
	(*TableCell)(nil),             // 0: industries.loosh.yutani.v1.TableCell
	(*SetTableCellRequest)(nil),   // 1: industries.loosh.yutani.v1.SetTableCellRequest
	(*SetTableCellResponse)(nil),  // 2: industries.loosh.yutani.v1.SetTableCellResponse
	(*GetTableCellRequest)(nil),   // 3: industries.loosh.yutani.v1.GetTableCellRequest
	(*GetTableCellResponse)(nil),  // 4: industries.loosh.yutani.v1.GetTableCellResponse
	(*SetTableCellsRequest)(nil),  // 5: industries.loosh.yutani.v1.SetTableCellsRequest
	(*TableCellUpdate)(nil),       // 6: industries.loosh.yutani.v1.TableCellUpdate
	(*SetTableCellsResponse)(nil), // 7: industries.loosh.yutani.v1.SetTableCellsResponse
	(*ClearTableRequest)(nil),     // 8: industries.loosh.yutani.v1.ClearTableRequest
	(*ClearTableResponse)(nil),    // 9: industries.loosh.yutani.v1.ClearTableResponse
	(*GetDimensionsRequest)(nil),  // 10: industries.loosh.yutani.v1.GetDimensionsRequest
	(*GetDimensionsResponse)(nil), // 11: industries.loosh.yutani.v1.GetDimensionsResponse
	(*GetSelectionRequest)(nil),   // 12: industries.loosh.yutani.v1.GetSelectionRequest
	(*GetSelectionResponse)(nil),  // 13: industries.loosh.yutani.v1.GetSelectionResponse
	(*SetSelectionRequest)(nil),   // 14: industries.loosh.yutani.v1.SetSelectionRequest
	(*SetSelectionResponse)(nil),  // 15: industries.loosh.yutani.v1.SetSelectionResponse
	(*SetFixedRequest)(nil),       // 16: industries.loosh.yutani.v1.SetFixedRequest
	(*SetFixedResponse)(nil),      // 17: industries.loosh.yutani.v1.SetFixedResponse
	(*Color)(nil),                 // 18: industries.loosh.yutani.v1.Color
	(Alignment)(0),                // 19: industries.loosh.yutani.v1.Alignment
	(*SessionId)(nil),             // 20: industries.loosh.yutani.v1.SessionId
	(*WidgetId)(nil),              // 21: industries.loosh.yutani.v1.WidgetId
}
var file_industries_loosh_yutani_v1_table_proto_depIdxs = []int32{
	18, // 0: industries.loosh.yutani.v1.TableCell.color:type_name -> industries.loosh.yutani.v1.Color
	19, // 1: industries.loosh.yutani.v1.TableCell.align:type_name -> industries.loosh.yutani.v1.Alignment
	20, // 2: industries.loosh.yutani.v1.SetTableCellRequest.session_id:type_name -> industries.loosh.yutani.v1.SessionId
	21, // 3: industries.loosh.yutani.v1.SetTableCellRequest.widget_id:type_name -> industries.loosh.yutani.v1.WidgetId
	0,  // 4: industries.loosh.yutani.v1.SetTableCellRequest.cell:type_name -> industries.loosh.yutani.v1.TableCell
	20, // 5: industries.loosh.yutani.v1.GetTableCellRequest.session_id:type_name -> industries.loosh.yutani.v1.SessionId
	21, // 6: industries.loosh.yutani.v1.GetTableCellRequest.widget_id:type_name -> industries.loosh.yutani.v1.WidgetId
	0,  // 7: industries.loosh.yutani.v1.GetTableCellResponse.cell:type_name -> industries.loosh.yutani.v1.TableCell
	20, // 8: industries.loosh.yutani.v1.SetTableCellsRequest.session_id:type_name -> industries.loosh.yutani.v1.SessionId
	21, // 9: industries.loosh.yutani.v1.SetTableCellsRequest.widget_id:type_name -> industries.loosh.yutani.v1.WidgetId
	6,  // 10: industries.loosh.yutani.v1.SetTableCellsRequest.cells:type_name -> industries.loosh.yutani.v1.TableCellUpdate
	0,  // 11: industries.loosh.yutani.v1.TableCellUpdate.cell:type_name -> industries.loosh.yutani.v1.TableCell
	20, // 12: industries.loosh.yutani.v1.ClearTableRequest.session_id:type_name -> industries.loosh.yutani.v1.SessionId
	21, // 13: industries.loosh.yutani.v1.ClearTableRequest.widget_id:type_name -> industries.loosh.yutani.v1.WidgetId
	20, // 14: industries.loosh.yutani.v1.GetDimensionsRequest.session_id:type_name -> industries.loosh.yutani.v1.SessionId
	21, // 15: industries.loosh.yutani.v1.GetDimensionsRequest.widget_id:type_name -> industries.loosh.yutani.v1.WidgetId
	20, // 16: industries.loosh.yutani.v1.GetSelectionRequest.session_id:type_name -> industries.loosh.yutani.v1.SessionId
	21, // 17: industries.loosh.yutani.v1.GetSelectionRequest.widget_id:type_name -> industries.loosh.yutani.v1.WidgetId
	20, // 18: industries.loosh.yutani.v1.SetSelectionRequest.session_id:type_name -> industries.loosh.yutani.v1.SessionId
	21, // 19: industries.loosh.yutani.v1.SetSelectionRequest.widget_id:type_name -> industries.loosh.yutani.v1.WidgetId
	20, // 20: industries.loosh.yutani.v1.SetFixedRequest.session_id:type_name -> industries.loosh.yutani.v1.SessionId
	21, // 21: industries.loosh.yutani.v1.SetFixedRequest.widget_id:type_name -> industries.loosh.yutani.v1.WidgetId
	1,  // 22: industries.loosh.yutani.v1.TableService.SetCell:input_type -> industries.loosh.yutani.v1.SetTableCellRequest
	3,  // 23: industries.loosh.yutani.v1.TableService.GetCell:input_type -> industries.loosh.yutani.v1.GetTableCellRequest
	5,  // 24: industries.loosh.yutani.v1.TableService.SetCells:input_type -> industries.loosh.yutani.v1.SetTableCellsRequest
	8,  // 25: industries.loosh.yutani.v1.TableService.Clear:input_type -> industries.loosh.yutani.v1.ClearTableRequest
	10, // 26: industries.loosh.yutani.v1.TableService.GetDimensions:input_type -> industries.loosh.yutani.v1.GetDimensionsRequest
	12, // 27: industries.loosh.yutani.v1.TableService.GetSelection:input_type -> industries.loosh.yutani.v1.GetSelectionRequest
	14, // 28: industries.loosh.yutani.v1.TableService.SetSelection:input_type -> industries.loosh.yutani.v1.SetSelectionRequest
	16, // 29: industries.loosh.yutani.v1.TableService.SetFixed:input_type -> industries.loosh.yutani.v1.SetFixedRequest
	2,  // 30: industries.loosh.yutani.v1.TableService.SetCell:output_type -> industries.loosh.yutani.v1.SetTableCellResponse
	4,  // 31: industries.loosh.yutani.v1.TableService.GetCell:output_type -> industries.loosh.yutani.v1.GetTableCellResponse
	7,  // 32: industries.loosh.yutani.v1.TableService.SetCells:output_type -> industries.loosh.yutani.v1.SetTableCellsResponse
	9,  // 33: industries.loosh.yutani.v1.TableService.Clear:output_type -> industries.loosh.yutani.v1.ClearTableResponse
	11, // 34: industries.loosh.yutani.v1.TableService.GetDimensions:output_type -> industries.loosh.yutani.v1.GetDimensionsResponse
	13, // 35: industries.loosh.yutani.v1.TableService.GetSelection:output_type -> industries.loosh.yutani.v1.GetSelectionResponse
	15, // 36: industries.loosh.yutani.v1.TableService.SetSelection:output_type -> industries.loosh.yutani.v1.SetSelectionResponse
	17, // 37: industries.loosh.yutani.v1.TableService.SetFixed:output_type -> industries.loosh.yutani.v1.SetFixedResponse
	30, // [30:38] is the sub-list for method output_type
	22, // [22:30] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_industries_loosh_yutani_v1_table_proto_init() }
func file_industries_loosh_yutani_v1_table_proto_init() {
	if File_industries_loosh_yutani_v1_table_proto != nil {
		return
	}
	file_industries_loosh_yutani_v1_types_proto_init()
	file_industries_loosh_yutani_v1_table_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_industries_loosh_yutani_v1_table_proto_rawDesc), len(file_industries_loosh_yutani_v1_table_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_industries_loosh_yutani_v1_table_proto_goTypes,
		DependencyIndexes: file_industries_loosh_yutani_v1_table_proto_depIdxs,
		MessageInfos:      file_industries_loosh_yutani_v1_table_proto_msgTypes,
	}.Build()
	File_industries_loosh_yutani_v1_table_proto = out.File
	file_industries_loosh_yutani_v1_table_proto_goTypes = nil
	file_industries_loosh_yutani_v1_table_proto_depIdxs = nil
}
