// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: industries/loosh/yutani/v1/textarea.proto

package yutani

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TextAreaGetCursorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     *SessionId             `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	WidgetId      *WidgetId              `protobuf:"bytes,2,opt,name=widget_id,json=widgetId,proto3" json:"widget_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextAreaGetCursorRequest) Reset() {
	*x = TextAreaGetCursorRequest{}
	mi := &file_industries_loosh_yutani_v1_textarea_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextAreaGetCursorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextAreaGetCursorRequest) ProtoMessage() {}

func (x *TextAreaGetCursorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_industries_loosh_yutani_v1_textarea_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextAreaGetCursorRequest.ProtoReflect.Descriptor instead.
func (*TextAreaGetCursorRequest) Descriptor() ([]byte, []int) {
	return file_industries_loosh_yutani_v1_textarea_proto_rawDescGZIP(), []int{0}
}

func (x *TextAreaGetCursorRequest) GetSessionId() *SessionId {
	if x != nil {
		return x.SessionId
	}
	return nil
}

func (x *TextAreaGetCursorRequest) GetWidgetId() *WidgetId {
	if x != nil {
		return x.WidgetId
	}
	return nil
}

type TextAreaGetCursorResponse struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Row    int32                  `protobuf:"varint,1,opt,name=row,proto3" json:"row,omitempty"`
	Column int32                  `protobuf:"varint,2,opt,name=column,proto3" json:"column,omitempty"`
	// If there is a selection, these are the "to" end of the cursor
	ToRow         int32 `protobuf:"varint,3,opt,name=to_row,json=toRow,proto3" json:"to_row,omitempty"`
	ToColumn      int32 `protobuf:"varint,4,opt,name=to_column,json=toColumn,proto3" json:"to_column,omitempty"`
	HasSelection  bool  `protobuf:"varint,5,opt,name=has_selection,json=hasSelection,proto3" json:"has_selection,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextAreaGetCursorResponse) Reset() {
	*x = TextAreaGetCursorResponse{}
	mi := &file_industries_loosh_yutani_v1_textarea_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextAreaGetCursorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextAreaGetCursorResponse) ProtoMessage() {}

func (x *TextAreaGetCursorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_industries_loosh_yutani_v1_textarea_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextAreaGetCursorResponse.ProtoReflect.Descriptor instead.
func (*TextAreaGetCursorResponse) Descriptor() ([]byte, []int) {
	return file_industries_loosh_yutani_v1_textarea_proto_rawDescGZIP(), []int{1}
}

func (x *TextAreaGetCursorResponse) GetRow() int32 {
	if x != nil {
		return x.Row
	}
	return 0
}

func (x *TextAreaGetCursorResponse) GetColumn() int32 {
	if x != nil {
		return x.Column
	}
	return 0
}

func (x *TextAreaGetCursorResponse) GetToRow() int32 {
	if x != nil {
		return x.ToRow
	}
	return 0
}

func (x *TextAreaGetCursorResponse) GetToColumn() int32 {
	if x != nil {
		return x.ToColumn
	}
	return 0
}

func (x *TextAreaGetCursorResponse) GetHasSelection() bool {
	if x != nil {
		return x.HasSelection
	}
	return false
}

type TextAreaSetCursorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     *SessionId             `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	WidgetId      *WidgetId              `protobuf:"bytes,2,opt,name=widget_id,json=widgetId,proto3" json:"widget_id,omitempty"`
	Row           int32                  `protobuf:"varint,3,opt,name=row,proto3" json:"row,omitempty"`
	Column        int32                  `protobuf:"varint,4,opt,name=column,proto3" json:"column,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextAreaSetCursorRequest) Reset() {
	*x = TextAreaSetCursorRequest{}
	mi := &file_industries_loosh_yutani_v1_textarea_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextAreaSetCursorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextAreaSetCursorRequest) ProtoMessage() {}

func (x *TextAreaSetCursorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_industries_loosh_yutani_v1_textarea_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextAreaSetCursorRequest.ProtoReflect.Descriptor instead.
func (*TextAreaSetCursorRequest) Descriptor() ([]byte, []int) {
	return file_industries_loosh_yutani_v1_textarea_proto_rawDescGZIP(), []int{2}
}

func (x *TextAreaSetCursorRequest) GetSessionId() *SessionId {
	if x != nil {
		return x.SessionId
	}
	return nil
}

func (x *TextAreaSetCursorRequest) GetWidgetId() *WidgetId {
	if x != nil {
		return x.WidgetId
	}
	return nil
}

func (x *TextAreaSetCursorRequest) GetRow() int32 {
	if x != nil {
		return x.Row
	}
	return 0
}

func (x *TextAreaSetCursorRequest) GetColumn() int32 {
	if x != nil {
		return x.Column
	}
	return 0
}

type TextAreaSetCursorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextAreaSetCursorResponse) Reset() {
	*x = TextAreaSetCursorResponse{}
	mi := &file_industries_loosh_yutani_v1_textarea_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextAreaSetCursorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextAreaSetCursorResponse) ProtoMessage() {}

func (x *TextAreaSetCursorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_industries_loosh_yutani_v1_textarea_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextAreaSetCursorResponse.ProtoReflect.Descriptor instead.
func (*TextAreaSetCursorResponse) Descriptor() ([]byte, []int) {
	return file_industries_loosh_yutani_v1_textarea_proto_rawDescGZIP(), []int{3}
}

func (x *TextAreaSetCursorResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type TextAreaGetSelectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     *SessionId             `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	WidgetId      *WidgetId              `protobuf:"bytes,2,opt,name=widget_id,json=widgetId,proto3" json:"widget_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextAreaGetSelectionRequest) Reset() {
	*x = TextAreaGetSelectionRequest{}
	mi := &file_industries_loosh_yutani_v1_textarea_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextAreaGetSelectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextAreaGetSelectionRequest) ProtoMessage() {}

func (x *TextAreaGetSelectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_industries_loosh_yutani_v1_textarea_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextAreaGetSelectionRequest.ProtoReflect.Descriptor instead.
func (*TextAreaGetSelectionRequest) Descriptor() ([]byte, []int) {
	return file_industries_loosh_yutani_v1_textarea_proto_rawDescGZIP(), []int{4}
}

func (x *TextAreaGetSelectionRequest) GetSessionId() *SessionId {
	if x != nil {
		return x.SessionId
	}
	return nil
}

func (x *TextAreaGetSelectionRequest) GetWidgetId() *WidgetId {
	if x != nil {
		return x.WidgetId
	}
	return nil
}

type TextAreaGetSelectionResponse struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	HasSelection bool                   `protobuf:"varint,1,opt,name=has_selection,json=hasSelection,proto3" json:"has_selection,omitempty"`
	SelectedText string                 `protobuf:"bytes,2,opt,name=selected_text,json=selectedText,proto3" json:"selected_text,omitempty"`
	Start        int32                  `protobuf:"varint,3,opt,name=start,proto3" json:"start,omitempty"` // byte offset into text
	End          int32                  `protobuf:"varint,4,opt,name=end,proto3" json:"end,omitempty"`     // byte offset into text
	// Row/column positions for the selection range
	FromRow       int32 `protobuf:"varint,5,opt,name=from_row,json=fromRow,proto3" json:"from_row,omitempty"`
	FromColumn    int32 `protobuf:"varint,6,opt,name=from_column,json=fromColumn,proto3" json:"from_column,omitempty"`
	ToRow         int32 `protobuf:"varint,7,opt,name=to_row,json=toRow,proto3" json:"to_row,omitempty"`
	ToColumn      int32 `protobuf:"varint,8,opt,name=to_column,json=toColumn,proto3" json:"to_column,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextAreaGetSelectionResponse) Reset() {
	*x = TextAreaGetSelectionResponse{}
	mi := &file_industries_loosh_yutani_v1_textarea_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextAreaGetSelectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextAreaGetSelectionResponse) ProtoMessage() {}

func (x *TextAreaGetSelectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_industries_loosh_yutani_v1_textarea_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextAreaGetSelectionResponse.ProtoReflect.Descriptor instead.
func (*TextAreaGetSelectionResponse) Descriptor() ([]byte, []int) {
	return file_industries_loosh_yutani_v1_textarea_proto_rawDescGZIP(), []int{5}
}

func (x *TextAreaGetSelectionResponse) GetHasSelection() bool {
	if x != nil {
		return x.HasSelection
	}
	return false
}

func (x *TextAreaGetSelectionResponse) GetSelectedText() string {
	if x != nil {
		return x.SelectedText
	}
	return ""
}

func (x *TextAreaGetSelectionResponse) GetStart() int32 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *TextAreaGetSelectionResponse) GetEnd() int32 {
	if x != nil {
		return x.End
	}
	return 0
}

func (x *TextAreaGetSelectionResponse) GetFromRow() int32 {
	if x != nil {
		return x.FromRow
	}
	return 0
}

func (x *TextAreaGetSelectionResponse) GetFromColumn() int32 {
	if x != nil {
		return x.FromColumn
	}
	return 0
}

func (x *TextAreaGetSelectionResponse) GetToRow() int32 {
	if x != nil {
		return x.ToRow
	}
	return 0
}

func (x *TextAreaGetSelectionResponse) GetToColumn() int32 {
	if x != nil {
		return x.ToColumn
	}
	return 0
}

type TextAreaSetSelectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     *SessionId             `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	WidgetId      *WidgetId              `protobuf:"bytes,2,opt,name=widget_id,json=widgetId,proto3" json:"widget_id,omitempty"`
	Start         int32                  `protobuf:"varint,3,opt,name=start,proto3" json:"start,omitempty"` // byte offset into text
	End           int32                  `protobuf:"varint,4,opt,name=end,proto3" json:"end,omitempty"`     // byte offset into text
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextAreaSetSelectionRequest) Reset() {
	*x = TextAreaSetSelectionRequest{}
	mi := &file_industries_loosh_yutani_v1_textarea_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextAreaSetSelectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextAreaSetSelectionRequest) ProtoMessage() {}

func (x *TextAreaSetSelectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_industries_loosh_yutani_v1_textarea_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextAreaSetSelectionRequest.ProtoReflect.Descriptor instead.
func (*TextAreaSetSelectionRequest) Descriptor() ([]byte, []int) {
	return file_industries_loosh_yutani_v1_textarea_proto_rawDescGZIP(), []int{6}
}

func (x *TextAreaSetSelectionRequest) GetSessionId() *SessionId {
	if x != nil {
		return x.SessionId
	}
	return nil
}

func (x *TextAreaSetSelectionRequest) GetWidgetId() *WidgetId {
	if x != nil {
		return x.WidgetId
	}
	return nil
}

func (x *TextAreaSetSelectionRequest) GetStart() int32 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *TextAreaSetSelectionRequest) GetEnd() int32 {
	if x != nil {
		return x.End
	}
	return 0
}

type TextAreaSetSelectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextAreaSetSelectionResponse) Reset() {
	*x = TextAreaSetSelectionResponse{}
	mi := &file_industries_loosh_yutani_v1_textarea_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextAreaSetSelectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextAreaSetSelectionResponse) ProtoMessage() {}

func (x *TextAreaSetSelectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_industries_loosh_yutani_v1_textarea_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextAreaSetSelectionResponse.ProtoReflect.Descriptor instead.
func (*TextAreaSetSelectionResponse) Descriptor() ([]byte, []int) {
	return file_industries_loosh_yutani_v1_textarea_proto_rawDescGZIP(), []int{7}
}

func (x *TextAreaSetSelectionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type TextAreaHasSelectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     *SessionId             `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	WidgetId      *WidgetId              `protobuf:"bytes,2,opt,name=widget_id,json=widgetId,proto3" json:"widget_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextAreaHasSelectionRequest) Reset() {
	*x = TextAreaHasSelectionRequest{}
	mi := &file_industries_loosh_yutani_v1_textarea_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextAreaHasSelectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextAreaHasSelectionRequest) ProtoMessage() {}

func (x *TextAreaHasSelectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_industries_loosh_yutani_v1_textarea_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextAreaHasSelectionRequest.ProtoReflect.Descriptor instead.
func (*TextAreaHasSelectionRequest) Descriptor() ([]byte, []int) {
	return file_industries_loosh_yutani_v1_textarea_proto_rawDescGZIP(), []int{8}
}

func (x *TextAreaHasSelectionRequest) GetSessionId() *SessionId {
	if x != nil {
		return x.SessionId
	}
	return nil
}

func (x *TextAreaHasSelectionRequest) GetWidgetId() *WidgetId {
	if x != nil {
		return x.WidgetId
	}
	return nil
}

type TextAreaHasSelectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HasSelection  bool                   `protobuf:"varint,1,opt,name=has_selection,json=hasSelection,proto3" json:"has_selection,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextAreaHasSelectionResponse) Reset() {
	*x = TextAreaHasSelectionResponse{}
	mi := &file_industries_loosh_yutani_v1_textarea_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextAreaHasSelectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextAreaHasSelectionResponse) ProtoMessage() {}

func (x *TextAreaHasSelectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_industries_loosh_yutani_v1_textarea_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextAreaHasSelectionResponse.ProtoReflect.Descriptor instead.
func (*TextAreaHasSelectionResponse) Descriptor() ([]byte, []int) {
	return file_industries_loosh_yutani_v1_textarea_proto_rawDescGZIP(), []int{9}
}

func (x *TextAreaHasSelectionResponse) GetHasSelection() bool {
	if x != nil {
		return x.HasSelection
	}
	return false
}

type TextAreaGetSelectedTextRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     *SessionId             `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	WidgetId      *WidgetId              `protobuf:"bytes,2,opt,name=widget_id,json=widgetId,proto3" json:"widget_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextAreaGetSelectedTextRequest) Reset() {
	*x = TextAreaGetSelectedTextRequest{}
	mi := &file_industries_loosh_yutani_v1_textarea_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextAreaGetSelectedTextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextAreaGetSelectedTextRequest) ProtoMessage() {}

func (x *TextAreaGetSelectedTextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_industries_loosh_yutani_v1_textarea_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextAreaGetSelectedTextRequest.ProtoReflect.Descriptor instead.
func (*TextAreaGetSelectedTextRequest) Descriptor() ([]byte, []int) {
	return file_industries_loosh_yutani_v1_textarea_proto_rawDescGZIP(), []int{10}
}

func (x *TextAreaGetSelectedTextRequest) GetSessionId() *SessionId {
	if x != nil {
		return x.SessionId
	}
	return nil
}

func (x *TextAreaGetSelectedTextRequest) GetWidgetId() *WidgetId {
	if x != nil {
		return x.WidgetId
	}
	return nil
}

type TextAreaGetSelectedTextResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	HasSelection  bool                   `protobuf:"varint,2,opt,name=has_selection,json=hasSelection,proto3" json:"has_selection,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextAreaGetSelectedTextResponse) Reset() {
	*x = TextAreaGetSelectedTextResponse{}
	mi := &file_industries_loosh_yutani_v1_textarea_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextAreaGetSelectedTextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextAreaGetSelectedTextResponse) ProtoMessage() {}

func (x *TextAreaGetSelectedTextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_industries_loosh_yutani_v1_textarea_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextAreaGetSelectedTextResponse.ProtoReflect.Descriptor instead.
func (*TextAreaGetSelectedTextResponse) Descriptor() ([]byte, []int) {
	return file_industries_loosh_yutani_v1_textarea_proto_rawDescGZIP(), []int{11}
}

func (x *TextAreaGetSelectedTextResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *TextAreaGetSelectedTextResponse) GetHasSelection() bool {
	if x != nil {
		return x.HasSelection
	}
	return false
}

type TextAreaInsertTextRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     *SessionId             `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	WidgetId      *WidgetId              `protobuf:"bytes,2,opt,name=widget_id,json=widgetId,proto3" json:"widget_id,omitempty"`
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextAreaInsertTextRequest) Reset() {
	*x = TextAreaInsertTextRequest{}
	mi := &file_industries_loosh_yutani_v1_textarea_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextAreaInsertTextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextAreaInsertTextRequest) ProtoMessage() {}

func (x *TextAreaInsertTextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_industries_loosh_yutani_v1_textarea_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextAreaInsertTextRequest.ProtoReflect.Descriptor instead.
func (*TextAreaInsertTextRequest) Descriptor() ([]byte, []int) {
	return file_industries_loosh_yutani_v1_textarea_proto_rawDescGZIP(), []int{12}
}

func (x *TextAreaInsertTextRequest) GetSessionId() *SessionId {
	if x != nil {
		return x.SessionId
	}
	return nil
}

func (x *TextAreaInsertTextRequest) GetWidgetId() *WidgetId {
	if x != nil {
		return x.WidgetId
	}
	return nil
}

func (x *TextAreaInsertTextRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type TextAreaInsertTextResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextAreaInsertTextResponse) Reset() {
	*x = TextAreaInsertTextResponse{}
	mi := &file_industries_loosh_yutani_v1_textarea_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextAreaInsertTextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextAreaInsertTextResponse) ProtoMessage() {}

func (x *TextAreaInsertTextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_industries_loosh_yutani_v1_textarea_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextAreaInsertTextResponse.ProtoReflect.Descriptor instead.
func (*TextAreaInsertTextResponse) Descriptor() ([]byte, []int) {
	return file_industries_loosh_yutani_v1_textarea_proto_rawDescGZIP(), []int{13}
}

func (x *TextAreaInsertTextResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_industries_loosh_yutani_v1_textarea_proto protoreflect.FileDescriptor

const file_industries_loosh_yutani_v1_textarea_proto_rawDesc = "" +
	"\n" +
	")industries/loosh/yutani/v1/textarea.proto\x12\x1aindustries.loosh.yutani.v1\x1a&industries/loosh/yutani/v1/types.proto\"\xa3\x01\n" +
	"\x18TextAreaGetCursorRequest\x12D\n" +
	"\n" +
	"session_id\x18\x01 \x01(\v2%.industries.loosh.yutani.v1.SessionIdR\tsessionId\x12A\n" +
	"\twidget_id\x18\x02 \x01(\v2$.industries.loosh.yutani.v1.WidgetIdR\bwidgetId\"\x9e\x01\n" +
	"\x19TextAreaGetCursorResponse\x12\x10\n" +
	"\x03row\x18\x01 \x01(\x05R\x03row\x12\x16\n" +
	"\x06column\x18\x02 \x01(\x05R\x06column\x12\x15\n" +
	"\x06to_row\x18\x03 \x01(\x05R\x05toRow\x12\x1b\n" +
	"\tto_column\x18\x04 \x01(\x05R\btoColumn\x12#\n" +
	"\rhas_selection\x18\x05 \x01(\bR\fhasSelection\"\xcd\x01\n" +
	"\x18TextAreaSetCursorRequest\x12D\n" +
	"\n" +
	"session_id\x18\x01 \x01(\v2%.industries.loosh.yutani.v1.SessionIdR\tsessionId\x12A\n" +
	"\twidget_id\x18\x02 \x01(\v2$.industries.loosh.yutani.v1.WidgetIdR\bwidgetId\x12\x10\n" +
	"\x03row\x18\x03 \x01(\x05R\x03row\x12\x16\n" +
	"\x06column\x18\x04 \x01(\x05R\x06column\"5\n" +
	"\x19TextAreaSetCursorResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xa6\x01\n" +
	"\x1bTextAreaGetSelectionRequest\x12D\n" +
	"\n" +
	"session_id\x18\x01 \x01(\v2%.industries.loosh.yutani.v1.SessionIdR\tsessionId\x12A\n" +
	"\twidget_id\x18\x02 \x01(\v2$.industries.loosh.yutani.v1.WidgetIdR\bwidgetId\"\x80\x02\n" +
	"\x1cTextAreaGetSelectionResponse\x12#\n" +
	"\rhas_selection\x18\x01 \x01(\bR\fhasSelection\x12#\n" +
	"\rselected_text\x18\x02 \x01(\tR\fselectedText\x12\x14\n" +
	"\x05start\x18\x03 \x01(\x05R\x05start\x12\x10\n" +
	"\x03end\x18\x04 \x01(\x05R\x03end\x12\x19\n" +
	"\bfrom_row\x18\x05 \x01(\x05R\afromRow\x12\x1f\n" +
	"\vfrom_column\x18\x06 \x01(\x05R\n" +
	"fromColumn\x12\x15\n" +
	"\x06to_row\x18\a \x01(\x05R\x05toRow\x12\x1b\n" +
	"\tto_column\x18\b \x01(\x05R\btoColumn\"\xce\x01\n" +
	"\x1bTextAreaSetSelectionRequest\x12D\n" +
	"\n" +
	"session_id\x18\x01 \x01(\v2%.industries.loosh.yutani.v1.SessionIdR\tsessionId\x12A\n" +
	"\twidget_id\x18\x02 \x01(\v2$.industries.loosh.yutani.v1.WidgetIdR\bwidgetId\x12\x14\n" +
	"\x05start\x18\x03 \x01(\x05R\x05start\x12\x10\n" +
	"\x03end\x18\x04 \x01(\x05R\x03end\"8\n" +
	"\x1cTextAreaSetSelectionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xa6\x01\n" +
	"\x1bTextAreaHasSelectionRequest\x12D\n" +
	"\n" +
	"session_id\x18\x01 \x01(\v2%.industries.loosh.yutani.v1.SessionIdR\tsessionId\x12A\n" +
	"\twidget_id\x18\x02 \x01(\v2$.industries.loosh.yutani.v1.WidgetIdR\bwidgetId\"C\n" +
	"\x1cTextAreaHasSelectionResponse\x12#\n" +
	"\rhas_selection\x18\x01 \x01(\bR\fhasSelection\"\xa9\x01\n" +
	"\x1eTextAreaGetSelectedTextRequest\x12D\n" +
	"\n" +
	"session_id\x18\x01 \x01(\v2%.industries.loosh.yutani.v1.SessionIdR\tsessionId\x12A\n" +
	"\twidget_id\x18\x02 \x01(\v2$.industries.loosh.yutani.v1.WidgetIdR\bwidgetId\"Z\n" +
	"\x1fTextAreaGetSelectedTextResponse\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12#\n" +
	"\rhas_selection\x18\x02 \x01(\bR\fhasSelection\"\xb8\x01\n" +
	"\x19TextAreaInsertTextRequest\x12D\n" +
	"\n" +
	"session_id\x18\x01 \x01(\v2%.industries.loosh.yutani.v1.SessionIdR\tsessionId\x12A\n" +
	"\twidget_id\x18\x02 \x01(\v2$.industries.loosh.yutani.v1.WidgetIdR\bwidgetId\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\"6\n" +
	"\x1aTextAreaInsertTextResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xb6\a\n" +
	"\x0fTextAreaService\x12\x80\x01\n" +
	"\x11GetCursorPosition\x124.industries.loosh.yutani.v1.TextAreaGetCursorRequest\x1a5.industries.loosh.yutani.v1.TextAreaGetCursorResponse\x12\x80\x01\n" +
	"\x11SetCursorPosition\x124.industries.loosh.yutani.v1.TextAreaSetCursorRequest\x1a5.industries.loosh.yutani.v1.TextAreaSetCursorResponse\x12\x81\x01\n" +
	"\fGetSelection\x127.industries.loosh.yutani.v1.TextAreaGetSelectionRequest\x1a8.industries.loosh.yutani.v1.TextAreaGetSelectionResponse\x12\x81\x01\n" +
	"\fSetSelection\x127.industries.loosh.yutani.v1.TextAreaSetSelectionRequest\x1a8.industries.loosh.yutani.v1.TextAreaSetSelectionResponse\x12\x81\x01\n" +
	"\fHasSelection\x127.industries.loosh.yutani.v1.TextAreaHasSelectionRequest\x1a8.industries.loosh.yutani.v1.TextAreaHasSelectionResponse\x12\x8a\x01\n" +
	"\x0fGetSelectedText\x12:.industries.loosh.yutani.v1.TextAreaGetSelectedTextRequest\x1a;.industries.loosh.yutani.v1.TextAreaGetSelectedTextResponse\x12\x83\x01\n" +
	"\x12InsertTextAtCursor\x125.industries.loosh.yutani.v1.TextAreaInsertTextRequest\x1a6.industries.loosh.yutani.v1.TextAreaInsertTextResponseB*Z(github.com/chazu/yutani/pkg/proto/yutanib\x06proto3"

var (
	file_industries_loosh_yutani_v1_textarea_proto_rawDescOnce sync.Once
	file_industries_loosh_yutani_v1_textarea_proto_rawDescData []byte
)

func file_industries_loosh_yutani_v1_textarea_proto_rawDescGZIP() []byte {
	file_industries_loosh_yutani_v1_textarea_proto_rawDescOnce.Do(func() {
		file_industries_loosh_yutani_v1_textarea_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_industries_loosh_yutani_v1_textarea_proto_rawDesc), len(file_industries_loosh_yutani_v1_textarea_proto_rawDesc)))
	})
	return file_industries_loosh_yutani_v1_textarea_proto_rawDescData
}

var file_industries_loosh_yutani_v1_textarea_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_industries_loosh_yutani_v1_textarea_proto_goTypes = []any{
	(*TextAreaGetCursorRequest)(nil),        // 0: industries.loosh.yutani.v1.TextAreaGetCursorRequest
	(*TextAreaGetCursorResponse)(nil),       // 1: industries.loosh.yutani.v1.TextAreaGetCursorResponse
	(*TextAreaSetCursorRequest)(nil),        // 2: industries.loosh.yutani.v1.TextAreaSetCursorRequest
	(*TextAreaSetCursorResponse)(nil),       // 3: industries.loosh.yutani.v1.TextAreaSetCursorResponse
	(*TextAreaGetSelectionRequest)(nil),     // 4: industries.loosh.yutani.v1.TextAreaGetSelectionRequest
	(*TextAreaGetSelectionResponse)(nil),    // 5: industries.loosh.yutani.v1.TextAreaGetSelectionResponse
	(*TextAreaSetSelectionRequest)(nil),     // 6: industries.loosh.yutani.v1.TextAreaSetSelectionRequest
	(*TextAreaSetSelectionResponse)(nil),    // 7: industries.loosh.yutani.v1.TextAreaSetSelectionResponse
	(*TextAreaHasSelectionRequest)(nil),     // 8: industries.loosh.yutani.v1.TextAreaHasSelectionRequest
	(*TextAreaHasSelectionResponse)(nil),    // 9: industries.loosh.yutani.v1.TextAreaHasSelectionResponse
	(*TextAreaGetSelectedTextRequest)(nil),  // 10: industries.loosh.yutani.v1.TextAreaGetSelectedTextRequest
	(*TextAreaGetSelectedTextResponse)(nil), // 11: industries.loosh.yutani.v1.TextAreaGetSelectedTextResponse
	(*TextAreaInsertTextRequest)(nil),       // 12: industries.loosh.yutani.v1.TextAreaInsertTextRequest
	(*TextAreaInsertTextResponse)(nil),      // 13: industries.loosh.yutani.v1.TextAreaInsertTextResponse
	(*SessionId)(nil),                       // 14: industries.loosh.yutani.v1.SessionId
	(*WidgetId)(nil),                        // 15: industries.loosh.yutani.v1.WidgetId
}
var file_industries_loosh_yutani_v1_textarea_proto_depIdxs = []int32{
	14, // 0: industries.loosh.yutani.v1.TextAreaGetCursorRequest.session_id:type_name -> industries.loosh.yutani.v1.SessionId
	15, // 1: industries.loosh.yutani.v1.TextAreaGetCursorRequest.widget_id:type_name -> industries.loosh.yutani.v1.WidgetId
	14, // 2: industries.loosh.yutani.v1.TextAreaSetCursorRequest.session_id:type_name -> industries.loosh.yutani.v1.SessionId
	15, // 3: industries.loosh.yutani.v1.TextAreaSetCursorRequest.widget_id:type_name -> industries.loosh.yutani.v1.WidgetId
	14, // 4: industries.loosh.yutani.v1.TextAreaGetSelectionRequest.session_id:type_name -> industries.loosh.yutani.v1.SessionId
	15, // 5: industries.loosh.yutani.v1.TextAreaGetSelectionRequest.widget_id:type_name -> industries.loosh.yutani.v1.WidgetId
	14, // 6: industries.loosh.yutani.v1.TextAreaSetSelectionRequest.session_id:type_name -> industries.loosh.yutani.v1.SessionId
	15, // 7: industries.loosh.yutani.v1.TextAreaSetSelectionRequest.widget_id:type_name -> industries.loosh.yutani.v1.WidgetId
	14, // 8: industries.loosh.yutani.v1.TextAreaHasSelectionRequest.session_id:type_name -> industries.loosh.yutani.v1.SessionId
	15, // 9: industries.loosh.yutani.v1.TextAreaHasSelectionRequest.widget_id:type_name -> industries.loosh.yutani.v1.WidgetId
	14, // 10: industries.loosh.yutani.v1.TextAreaGetSelectedTextRequest.session_id:type_name -> industries.loosh.yutani.v1.SessionId
	15, // 11: industries.loosh.yutani.v1.TextAreaGetSelectedTextRequest.widget_id:type_name -> industries.loosh.yutani.v1.WidgetId
	14, // 12: industries.loosh.yutani.v1.TextAreaInsertTextRequest.session_id:type_name -> industries.loosh.yutani.v1.SessionId
	15, // 13: industries.loosh.yutani.v1.TextAreaInsertTextRequest.widget_id:type_name -> industries.loosh.yutani.v1.WidgetId
	0,  // 14: industries.loosh.yutani.v1.TextAreaService.GetCursorPosition:input_type -> industries.loosh.yutani.v1.TextAreaGetCursorRequest
	2,  // 15: industries.loosh.yutani.v1.TextAreaService.SetCursorPosition:input_type -> industries.loosh.yutani.v1.TextAreaSetCursorRequest
	4,  // 16: industries.loosh.yutani.v1.TextAreaService.GetSelection:input_type -> industries.loosh.yutani.v1.TextAreaGetSelectionRequest
	6,  // 17: industries.loosh.yutani.v1.TextAreaService.SetSelection:input_type -> industries.loosh.yutani.v1.TextAreaSetSelectionRequest
	8,  // 18: industries.loosh.yutani.v1.TextAreaService.HasSelection:input_type -> industries.loosh.yutani.v1.TextAreaHasSelectionRequest
	10, // 19: industries.loosh.yutani.v1.TextAreaService.GetSelectedText:input_type -> industries.loosh.yutani.v1.TextAreaGetSelectedTextRequest
	12, // 20: industries.loosh.yutani.v1.TextAreaService.InsertTextAtCursor:input_type -> industries.loosh.yutani.v1.TextAreaInsertTextRequest
	1,  // 21: industries.loosh.yutani.v1.TextAreaService.GetCursorPosition:output_type -> industries.loosh.yutani.v1.TextAreaGetCursorResponse
	3,  // 22: industries.loosh.yutani.v1.TextAreaService.SetCursorPosition:output_type -> industries.loosh.yutani.v1.TextAreaSetCursorResponse
	5,  // 23: industries.loosh.yutani.v1.TextAreaService.GetSelection:output_type -> industries.loosh.yutani.v1.TextAreaGetSelectionResponse
	7,  // 24: industries.loosh.yutani.v1.TextAreaService.SetSelection:output_type -> industries.loosh.yutani.v1.TextAreaSetSelectionResponse
	9,  // 25: industries.loosh.yutani.v1.TextAreaService.HasSelection:output_type -> industries.loosh.yutani.v1.TextAreaHasSelectionResponse
	11, // 26: industries.loosh.yutani.v1.TextAreaService.GetSelectedText:output_type -> industries.loosh.yutani.v1.TextAreaGetSelectedTextResponse
	13, // 27: industries.loosh.yutani.v1.TextAreaService.InsertTextAtCursor:output_type -> industries.loosh.yutani.v1.TextAreaInsertTextResponse
	21, // [21:28] is the sub-list for method output_type
	14, // [14:21] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_industries_loosh_yutani_v1_textarea_proto_init() }
func file_industries_loosh_yutani_v1_textarea_proto_init() {
	if File_industries_loosh_yutani_v1_textarea_proto != nil {
		return
	}
	file_industries_loosh_yutani_v1_types_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_industries_loosh_yutani_v1_textarea_proto_rawDesc), len(file_industries_loosh_yutani_v1_textarea_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_industries_loosh_yutani_v1_textarea_proto_goTypes,
		DependencyIndexes: file_industries_loosh_yutani_v1_textarea_proto_depIdxs,
		MessageInfos:      file_industries_loosh_yutani_v1_textarea_proto_msgTypes,
	}.Build()
	File_industries_loosh_yutani_v1_textarea_proto = out.File
	file_industries_loosh_yutani_v1_textarea_proto_goTypes = nil
	file_industries_loosh_yutani_v1_textarea_proto_depIdxs = nil
}
