// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v5.29.3
// source: industries/loosh/yutani/v1/tree.proto

package yutani

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TreeService_SetRoot_FullMethodName     = "/industries.loosh.yutani.v1.TreeService/SetRoot"
	TreeService_AddChild_FullMethodName    = "/industries.loosh.yutani.v1.TreeService/AddChild"
	TreeService_RemoveNode_FullMethodName  = "/industries.loosh.yutani.v1.TreeService/RemoveNode"
	TreeService_SetExpanded_FullMethodName = "/industries.loosh.yutani.v1.TreeService/SetExpanded"
	TreeService_GetSelected_FullMethodName = "/industries.loosh.yutani.v1.TreeService/GetSelected"
	TreeService_SetSelected_FullMethodName = "/industries.loosh.yutani.v1.TreeService/SetSelected"
	TreeService_GetChildren_FullMethodName = "/industries.loosh.yutani.v1.TreeService/GetChildren"
)

// TreeServiceClient is the client API for TreeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// TreeService provides operations for TreeView widgets
type TreeServiceClient interface {
	// Set the root node
	SetRoot(ctx context.Context, in *SetTreeRootRequest, opts ...grpc.CallOption) (*SetTreeRootResponse, error)
	// Add a child node
	AddChild(ctx context.Context, in *AddTreeChildRequest, opts ...grpc.CallOption) (*AddTreeChildResponse, error)
	// Remove a node
	RemoveNode(ctx context.Context, in *RemoveTreeNodeRequest, opts ...grpc.CallOption) (*RemoveTreeNodeResponse, error)
	// Expand or collapse a node
	SetExpanded(ctx context.Context, in *SetExpandedRequest, opts ...grpc.CallOption) (*SetExpandedResponse, error)
	// Get the currently selected node
	GetSelected(ctx context.Context, in *GetTreeSelectedRequest, opts ...grpc.CallOption) (*GetTreeSelectedResponse, error)
	// Set the selected node
	SetSelected(ctx context.Context, in *SetTreeSelectedRequest, opts ...grpc.CallOption) (*SetTreeSelectedResponse, error)
	// Get a node's children
	GetChildren(ctx context.Context, in *GetChildrenRequest, opts ...grpc.CallOption) (*GetChildrenResponse, error)
}

type treeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTreeServiceClient(cc grpc.ClientConnInterface) TreeServiceClient {
	return &treeServiceClient{cc}
}

func (c *treeServiceClient) SetRoot(ctx context.Context, in *SetTreeRootRequest, opts ...grpc.CallOption) (*SetTreeRootResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetTreeRootResponse)
	err := c.cc.Invoke(ctx, TreeService_SetRoot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *treeServiceClient) AddChild(ctx context.Context, in *AddTreeChildRequest, opts ...grpc.CallOption) (*AddTreeChildResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddTreeChildResponse)
	err := c.cc.Invoke(ctx, TreeService_AddChild_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *treeServiceClient) RemoveNode(ctx context.Context, in *RemoveTreeNodeRequest, opts ...grpc.CallOption) (*RemoveTreeNodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveTreeNodeResponse)
	err := c.cc.Invoke(ctx, TreeService_RemoveNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *treeServiceClient) SetExpanded(ctx context.Context, in *SetExpandedRequest, opts ...grpc.CallOption) (*SetExpandedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetExpandedResponse)
	err := c.cc.Invoke(ctx, TreeService_SetExpanded_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *treeServiceClient) GetSelected(ctx context.Context, in *GetTreeSelectedRequest, opts ...grpc.CallOption) (*GetTreeSelectedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTreeSelectedResponse)
	err := c.cc.Invoke(ctx, TreeService_GetSelected_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *treeServiceClient) SetSelected(ctx context.Context, in *SetTreeSelectedRequest, opts ...grpc.CallOption) (*SetTreeSelectedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetTreeSelectedResponse)
	err := c.cc.Invoke(ctx, TreeService_SetSelected_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *treeServiceClient) GetChildren(ctx context.Context, in *GetChildrenRequest, opts ...grpc.CallOption) (*GetChildrenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetChildrenResponse)
	err := c.cc.Invoke(ctx, TreeService_GetChildren_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TreeServiceServer is the server API for TreeService service.
// All implementations must embed UnimplementedTreeServiceServer
// for forward compatibility.
//
// TreeService provides operations for TreeView widgets
type TreeServiceServer interface {
	// Set the root node
	SetRoot(context.Context, *SetTreeRootRequest) (*SetTreeRootResponse, error)
	// Add a child node
	AddChild(context.Context, *AddTreeChildRequest) (*AddTreeChildResponse, error)
	// Remove a node
	RemoveNode(context.Context, *RemoveTreeNodeRequest) (*RemoveTreeNodeResponse, error)
	// Expand or collapse a node
	SetExpanded(context.Context, *SetExpandedRequest) (*SetExpandedResponse, error)
	// Get the currently selected node
	GetSelected(context.Context, *GetTreeSelectedRequest) (*GetTreeSelectedResponse, error)
	// Set the selected node
	SetSelected(context.Context, *SetTreeSelectedRequest) (*SetTreeSelectedResponse, error)
	// Get a node's children
	GetChildren(context.Context, *GetChildrenRequest) (*GetChildrenResponse, error)
	mustEmbedUnimplementedTreeServiceServer()
}

// UnimplementedTreeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTreeServiceServer struct{}

func (UnimplementedTreeServiceServer) SetRoot(context.Context, *SetTreeRootRequest) (*SetTreeRootResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetRoot not implemented")
}
func (UnimplementedTreeServiceServer) AddChild(context.Context, *AddTreeChildRequest) (*AddTreeChildResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddChild not implemented")
}
func (UnimplementedTreeServiceServer) RemoveNode(context.Context, *RemoveTreeNodeRequest) (*RemoveTreeNodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveNode not implemented")
}
func (UnimplementedTreeServiceServer) SetExpanded(context.Context, *SetExpandedRequest) (*SetExpandedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetExpanded not implemented")
}
func (UnimplementedTreeServiceServer) GetSelected(context.Context, *GetTreeSelectedRequest) (*GetTreeSelectedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSelected not implemented")
}
func (UnimplementedTreeServiceServer) SetSelected(context.Context, *SetTreeSelectedRequest) (*SetTreeSelectedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetSelected not implemented")
}
func (UnimplementedTreeServiceServer) GetChildren(context.Context, *GetChildrenRequest) (*GetChildrenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetChildren not implemented")
}
func (UnimplementedTreeServiceServer) mustEmbedUnimplementedTreeServiceServer() {}
func (UnimplementedTreeServiceServer) testEmbeddedByValue()                     {}

// UnsafeTreeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TreeServiceServer will
// result in compilation errors.
type UnsafeTreeServiceServer interface {
	mustEmbedUnimplementedTreeServiceServer()
}

func RegisterTreeServiceServer(s grpc.ServiceRegistrar, srv TreeServiceServer) {
	// If the following call panics, it indicates UnimplementedTreeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TreeService_ServiceDesc, srv)
}

func _TreeService_SetRoot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetTreeRootRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TreeServiceServer).SetRoot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TreeService_SetRoot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TreeServiceServer).SetRoot(ctx, req.(*SetTreeRootRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TreeService_AddChild_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddTreeChildRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TreeServiceServer).AddChild(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TreeService_AddChild_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TreeServiceServer).AddChild(ctx, req.(*AddTreeChildRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TreeService_RemoveNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveTreeNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TreeServiceServer).RemoveNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TreeService_RemoveNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TreeServiceServer).RemoveNode(ctx, req.(*RemoveTreeNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TreeService_SetExpanded_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetExpandedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TreeServiceServer).SetExpanded(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TreeService_SetExpanded_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TreeServiceServer).SetExpanded(ctx, req.(*SetExpandedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TreeService_GetSelected_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTreeSelectedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TreeServiceServer).GetSelected(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TreeService_GetSelected_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TreeServiceServer).GetSelected(ctx, req.(*GetTreeSelectedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TreeService_SetSelected_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetTreeSelectedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TreeServiceServer).SetSelected(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TreeService_SetSelected_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TreeServiceServer).SetSelected(ctx, req.(*SetTreeSelectedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TreeService_GetChildren_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetChildrenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TreeServiceServer).GetChildren(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TreeService_GetChildren_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TreeServiceServer).GetChildren(ctx, req.(*GetChildrenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TreeService_ServiceDesc is the grpc.ServiceDesc for TreeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TreeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "industries.loosh.yutani.v1.TreeService",
	HandlerType: (*TreeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetRoot",
			Handler:    _TreeService_SetRoot_Handler,
		},
		{
			MethodName: "AddChild",
			Handler:    _TreeService_AddChild_Handler,
		},
		{
			MethodName: "RemoveNode",
			Handler:    _TreeService_RemoveNode_Handler,
		},
		{
			MethodName: "SetExpanded",
			Handler:    _TreeService_SetExpanded_Handler,
		},
		{
			MethodName: "GetSelected",
			Handler:    _TreeService_GetSelected_Handler,
		},
		{
			MethodName: "SetSelected",
			Handler:    _TreeService_SetSelected_Handler,
		},
		{
			MethodName: "GetChildren",
			Handler:    _TreeService_GetChildren_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "industries/loosh/yutani/v1/tree.proto",
}
