// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: industries/loosh/yutani/v1/types.proto

package yutani

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Attribute int32

const (
	Attribute_ATTR_NONE          Attribute = 0
	Attribute_ATTR_BOLD          Attribute = 1
	Attribute_ATTR_ITALIC        Attribute = 2
	Attribute_ATTR_UNDERLINE     Attribute = 3
	Attribute_ATTR_REVERSE       Attribute = 4
	Attribute_ATTR_BLINK         Attribute = 5
	Attribute_ATTR_DIM           Attribute = 6
	Attribute_ATTR_STRIKETHROUGH Attribute = 7
)

// Enum value maps for Attribute.
var (
	Attribute_name = map[int32]string{
		0: "ATTR_NONE",
		1: "ATTR_BOLD",
		2: "ATTR_ITALIC",
		3: "ATTR_UNDERLINE",
		4: "ATTR_REVERSE",
		5: "ATTR_BLINK",
		6: "ATTR_DIM",
		7: "ATTR_STRIKETHROUGH",
	}
	Attribute_value = map[string]int32{
		"ATTR_NONE":          0,
		"ATTR_BOLD":          1,
		"ATTR_ITALIC":        2,
		"ATTR_UNDERLINE":     3,
		"ATTR_REVERSE":       4,
		"ATTR_BLINK":         5,
		"ATTR_DIM":           6,
		"ATTR_STRIKETHROUGH": 7,
	}
)

func (x Attribute) Enum() *Attribute {
	p := new(Attribute)
	*p = x
	return p
}

func (x Attribute) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Attribute) Descriptor() protoreflect.EnumDescriptor {
	return file_industries_loosh_yutani_v1_types_proto_enumTypes[0].Descriptor()
}

func (Attribute) Type() protoreflect.EnumType {
	return &file_industries_loosh_yutani_v1_types_proto_enumTypes[0]
}

func (x Attribute) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Attribute.Descriptor instead.
func (Attribute) EnumDescriptor() ([]byte, []int) {
	return file_industries_loosh_yutani_v1_types_proto_rawDescGZIP(), []int{0}
}

type WidgetType int32

const (
	WidgetType_WIDGET_BOX         WidgetType = 0
	WidgetType_WIDGET_TEXT_VIEW   WidgetType = 1
	WidgetType_WIDGET_INPUT_FIELD WidgetType = 2
	WidgetType_WIDGET_TEXT_AREA   WidgetType = 3
	WidgetType_WIDGET_BUTTON      WidgetType = 4
	WidgetType_WIDGET_CHECKBOX    WidgetType = 5
	WidgetType_WIDGET_DROPDOWN    WidgetType = 6
	WidgetType_WIDGET_LIST        WidgetType = 7
	WidgetType_WIDGET_TABLE       WidgetType = 8
	WidgetType_WIDGET_TREE_VIEW   WidgetType = 9
	WidgetType_WIDGET_FORM        WidgetType = 10
	WidgetType_WIDGET_FLEX        WidgetType = 11
	WidgetType_WIDGET_GRID        WidgetType = 12
	WidgetType_WIDGET_PAGES       WidgetType = 13
	WidgetType_WIDGET_MODAL       WidgetType = 14
	WidgetType_WIDGET_IMAGE       WidgetType = 15
)

// Enum value maps for WidgetType.
var (
	WidgetType_name = map[int32]string{
		0:  "WIDGET_BOX",
		1:  "WIDGET_TEXT_VIEW",
		2:  "WIDGET_INPUT_FIELD",
		3:  "WIDGET_TEXT_AREA",
		4:  "WIDGET_BUTTON",
		5:  "WIDGET_CHECKBOX",
		6:  "WIDGET_DROPDOWN",
		7:  "WIDGET_LIST",
		8:  "WIDGET_TABLE",
		9:  "WIDGET_TREE_VIEW",
		10: "WIDGET_FORM",
		11: "WIDGET_FLEX",
		12: "WIDGET_GRID",
		13: "WIDGET_PAGES",
		14: "WIDGET_MODAL",
		15: "WIDGET_IMAGE",
	}
	WidgetType_value = map[string]int32{
		"WIDGET_BOX":         0,
		"WIDGET_TEXT_VIEW":   1,
		"WIDGET_INPUT_FIELD": 2,
		"WIDGET_TEXT_AREA":   3,
		"WIDGET_BUTTON":      4,
		"WIDGET_CHECKBOX":    5,
		"WIDGET_DROPDOWN":    6,
		"WIDGET_LIST":        7,
		"WIDGET_TABLE":       8,
		"WIDGET_TREE_VIEW":   9,
		"WIDGET_FORM":        10,
		"WIDGET_FLEX":        11,
		"WIDGET_GRID":        12,
		"WIDGET_PAGES":       13,
		"WIDGET_MODAL":       14,
		"WIDGET_IMAGE":       15,
	}
)

func (x WidgetType) Enum() *WidgetType {
	p := new(WidgetType)
	*p = x
	return p
}

func (x WidgetType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WidgetType) Descriptor() protoreflect.EnumDescriptor {
	return file_industries_loosh_yutani_v1_types_proto_enumTypes[1].Descriptor()
}

func (WidgetType) Type() protoreflect.EnumType {
	return &file_industries_loosh_yutani_v1_types_proto_enumTypes[1]
}

func (x WidgetType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WidgetType.Descriptor instead.
func (WidgetType) EnumDescriptor() ([]byte, []int) {
	return file_industries_loosh_yutani_v1_types_proto_rawDescGZIP(), []int{1}
}

type Alignment int32

const (
	Alignment_ALIGN_LEFT   Alignment = 0
	Alignment_ALIGN_CENTER Alignment = 1
	Alignment_ALIGN_RIGHT  Alignment = 2
)

// Enum value maps for Alignment.
var (
	Alignment_name = map[int32]string{
		0: "ALIGN_LEFT",
		1: "ALIGN_CENTER",
		2: "ALIGN_RIGHT",
	}
	Alignment_value = map[string]int32{
		"ALIGN_LEFT":   0,
		"ALIGN_CENTER": 1,
		"ALIGN_RIGHT":  2,
	}
)

func (x Alignment) Enum() *Alignment {
	p := new(Alignment)
	*p = x
	return p
}

func (x Alignment) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Alignment) Descriptor() protoreflect.EnumDescriptor {
	return file_industries_loosh_yutani_v1_types_proto_enumTypes[2].Descriptor()
}

func (Alignment) Type() protoreflect.EnumType {
	return &file_industries_loosh_yutani_v1_types_proto_enumTypes[2]
}

func (x Alignment) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Alignment.Descriptor instead.
func (Alignment) EnumDescriptor() ([]byte, []int) {
	return file_industries_loosh_yutani_v1_types_proto_rawDescGZIP(), []int{2}
}

type FlexDirection int32

const (
	FlexDirection_FLEX_ROW    FlexDirection = 0
	FlexDirection_FLEX_COLUMN FlexDirection = 1
)

// Enum value maps for FlexDirection.
var (
	FlexDirection_name = map[int32]string{
		0: "FLEX_ROW",
		1: "FLEX_COLUMN",
	}
	FlexDirection_value = map[string]int32{
		"FLEX_ROW":    0,
		"FLEX_COLUMN": 1,
	}
)

func (x FlexDirection) Enum() *FlexDirection {
	p := new(FlexDirection)
	*p = x
	return p
}

func (x FlexDirection) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FlexDirection) Descriptor() protoreflect.EnumDescriptor {
	return file_industries_loosh_yutani_v1_types_proto_enumTypes[3].Descriptor()
}

func (FlexDirection) Type() protoreflect.EnumType {
	return &file_industries_loosh_yutani_v1_types_proto_enumTypes[3]
}

func (x FlexDirection) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FlexDirection.Descriptor instead.
func (FlexDirection) EnumDescriptor() ([]byte, []int) {
	return file_industries_loosh_yutani_v1_types_proto_rawDescGZIP(), []int{3}
}

type Key int32

const (
	Key_KEY_RUNE      Key = 0 // Regular character (check rune field)
	Key_KEY_UP        Key = 1
	Key_KEY_DOWN      Key = 2
	Key_KEY_LEFT      Key = 3
	Key_KEY_RIGHT     Key = 4
	Key_KEY_ENTER     Key = 5
	Key_KEY_ESCAPE    Key = 6
	Key_KEY_TAB       Key = 7
	Key_KEY_BACKTAB   Key = 8
	Key_KEY_BACKSPACE Key = 9
	Key_KEY_DELETE    Key = 10
	Key_KEY_INSERT    Key = 11
	Key_KEY_HOME      Key = 12
	Key_KEY_END       Key = 13
	Key_KEY_PGUP      Key = 14
	Key_KEY_PGDN      Key = 15
	Key_KEY_F1        Key = 16
	Key_KEY_F2        Key = 17
	Key_KEY_F3        Key = 18
	Key_KEY_F4        Key = 19
	Key_KEY_F5        Key = 20
	Key_KEY_F6        Key = 21
	Key_KEY_F7        Key = 22
	Key_KEY_F8        Key = 23
	Key_KEY_F9        Key = 24
	Key_KEY_F10       Key = 25
	Key_KEY_F11       Key = 26
	Key_KEY_F12       Key = 27
)

// Enum value maps for Key.
var (
	Key_name = map[int32]string{
		0:  "KEY_RUNE",
		1:  "KEY_UP",
		2:  "KEY_DOWN",
		3:  "KEY_LEFT",
		4:  "KEY_RIGHT",
		5:  "KEY_ENTER",
		6:  "KEY_ESCAPE",
		7:  "KEY_TAB",
		8:  "KEY_BACKTAB",
		9:  "KEY_BACKSPACE",
		10: "KEY_DELETE",
		11: "KEY_INSERT",
		12: "KEY_HOME",
		13: "KEY_END",
		14: "KEY_PGUP",
		15: "KEY_PGDN",
		16: "KEY_F1",
		17: "KEY_F2",
		18: "KEY_F3",
		19: "KEY_F4",
		20: "KEY_F5",
		21: "KEY_F6",
		22: "KEY_F7",
		23: "KEY_F8",
		24: "KEY_F9",
		25: "KEY_F10",
		26: "KEY_F11",
		27: "KEY_F12",
	}
	Key_value = map[string]int32{
		"KEY_RUNE":      0,
		"KEY_UP":        1,
		"KEY_DOWN":      2,
		"KEY_LEFT":      3,
		"KEY_RIGHT":     4,
		"KEY_ENTER":     5,
		"KEY_ESCAPE":    6,
		"KEY_TAB":       7,
		"KEY_BACKTAB":   8,
		"KEY_BACKSPACE": 9,
		"KEY_DELETE":    10,
		"KEY_INSERT":    11,
		"KEY_HOME":      12,
		"KEY_END":       13,
		"KEY_PGUP":      14,
		"KEY_PGDN":      15,
		"KEY_F1":        16,
		"KEY_F2":        17,
		"KEY_F3":        18,
		"KEY_F4":        19,
		"KEY_F5":        20,
		"KEY_F6":        21,
		"KEY_F7":        22,
		"KEY_F8":        23,
		"KEY_F9":        24,
		"KEY_F10":       25,
		"KEY_F11":       26,
		"KEY_F12":       27,
	}
)

func (x Key) Enum() *Key {
	p := new(Key)
	*p = x
	return p
}

func (x Key) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Key) Descriptor() protoreflect.EnumDescriptor {
	return file_industries_loosh_yutani_v1_types_proto_enumTypes[4].Descriptor()
}

func (Key) Type() protoreflect.EnumType {
	return &file_industries_loosh_yutani_v1_types_proto_enumTypes[4]
}

func (x Key) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Key.Descriptor instead.
func (Key) EnumDescriptor() ([]byte, []int) {
	return file_industries_loosh_yutani_v1_types_proto_rawDescGZIP(), []int{4}
}

type Modifier int32

const (
	Modifier_MOD_NONE  Modifier = 0
	Modifier_MOD_SHIFT Modifier = 1
	Modifier_MOD_CTRL  Modifier = 2
	Modifier_MOD_ALT   Modifier = 3
	Modifier_MOD_META  Modifier = 4
)

// Enum value maps for Modifier.
var (
	Modifier_name = map[int32]string{
		0: "MOD_NONE",
		1: "MOD_SHIFT",
		2: "MOD_CTRL",
		3: "MOD_ALT",
		4: "MOD_META",
	}
	Modifier_value = map[string]int32{
		"MOD_NONE":  0,
		"MOD_SHIFT": 1,
		"MOD_CTRL":  2,
		"MOD_ALT":   3,
		"MOD_META":  4,
	}
)

func (x Modifier) Enum() *Modifier {
	p := new(Modifier)
	*p = x
	return p
}

func (x Modifier) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Modifier) Descriptor() protoreflect.EnumDescriptor {
	return file_industries_loosh_yutani_v1_types_proto_enumTypes[5].Descriptor()
}

func (Modifier) Type() protoreflect.EnumType {
	return &file_industries_loosh_yutani_v1_types_proto_enumTypes[5]
}

func (x Modifier) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Modifier.Descriptor instead.
func (Modifier) EnumDescriptor() ([]byte, []int) {
	return file_industries_loosh_yutani_v1_types_proto_rawDescGZIP(), []int{5}
}

type Position struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             int32                  `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Position) Reset() {
	*x = Position{}
	mi := &file_industries_loosh_yutani_v1_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Position) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Position) ProtoMessage() {}

func (x *Position) ProtoReflect() protoreflect.Message {
	mi := &file_industries_loosh_yutani_v1_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Position.ProtoReflect.Descriptor instead.
func (*Position) Descriptor() ([]byte, []int) {
	return file_industries_loosh_yutani_v1_types_proto_rawDescGZIP(), []int{0}
}

func (x *Position) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Position) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type Size struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Width         int32                  `protobuf:"varint,1,opt,name=width,proto3" json:"width,omitempty"`
	Height        int32                  `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Size) Reset() {
	*x = Size{}
	mi := &file_industries_loosh_yutani_v1_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Size) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Size) ProtoMessage() {}

func (x *Size) ProtoReflect() protoreflect.Message {
	mi := &file_industries_loosh_yutani_v1_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Size.ProtoReflect.Descriptor instead.
func (*Size) Descriptor() ([]byte, []int) {
	return file_industries_loosh_yutani_v1_types_proto_rawDescGZIP(), []int{1}
}

func (x *Size) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *Size) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

type Rect struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             int32                  `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	Width         int32                  `protobuf:"varint,3,opt,name=width,proto3" json:"width,omitempty"`
	Height        int32                  `protobuf:"varint,4,opt,name=height,proto3" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Rect) Reset() {
	*x = Rect{}
	mi := &file_industries_loosh_yutani_v1_types_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rect) ProtoMessage() {}

func (x *Rect) ProtoReflect() protoreflect.Message {
	mi := &file_industries_loosh_yutani_v1_types_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rect.ProtoReflect.Descriptor instead.
func (*Rect) Descriptor() ([]byte, []int) {
	return file_industries_loosh_yutani_v1_types_proto_rawDescGZIP(), []int{2}
}

func (x *Rect) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Rect) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Rect) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *Rect) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

type Color struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Color:
	//
	//	*Color_Name
	//	*Color_Index
	//	*Color_Rgb
	Color         isColor_Color `protobuf_oneof:"color"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Color) Reset() {
	*x = Color{}
	mi := &file_industries_loosh_yutani_v1_types_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Color) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Color) ProtoMessage() {}

func (x *Color) ProtoReflect() protoreflect.Message {
	mi := &file_industries_loosh_yutani_v1_types_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Color.ProtoReflect.Descriptor instead.
func (*Color) Descriptor() ([]byte, []int) {
	return file_industries_loosh_yutani_v1_types_proto_rawDescGZIP(), []int{3}
}

func (x *Color) GetColor() isColor_Color {
	if x != nil {
		return x.Color
	}
	return nil
}

func (x *Color) GetName() string {
	if x != nil {
		if x, ok := x.Color.(*Color_Name); ok {
			return x.Name
		}
	}
	return ""
}

func (x *Color) GetIndex() int32 {
	if x != nil {
		if x, ok := x.Color.(*Color_Index); ok {
			return x.Index
		}
	}
	return 0
}

func (x *Color) GetRgb() *RGB {
	if x != nil {
		if x, ok := x.Color.(*Color_Rgb); ok {
			return x.Rgb
		}
	}
	return nil
}

type isColor_Color interface {
	isColor_Color()
}

type Color_Name struct {
	Name string `protobuf:"bytes,1,opt,name=name,proto3,oneof"` // Named color: "red", "blue", etc.
}

type Color_Index struct {
	Index int32 `protobuf:"varint,2,opt,name=index,proto3,oneof"` // 256-color palette index
}

type Color_Rgb struct {
	Rgb *RGB `protobuf:"bytes,3,opt,name=rgb,proto3,oneof"` // True color
}

func (*Color_Name) isColor_Color() {}

func (*Color_Index) isColor_Color() {}

func (*Color_Rgb) isColor_Color() {}

type RGB struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	R             int32                  `protobuf:"varint,1,opt,name=r,proto3" json:"r,omitempty"`
	G             int32                  `protobuf:"varint,2,opt,name=g,proto3" json:"g,omitempty"`
	B             int32                  `protobuf:"varint,3,opt,name=b,proto3" json:"b,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RGB) Reset() {
	*x = RGB{}
	mi := &file_industries_loosh_yutani_v1_types_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RGB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RGB) ProtoMessage() {}

func (x *RGB) ProtoReflect() protoreflect.Message {
	mi := &file_industries_loosh_yutani_v1_types_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RGB.ProtoReflect.Descriptor instead.
func (*RGB) Descriptor() ([]byte, []int) {
	return file_industries_loosh_yutani_v1_types_proto_rawDescGZIP(), []int{4}
}

func (x *RGB) GetR() int32 {
	if x != nil {
		return x.R
	}
	return 0
}

func (x *RGB) GetG() int32 {
	if x != nil {
		return x.G
	}
	return 0
}

func (x *RGB) GetB() int32 {
	if x != nil {
		return x.B
	}
	return 0
}

type Style struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Foreground    *Color                 `protobuf:"bytes,1,opt,name=foreground,proto3" json:"foreground,omitempty"`
	Background    *Color                 `protobuf:"bytes,2,opt,name=background,proto3" json:"background,omitempty"`
	Attributes    []Attribute            `protobuf:"varint,3,rep,packed,name=attributes,proto3,enum=industries.loosh.yutani.v1.Attribute" json:"attributes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Style) Reset() {
	*x = Style{}
	mi := &file_industries_loosh_yutani_v1_types_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Style) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Style) ProtoMessage() {}

func (x *Style) ProtoReflect() protoreflect.Message {
	mi := &file_industries_loosh_yutani_v1_types_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Style.ProtoReflect.Descriptor instead.
func (*Style) Descriptor() ([]byte, []int) {
	return file_industries_loosh_yutani_v1_types_proto_rawDescGZIP(), []int{5}
}

func (x *Style) GetForeground() *Color {
	if x != nil {
		return x.Foreground
	}
	return nil
}

func (x *Style) GetBackground() *Color {
	if x != nil {
		return x.Background
	}
	return nil
}

func (x *Style) GetAttributes() []Attribute {
	if x != nil {
		return x.Attributes
	}
	return nil
}

type Cell struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rune          string                 `protobuf:"bytes,1,opt,name=rune,proto3" json:"rune,omitempty"` // UTF-8 character
	Style         *Style                 `protobuf:"bytes,2,opt,name=style,proto3" json:"style,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cell) Reset() {
	*x = Cell{}
	mi := &file_industries_loosh_yutani_v1_types_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cell) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cell) ProtoMessage() {}

func (x *Cell) ProtoReflect() protoreflect.Message {
	mi := &file_industries_loosh_yutani_v1_types_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cell.ProtoReflect.Descriptor instead.
func (*Cell) Descriptor() ([]byte, []int) {
	return file_industries_loosh_yutani_v1_types_proto_rawDescGZIP(), []int{6}
}

func (x *Cell) GetRune() string {
	if x != nil {
		return x.Rune
	}
	return ""
}

func (x *Cell) GetStyle() *Style {
	if x != nil {
		return x.Style
	}
	return nil
}

type SessionId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionId) Reset() {
	*x = SessionId{}
	mi := &file_industries_loosh_yutani_v1_types_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionId) ProtoMessage() {}

func (x *SessionId) ProtoReflect() protoreflect.Message {
	mi := &file_industries_loosh_yutani_v1_types_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionId.ProtoReflect.Descriptor instead.
func (*SessionId) Descriptor() ([]byte, []int) {
	return file_industries_loosh_yutani_v1_types_proto_rawDescGZIP(), []int{7}
}

func (x *SessionId) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type WidgetId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WidgetId) Reset() {
	*x = WidgetId{}
	mi := &file_industries_loosh_yutani_v1_types_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WidgetId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WidgetId) ProtoMessage() {}

func (x *WidgetId) ProtoReflect() protoreflect.Message {
	mi := &file_industries_loosh_yutani_v1_types_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WidgetId.ProtoReflect.Descriptor instead.
func (*WidgetId) Descriptor() ([]byte, []int) {
	return file_industries_loosh_yutani_v1_types_proto_rawDescGZIP(), []int{8}
}

func (x *WidgetId) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type Padding struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Top           int32                  `protobuf:"varint,1,opt,name=top,proto3" json:"top,omitempty"`
	Bottom        int32                  `protobuf:"varint,2,opt,name=bottom,proto3" json:"bottom,omitempty"`
	Left          int32                  `protobuf:"varint,3,opt,name=left,proto3" json:"left,omitempty"`
	Right         int32                  `protobuf:"varint,4,opt,name=right,proto3" json:"right,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Padding) Reset() {
	*x = Padding{}
	mi := &file_industries_loosh_yutani_v1_types_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Padding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Padding) ProtoMessage() {}

func (x *Padding) ProtoReflect() protoreflect.Message {
	mi := &file_industries_loosh_yutani_v1_types_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Padding.ProtoReflect.Descriptor instead.
func (*Padding) Descriptor() ([]byte, []int) {
	return file_industries_loosh_yutani_v1_types_proto_rawDescGZIP(), []int{9}
}

func (x *Padding) GetTop() int32 {
	if x != nil {
		return x.Top
	}
	return 0
}

func (x *Padding) GetBottom() int32 {
	if x != nil {
		return x.Bottom
	}
	return 0
}

func (x *Padding) GetLeft() int32 {
	if x != nil {
		return x.Left
	}
	return 0
}

func (x *Padding) GetRight() int32 {
	if x != nil {
		return x.Right
	}
	return 0
}

type WidgetProperties struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Common properties (from Box)
	Rect            *Rect      `protobuf:"bytes,1,opt,name=rect,proto3,oneof" json:"rect,omitempty"`
	Border          *bool      `protobuf:"varint,2,opt,name=border,proto3,oneof" json:"border,omitempty"`
	Title           *string    `protobuf:"bytes,3,opt,name=title,proto3,oneof" json:"title,omitempty"`
	TitleAlign      *Alignment `protobuf:"varint,4,opt,name=title_align,json=titleAlign,proto3,enum=industries.loosh.yutani.v1.Alignment,oneof" json:"title_align,omitempty"`
	BackgroundColor *Color     `protobuf:"bytes,5,opt,name=background_color,json=backgroundColor,proto3,oneof" json:"background_color,omitempty"`
	BorderColor     *Color     `protobuf:"bytes,6,opt,name=border_color,json=borderColor,proto3,oneof" json:"border_color,omitempty"`
	TitleColor      *Color     `protobuf:"bytes,7,opt,name=title_color,json=titleColor,proto3,oneof" json:"title_color,omitempty"`
	Padding         *Padding   `protobuf:"bytes,8,opt,name=padding,proto3,oneof" json:"padding,omitempty"`
	// Type-specific properties
	//
	// Types that are valid to be assigned to TypeProperties:
	//
	//	*WidgetProperties_TextView
	//	*WidgetProperties_InputField
	//	*WidgetProperties_Button
	//	*WidgetProperties_Checkbox
	//	*WidgetProperties_List
	//	*WidgetProperties_Table
	//	*WidgetProperties_Flex
	//	*WidgetProperties_Grid
	//	*WidgetProperties_Tree
	//	*WidgetProperties_Form
	//	*WidgetProperties_Pages
	TypeProperties isWidgetProperties_TypeProperties `protobuf_oneof:"type_properties"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *WidgetProperties) Reset() {
	*x = WidgetProperties{}
	mi := &file_industries_loosh_yutani_v1_types_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WidgetProperties) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WidgetProperties) ProtoMessage() {}

func (x *WidgetProperties) ProtoReflect() protoreflect.Message {
	mi := &file_industries_loosh_yutani_v1_types_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WidgetProperties.ProtoReflect.Descriptor instead.
func (*WidgetProperties) Descriptor() ([]byte, []int) {
	return file_industries_loosh_yutani_v1_types_proto_rawDescGZIP(), []int{10}
}

func (x *WidgetProperties) GetRect() *Rect {
	if x != nil {
		return x.Rect
	}
	return nil
}

func (x *WidgetProperties) GetBorder() bool {
	if x != nil && x.Border != nil {
		return *x.Border
	}
	return false
}

func (x *WidgetProperties) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *WidgetProperties) GetTitleAlign() Alignment {
	if x != nil && x.TitleAlign != nil {
		return *x.TitleAlign
	}
	return Alignment_ALIGN_LEFT
}

func (x *WidgetProperties) GetBackgroundColor() *Color {
	if x != nil {
		return x.BackgroundColor
	}
	return nil
}

func (x *WidgetProperties) GetBorderColor() *Color {
	if x != nil {
		return x.BorderColor
	}
	return nil
}

func (x *WidgetProperties) GetTitleColor() *Color {
	if x != nil {
		return x.TitleColor
	}
	return nil
}

func (x *WidgetProperties) GetPadding() *Padding {
	if x != nil {
		return x.Padding
	}
	return nil
}

func (x *WidgetProperties) GetTypeProperties() isWidgetProperties_TypeProperties {
	if x != nil {
		return x.TypeProperties
	}
	return nil
}

func (x *WidgetProperties) GetTextView() *TextViewProperties {
	if x != nil {
		if x, ok := x.TypeProperties.(*WidgetProperties_TextView); ok {
			return x.TextView
		}
	}
	return nil
}

func (x *WidgetProperties) GetInputField() *InputFieldProperties {
	if x != nil {
		if x, ok := x.TypeProperties.(*WidgetProperties_InputField); ok {
			return x.InputField
		}
	}
	return nil
}

func (x *WidgetProperties) GetButton() *ButtonProperties {
	if x != nil {
		if x, ok := x.TypeProperties.(*WidgetProperties_Button); ok {
			return x.Button
		}
	}
	return nil
}

func (x *WidgetProperties) GetCheckbox() *CheckboxProperties {
	if x != nil {
		if x, ok := x.TypeProperties.(*WidgetProperties_Checkbox); ok {
			return x.Checkbox
		}
	}
	return nil
}

func (x *WidgetProperties) GetList() *ListProperties {
	if x != nil {
		if x, ok := x.TypeProperties.(*WidgetProperties_List); ok {
			return x.List
		}
	}
	return nil
}

func (x *WidgetProperties) GetTable() *TableProperties {
	if x != nil {
		if x, ok := x.TypeProperties.(*WidgetProperties_Table); ok {
			return x.Table
		}
	}
	return nil
}

func (x *WidgetProperties) GetFlex() *FlexProperties {
	if x != nil {
		if x, ok := x.TypeProperties.(*WidgetProperties_Flex); ok {
			return x.Flex
		}
	}
	return nil
}

func (x *WidgetProperties) GetGrid() *GridProperties {
	if x != nil {
		if x, ok := x.TypeProperties.(*WidgetProperties_Grid); ok {
			return x.Grid
		}
	}
	return nil
}

func (x *WidgetProperties) GetTree() *TreeProperties {
	if x != nil {
		if x, ok := x.TypeProperties.(*WidgetProperties_Tree); ok {
			return x.Tree
		}
	}
	return nil
}

func (x *WidgetProperties) GetForm() *FormProperties {
	if x != nil {
		if x, ok := x.TypeProperties.(*WidgetProperties_Form); ok {
			return x.Form
		}
	}
	return nil
}

func (x *WidgetProperties) GetPages() *PagesProperties {
	if x != nil {
		if x, ok := x.TypeProperties.(*WidgetProperties_Pages); ok {
			return x.Pages
		}
	}
	return nil
}

type isWidgetProperties_TypeProperties interface {
	isWidgetProperties_TypeProperties()
}

type WidgetProperties_TextView struct {
	TextView *TextViewProperties `protobuf:"bytes,20,opt,name=text_view,json=textView,proto3,oneof"`
}

type WidgetProperties_InputField struct {
	InputField *InputFieldProperties `protobuf:"bytes,21,opt,name=input_field,json=inputField,proto3,oneof"`
}

type WidgetProperties_Button struct {
	Button *ButtonProperties `protobuf:"bytes,22,opt,name=button,proto3,oneof"`
}

type WidgetProperties_Checkbox struct {
	Checkbox *CheckboxProperties `protobuf:"bytes,23,opt,name=checkbox,proto3,oneof"`
}

type WidgetProperties_List struct {
	List *ListProperties `protobuf:"bytes,24,opt,name=list,proto3,oneof"`
}

type WidgetProperties_Table struct {
	Table *TableProperties `protobuf:"bytes,25,opt,name=table,proto3,oneof"`
}

type WidgetProperties_Flex struct {
	Flex *FlexProperties `protobuf:"bytes,26,opt,name=flex,proto3,oneof"`
}

type WidgetProperties_Grid struct {
	Grid *GridProperties `protobuf:"bytes,27,opt,name=grid,proto3,oneof"`
}

type WidgetProperties_Tree struct {
	Tree *TreeProperties `protobuf:"bytes,28,opt,name=tree,proto3,oneof"`
}

type WidgetProperties_Form struct {
	Form *FormProperties `protobuf:"bytes,29,opt,name=form,proto3,oneof"`
}

type WidgetProperties_Pages struct {
	Pages *PagesProperties `protobuf:"bytes,30,opt,name=pages,proto3,oneof"`
}

func (*WidgetProperties_TextView) isWidgetProperties_TypeProperties() {}

func (*WidgetProperties_InputField) isWidgetProperties_TypeProperties() {}

func (*WidgetProperties_Button) isWidgetProperties_TypeProperties() {}

func (*WidgetProperties_Checkbox) isWidgetProperties_TypeProperties() {}

func (*WidgetProperties_List) isWidgetProperties_TypeProperties() {}

func (*WidgetProperties_Table) isWidgetProperties_TypeProperties() {}

func (*WidgetProperties_Flex) isWidgetProperties_TypeProperties() {}

func (*WidgetProperties_Grid) isWidgetProperties_TypeProperties() {}

func (*WidgetProperties_Tree) isWidgetProperties_TypeProperties() {}

func (*WidgetProperties_Form) isWidgetProperties_TypeProperties() {}

func (*WidgetProperties_Pages) isWidgetProperties_TypeProperties() {}

type TextViewProperties struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          *string                `protobuf:"bytes,1,opt,name=text,proto3,oneof" json:"text,omitempty"`
	DynamicColors *bool                  `protobuf:"varint,2,opt,name=dynamic_colors,json=dynamicColors,proto3,oneof" json:"dynamic_colors,omitempty"`
	WordWrap      *bool                  `protobuf:"varint,3,opt,name=word_wrap,json=wordWrap,proto3,oneof" json:"word_wrap,omitempty"`
	Scrollable    *bool                  `protobuf:"varint,4,opt,name=scrollable,proto3,oneof" json:"scrollable,omitempty"`
	MaxLines      *int32                 `protobuf:"varint,5,opt,name=max_lines,json=maxLines,proto3,oneof" json:"max_lines,omitempty"`
	TextColor     *Color                 `protobuf:"bytes,6,opt,name=text_color,json=textColor,proto3,oneof" json:"text_color,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextViewProperties) Reset() {
	*x = TextViewProperties{}
	mi := &file_industries_loosh_yutani_v1_types_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextViewProperties) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextViewProperties) ProtoMessage() {}

func (x *TextViewProperties) ProtoReflect() protoreflect.Message {
	mi := &file_industries_loosh_yutani_v1_types_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextViewProperties.ProtoReflect.Descriptor instead.
func (*TextViewProperties) Descriptor() ([]byte, []int) {
	return file_industries_loosh_yutani_v1_types_proto_rawDescGZIP(), []int{11}
}

func (x *TextViewProperties) GetText() string {
	if x != nil && x.Text != nil {
		return *x.Text
	}
	return ""
}

func (x *TextViewProperties) GetDynamicColors() bool {
	if x != nil && x.DynamicColors != nil {
		return *x.DynamicColors
	}
	return false
}

func (x *TextViewProperties) GetWordWrap() bool {
	if x != nil && x.WordWrap != nil {
		return *x.WordWrap
	}
	return false
}

func (x *TextViewProperties) GetScrollable() bool {
	if x != nil && x.Scrollable != nil {
		return *x.Scrollable
	}
	return false
}

func (x *TextViewProperties) GetMaxLines() int32 {
	if x != nil && x.MaxLines != nil {
		return *x.MaxLines
	}
	return 0
}

func (x *TextViewProperties) GetTextColor() *Color {
	if x != nil {
		return x.TextColor
	}
	return nil
}

type InputFieldProperties struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Label                *string                `protobuf:"bytes,1,opt,name=label,proto3,oneof" json:"label,omitempty"`
	Placeholder          *string                `protobuf:"bytes,2,opt,name=placeholder,proto3,oneof" json:"placeholder,omitempty"`
	Text                 *string                `protobuf:"bytes,3,opt,name=text,proto3,oneof" json:"text,omitempty"`
	FieldWidth           *int32                 `protobuf:"varint,4,opt,name=field_width,json=fieldWidth,proto3,oneof" json:"field_width,omitempty"`
	Masked               *bool                  `protobuf:"varint,5,opt,name=masked,proto3,oneof" json:"masked,omitempty"`
	MaskCharacter        *string                `protobuf:"bytes,6,opt,name=mask_character,json=maskCharacter,proto3,oneof" json:"mask_character,omitempty"`
	LabelColor           *Color                 `protobuf:"bytes,7,opt,name=label_color,json=labelColor,proto3,oneof" json:"label_color,omitempty"`
	FieldTextColor       *Color                 `protobuf:"bytes,8,opt,name=field_text_color,json=fieldTextColor,proto3,oneof" json:"field_text_color,omitempty"`
	FieldBackgroundColor *Color                 `protobuf:"bytes,9,opt,name=field_background_color,json=fieldBackgroundColor,proto3,oneof" json:"field_background_color,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *InputFieldProperties) Reset() {
	*x = InputFieldProperties{}
	mi := &file_industries_loosh_yutani_v1_types_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InputFieldProperties) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InputFieldProperties) ProtoMessage() {}

func (x *InputFieldProperties) ProtoReflect() protoreflect.Message {
	mi := &file_industries_loosh_yutani_v1_types_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InputFieldProperties.ProtoReflect.Descriptor instead.
func (*InputFieldProperties) Descriptor() ([]byte, []int) {
	return file_industries_loosh_yutani_v1_types_proto_rawDescGZIP(), []int{12}
}

func (x *InputFieldProperties) GetLabel() string {
	if x != nil && x.Label != nil {
		return *x.Label
	}
	return ""
}

func (x *InputFieldProperties) GetPlaceholder() string {
	if x != nil && x.Placeholder != nil {
		return *x.Placeholder
	}
	return ""
}

func (x *InputFieldProperties) GetText() string {
	if x != nil && x.Text != nil {
		return *x.Text
	}
	return ""
}

func (x *InputFieldProperties) GetFieldWidth() int32 {
	if x != nil && x.FieldWidth != nil {
		return *x.FieldWidth
	}
	return 0
}

func (x *InputFieldProperties) GetMasked() bool {
	if x != nil && x.Masked != nil {
		return *x.Masked
	}
	return false
}

func (x *InputFieldProperties) GetMaskCharacter() string {
	if x != nil && x.MaskCharacter != nil {
		return *x.MaskCharacter
	}
	return ""
}

func (x *InputFieldProperties) GetLabelColor() *Color {
	if x != nil {
		return x.LabelColor
	}
	return nil
}

func (x *InputFieldProperties) GetFieldTextColor() *Color {
	if x != nil {
		return x.FieldTextColor
	}
	return nil
}

func (x *InputFieldProperties) GetFieldBackgroundColor() *Color {
	if x != nil {
		return x.FieldBackgroundColor
	}
	return nil
}

type ButtonProperties struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Label           *string                `protobuf:"bytes,1,opt,name=label,proto3,oneof" json:"label,omitempty"`
	LabelColor      *Color                 `protobuf:"bytes,2,opt,name=label_color,json=labelColor,proto3,oneof" json:"label_color,omitempty"`
	BackgroundColor *Color                 `protobuf:"bytes,3,opt,name=background_color,json=backgroundColor,proto3,oneof" json:"background_color,omitempty"`
	ActivatedColor  *Color                 `protobuf:"bytes,4,opt,name=activated_color,json=activatedColor,proto3,oneof" json:"activated_color,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ButtonProperties) Reset() {
	*x = ButtonProperties{}
	mi := &file_industries_loosh_yutani_v1_types_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ButtonProperties) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ButtonProperties) ProtoMessage() {}

func (x *ButtonProperties) ProtoReflect() protoreflect.Message {
	mi := &file_industries_loosh_yutani_v1_types_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ButtonProperties.ProtoReflect.Descriptor instead.
func (*ButtonProperties) Descriptor() ([]byte, []int) {
	return file_industries_loosh_yutani_v1_types_proto_rawDescGZIP(), []int{13}
}

func (x *ButtonProperties) GetLabel() string {
	if x != nil && x.Label != nil {
		return *x.Label
	}
	return ""
}

func (x *ButtonProperties) GetLabelColor() *Color {
	if x != nil {
		return x.LabelColor
	}
	return nil
}

func (x *ButtonProperties) GetBackgroundColor() *Color {
	if x != nil {
		return x.BackgroundColor
	}
	return nil
}

func (x *ButtonProperties) GetActivatedColor() *Color {
	if x != nil {
		return x.ActivatedColor
	}
	return nil
}

type CheckboxProperties struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Label         *string                `protobuf:"bytes,1,opt,name=label,proto3,oneof" json:"label,omitempty"`
	Checked       *bool                  `protobuf:"varint,2,opt,name=checked,proto3,oneof" json:"checked,omitempty"`
	LabelColor    *Color                 `protobuf:"bytes,3,opt,name=label_color,json=labelColor,proto3,oneof" json:"label_color,omitempty"`
	CheckedColor  *Color                 `protobuf:"bytes,4,opt,name=checked_color,json=checkedColor,proto3,oneof" json:"checked_color,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckboxProperties) Reset() {
	*x = CheckboxProperties{}
	mi := &file_industries_loosh_yutani_v1_types_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckboxProperties) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckboxProperties) ProtoMessage() {}

func (x *CheckboxProperties) ProtoReflect() protoreflect.Message {
	mi := &file_industries_loosh_yutani_v1_types_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckboxProperties.ProtoReflect.Descriptor instead.
func (*CheckboxProperties) Descriptor() ([]byte, []int) {
	return file_industries_loosh_yutani_v1_types_proto_rawDescGZIP(), []int{14}
}

func (x *CheckboxProperties) GetLabel() string {
	if x != nil && x.Label != nil {
		return *x.Label
	}
	return ""
}

func (x *CheckboxProperties) GetChecked() bool {
	if x != nil && x.Checked != nil {
		return *x.Checked
	}
	return false
}

func (x *CheckboxProperties) GetLabelColor() *Color {
	if x != nil {
		return x.LabelColor
	}
	return nil
}

func (x *CheckboxProperties) GetCheckedColor() *Color {
	if x != nil {
		return x.CheckedColor
	}
	return nil
}

type ListProperties struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	ShowSecondaryText       *bool                  `protobuf:"varint,1,opt,name=show_secondary_text,json=showSecondaryText,proto3,oneof" json:"show_secondary_text,omitempty"`
	MainTextColor           *Color                 `protobuf:"bytes,2,opt,name=main_text_color,json=mainTextColor,proto3,oneof" json:"main_text_color,omitempty"`
	SecondaryTextColor      *Color                 `protobuf:"bytes,3,opt,name=secondary_text_color,json=secondaryTextColor,proto3,oneof" json:"secondary_text_color,omitempty"`
	SelectedTextColor       *Color                 `protobuf:"bytes,4,opt,name=selected_text_color,json=selectedTextColor,proto3,oneof" json:"selected_text_color,omitempty"`
	SelectedBackgroundColor *Color                 `protobuf:"bytes,5,opt,name=selected_background_color,json=selectedBackgroundColor,proto3,oneof" json:"selected_background_color,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *ListProperties) Reset() {
	*x = ListProperties{}
	mi := &file_industries_loosh_yutani_v1_types_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProperties) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProperties) ProtoMessage() {}

func (x *ListProperties) ProtoReflect() protoreflect.Message {
	mi := &file_industries_loosh_yutani_v1_types_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProperties.ProtoReflect.Descriptor instead.
func (*ListProperties) Descriptor() ([]byte, []int) {
	return file_industries_loosh_yutani_v1_types_proto_rawDescGZIP(), []int{15}
}

func (x *ListProperties) GetShowSecondaryText() bool {
	if x != nil && x.ShowSecondaryText != nil {
		return *x.ShowSecondaryText
	}
	return false
}

func (x *ListProperties) GetMainTextColor() *Color {
	if x != nil {
		return x.MainTextColor
	}
	return nil
}

func (x *ListProperties) GetSecondaryTextColor() *Color {
	if x != nil {
		return x.SecondaryTextColor
	}
	return nil
}

func (x *ListProperties) GetSelectedTextColor() *Color {
	if x != nil {
		return x.SelectedTextColor
	}
	return nil
}

func (x *ListProperties) GetSelectedBackgroundColor() *Color {
	if x != nil {
		return x.SelectedBackgroundColor
	}
	return nil
}

type TableProperties struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Borders       *bool                  `protobuf:"varint,1,opt,name=borders,proto3,oneof" json:"borders,omitempty"`
	FixedColumns  *bool                  `protobuf:"varint,2,opt,name=fixed_columns,json=fixedColumns,proto3,oneof" json:"fixed_columns,omitempty"`
	Selectable    *bool                  `protobuf:"varint,3,opt,name=selectable,proto3,oneof" json:"selectable,omitempty"`
	BordersColor  *Color                 `protobuf:"bytes,4,opt,name=borders_color,json=bordersColor,proto3,oneof" json:"borders_color,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TableProperties) Reset() {
	*x = TableProperties{}
	mi := &file_industries_loosh_yutani_v1_types_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TableProperties) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableProperties) ProtoMessage() {}

func (x *TableProperties) ProtoReflect() protoreflect.Message {
	mi := &file_industries_loosh_yutani_v1_types_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableProperties.ProtoReflect.Descriptor instead.
func (*TableProperties) Descriptor() ([]byte, []int) {
	return file_industries_loosh_yutani_v1_types_proto_rawDescGZIP(), []int{16}
}

func (x *TableProperties) GetBorders() bool {
	if x != nil && x.Borders != nil {
		return *x.Borders
	}
	return false
}

func (x *TableProperties) GetFixedColumns() bool {
	if x != nil && x.FixedColumns != nil {
		return *x.FixedColumns
	}
	return false
}

func (x *TableProperties) GetSelectable() bool {
	if x != nil && x.Selectable != nil {
		return *x.Selectable
	}
	return false
}

func (x *TableProperties) GetBordersColor() *Color {
	if x != nil {
		return x.BordersColor
	}
	return nil
}

type FlexProperties struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Direction     *FlexDirection         `protobuf:"varint,1,opt,name=direction,proto3,enum=industries.loosh.yutani.v1.FlexDirection,oneof" json:"direction,omitempty"`
	FullScreen    *bool                  `protobuf:"varint,2,opt,name=full_screen,json=fullScreen,proto3,oneof" json:"full_screen,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlexProperties) Reset() {
	*x = FlexProperties{}
	mi := &file_industries_loosh_yutani_v1_types_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlexProperties) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlexProperties) ProtoMessage() {}

func (x *FlexProperties) ProtoReflect() protoreflect.Message {
	mi := &file_industries_loosh_yutani_v1_types_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlexProperties.ProtoReflect.Descriptor instead.
func (*FlexProperties) Descriptor() ([]byte, []int) {
	return file_industries_loosh_yutani_v1_types_proto_rawDescGZIP(), []int{17}
}

func (x *FlexProperties) GetDirection() FlexDirection {
	if x != nil && x.Direction != nil {
		return *x.Direction
	}
	return FlexDirection_FLEX_ROW
}

func (x *FlexProperties) GetFullScreen() bool {
	if x != nil && x.FullScreen != nil {
		return *x.FullScreen
	}
	return false
}

type GridProperties struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rows          *int32                 `protobuf:"varint,1,opt,name=rows,proto3,oneof" json:"rows,omitempty"`
	Columns       *int32                 `protobuf:"varint,2,opt,name=columns,proto3,oneof" json:"columns,omitempty"`
	MinWidth      *int32                 `protobuf:"varint,3,opt,name=min_width,json=minWidth,proto3,oneof" json:"min_width,omitempty"`
	MinHeight     *int32                 `protobuf:"varint,4,opt,name=min_height,json=minHeight,proto3,oneof" json:"min_height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GridProperties) Reset() {
	*x = GridProperties{}
	mi := &file_industries_loosh_yutani_v1_types_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GridProperties) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GridProperties) ProtoMessage() {}

func (x *GridProperties) ProtoReflect() protoreflect.Message {
	mi := &file_industries_loosh_yutani_v1_types_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GridProperties.ProtoReflect.Descriptor instead.
func (*GridProperties) Descriptor() ([]byte, []int) {
	return file_industries_loosh_yutani_v1_types_proto_rawDescGZIP(), []int{18}
}

func (x *GridProperties) GetRows() int32 {
	if x != nil && x.Rows != nil {
		return *x.Rows
	}
	return 0
}

func (x *GridProperties) GetColumns() int32 {
	if x != nil && x.Columns != nil {
		return *x.Columns
	}
	return 0
}

func (x *GridProperties) GetMinWidth() int32 {
	if x != nil && x.MinWidth != nil {
		return *x.MinWidth
	}
	return 0
}

func (x *GridProperties) GetMinHeight() int32 {
	if x != nil && x.MinHeight != nil {
		return *x.MinHeight
	}
	return 0
}

type TreeProperties struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	NodeTextColor           *Color                 `protobuf:"bytes,1,opt,name=node_text_color,json=nodeTextColor,proto3,oneof" json:"node_text_color,omitempty"`
	SelectedTextColor       *Color                 `protobuf:"bytes,2,opt,name=selected_text_color,json=selectedTextColor,proto3,oneof" json:"selected_text_color,omitempty"`
	SelectedBackgroundColor *Color                 `protobuf:"bytes,3,opt,name=selected_background_color,json=selectedBackgroundColor,proto3,oneof" json:"selected_background_color,omitempty"`
	TopLevelPrefix          *string                `protobuf:"bytes,4,opt,name=top_level_prefix,json=topLevelPrefix,proto3,oneof" json:"top_level_prefix,omitempty"`
	ShowGraphics            *bool                  `protobuf:"varint,5,opt,name=show_graphics,json=showGraphics,proto3,oneof" json:"show_graphics,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *TreeProperties) Reset() {
	*x = TreeProperties{}
	mi := &file_industries_loosh_yutani_v1_types_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TreeProperties) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TreeProperties) ProtoMessage() {}

func (x *TreeProperties) ProtoReflect() protoreflect.Message {
	mi := &file_industries_loosh_yutani_v1_types_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TreeProperties.ProtoReflect.Descriptor instead.
func (*TreeProperties) Descriptor() ([]byte, []int) {
	return file_industries_loosh_yutani_v1_types_proto_rawDescGZIP(), []int{19}
}

func (x *TreeProperties) GetNodeTextColor() *Color {
	if x != nil {
		return x.NodeTextColor
	}
	return nil
}

func (x *TreeProperties) GetSelectedTextColor() *Color {
	if x != nil {
		return x.SelectedTextColor
	}
	return nil
}

func (x *TreeProperties) GetSelectedBackgroundColor() *Color {
	if x != nil {
		return x.SelectedBackgroundColor
	}
	return nil
}

func (x *TreeProperties) GetTopLevelPrefix() string {
	if x != nil && x.TopLevelPrefix != nil {
		return *x.TopLevelPrefix
	}
	return ""
}

func (x *TreeProperties) GetShowGraphics() bool {
	if x != nil && x.ShowGraphics != nil {
		return *x.ShowGraphics
	}
	return false
}

type FormProperties struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	LabelWidth            *int32                 `protobuf:"varint,1,opt,name=label_width,json=labelWidth,proto3,oneof" json:"label_width,omitempty"`
	FieldWidth            *int32                 `protobuf:"varint,2,opt,name=field_width,json=fieldWidth,proto3,oneof" json:"field_width,omitempty"`
	LabelColor            *Color                 `protobuf:"bytes,3,opt,name=label_color,json=labelColor,proto3,oneof" json:"label_color,omitempty"`
	FieldTextColor        *Color                 `protobuf:"bytes,4,opt,name=field_text_color,json=fieldTextColor,proto3,oneof" json:"field_text_color,omitempty"`
	FieldBackgroundColor  *Color                 `protobuf:"bytes,5,opt,name=field_background_color,json=fieldBackgroundColor,proto3,oneof" json:"field_background_color,omitempty"`
	ButtonBackgroundColor *Color                 `protobuf:"bytes,6,opt,name=button_background_color,json=buttonBackgroundColor,proto3,oneof" json:"button_background_color,omitempty"`
	ButtonTextColor       *Color                 `protobuf:"bytes,7,opt,name=button_text_color,json=buttonTextColor,proto3,oneof" json:"button_text_color,omitempty"`
	Horizontal            *bool                  `protobuf:"varint,8,opt,name=horizontal,proto3,oneof" json:"horizontal,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *FormProperties) Reset() {
	*x = FormProperties{}
	mi := &file_industries_loosh_yutani_v1_types_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FormProperties) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FormProperties) ProtoMessage() {}

func (x *FormProperties) ProtoReflect() protoreflect.Message {
	mi := &file_industries_loosh_yutani_v1_types_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FormProperties.ProtoReflect.Descriptor instead.
func (*FormProperties) Descriptor() ([]byte, []int) {
	return file_industries_loosh_yutani_v1_types_proto_rawDescGZIP(), []int{20}
}

func (x *FormProperties) GetLabelWidth() int32 {
	if x != nil && x.LabelWidth != nil {
		return *x.LabelWidth
	}
	return 0
}

func (x *FormProperties) GetFieldWidth() int32 {
	if x != nil && x.FieldWidth != nil {
		return *x.FieldWidth
	}
	return 0
}

func (x *FormProperties) GetLabelColor() *Color {
	if x != nil {
		return x.LabelColor
	}
	return nil
}

func (x *FormProperties) GetFieldTextColor() *Color {
	if x != nil {
		return x.FieldTextColor
	}
	return nil
}

func (x *FormProperties) GetFieldBackgroundColor() *Color {
	if x != nil {
		return x.FieldBackgroundColor
	}
	return nil
}

func (x *FormProperties) GetButtonBackgroundColor() *Color {
	if x != nil {
		return x.ButtonBackgroundColor
	}
	return nil
}

func (x *FormProperties) GetButtonTextColor() *Color {
	if x != nil {
		return x.ButtonTextColor
	}
	return nil
}

func (x *FormProperties) GetHorizontal() bool {
	if x != nil && x.Horizontal != nil {
		return *x.Horizontal
	}
	return false
}

type PagesProperties struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShowPageNames *bool                  `protobuf:"varint,1,opt,name=show_page_names,json=showPageNames,proto3,oneof" json:"show_page_names,omitempty"`
	PageNameColor *Color                 `protobuf:"bytes,2,opt,name=page_name_color,json=pageNameColor,proto3,oneof" json:"page_name_color,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PagesProperties) Reset() {
	*x = PagesProperties{}
	mi := &file_industries_loosh_yutani_v1_types_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PagesProperties) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PagesProperties) ProtoMessage() {}

func (x *PagesProperties) ProtoReflect() protoreflect.Message {
	mi := &file_industries_loosh_yutani_v1_types_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PagesProperties.ProtoReflect.Descriptor instead.
func (*PagesProperties) Descriptor() ([]byte, []int) {
	return file_industries_loosh_yutani_v1_types_proto_rawDescGZIP(), []int{21}
}

func (x *PagesProperties) GetShowPageNames() bool {
	if x != nil && x.ShowPageNames != nil {
		return *x.ShowPageNames
	}
	return false
}

func (x *PagesProperties) GetPageNameColor() *Color {
	if x != nil {
		return x.PageNameColor
	}
	return nil
}

var File_industries_loosh_yutani_v1_types_proto protoreflect.FileDescriptor

const file_industries_loosh_yutani_v1_types_proto_rawDesc = "" +
	"\n" +
	"&industries/loosh/yutani/v1/types.proto\x12\x1aindustries.loosh.yutani.v1\"&\n" +
	"\bPosition\x12\f\n" +
	"\x01x\x18\x01 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x05R\x01y\"4\n" +
	"\x04Size\x12\x14\n" +
	"\x05width\x18\x01 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x02 \x01(\x05R\x06height\"P\n" +
	"\x04Rect\x12\f\n" +
	"\x01x\x18\x01 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x05R\x01y\x12\x14\n" +
	"\x05width\x18\x03 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x04 \x01(\x05R\x06height\"s\n" +
	"\x05Color\x12\x14\n" +
	"\x04name\x18\x01 \x01(\tH\x00R\x04name\x12\x16\n" +
	"\x05index\x18\x02 \x01(\x05H\x00R\x05index\x123\n" +
	"\x03rgb\x18\x03 \x01(\v2\x1f.industries.loosh.yutani.v1.RGBH\x00R\x03rgbB\a\n" +
	"\x05color\"/\n" +
	"\x03RGB\x12\f\n" +
	"\x01r\x18\x01 \x01(\x05R\x01r\x12\f\n" +
	"\x01g\x18\x02 \x01(\x05R\x01g\x12\f\n" +
	"\x01b\x18\x03 \x01(\x05R\x01b\"\xd4\x01\n" +
	"\x05Style\x12A\n" +
	"\n" +
	"foreground\x18\x01 \x01(\v2!.industries.loosh.yutani.v1.ColorR\n" +
	"foreground\x12A\n" +
	"\n" +
	"background\x18\x02 \x01(\v2!.industries.loosh.yutani.v1.ColorR\n" +
	"background\x12E\n" +
	"\n" +
	"attributes\x18\x03 \x03(\x0e2%.industries.loosh.yutani.v1.AttributeR\n" +
	"attributes\"S\n" +
	"\x04Cell\x12\x12\n" +
	"\x04rune\x18\x01 \x01(\tR\x04rune\x127\n" +
	"\x05style\x18\x02 \x01(\v2!.industries.loosh.yutani.v1.StyleR\x05style\"\x1b\n" +
	"\tSessionId\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x1a\n" +
	"\bWidgetId\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"]\n" +
	"\aPadding\x12\x10\n" +
	"\x03top\x18\x01 \x01(\x05R\x03top\x12\x16\n" +
	"\x06bottom\x18\x02 \x01(\x05R\x06bottom\x12\x12\n" +
	"\x04left\x18\x03 \x01(\x05R\x04left\x12\x14\n" +
	"\x05right\x18\x04 \x01(\x05R\x05right\"\x8e\v\n" +
	"\x10WidgetProperties\x129\n" +
	"\x04rect\x18\x01 \x01(\v2 .industries.loosh.yutani.v1.RectH\x01R\x04rect\x88\x01\x01\x12\x1b\n" +
	"\x06border\x18\x02 \x01(\bH\x02R\x06border\x88\x01\x01\x12\x19\n" +
	"\x05title\x18\x03 \x01(\tH\x03R\x05title\x88\x01\x01\x12K\n" +
	"\vtitle_align\x18\x04 \x01(\x0e2%.industries.loosh.yutani.v1.AlignmentH\x04R\n" +
	"titleAlign\x88\x01\x01\x12Q\n" +
	"\x10background_color\x18\x05 \x01(\v2!.industries.loosh.yutani.v1.ColorH\x05R\x0fbackgroundColor\x88\x01\x01\x12I\n" +
	"\fborder_color\x18\x06 \x01(\v2!.industries.loosh.yutani.v1.ColorH\x06R\vborderColor\x88\x01\x01\x12G\n" +
	"\vtitle_color\x18\a \x01(\v2!.industries.loosh.yutani.v1.ColorH\aR\n" +
	"titleColor\x88\x01\x01\x12B\n" +
	"\apadding\x18\b \x01(\v2#.industries.loosh.yutani.v1.PaddingH\bR\apadding\x88\x01\x01\x12M\n" +
	"\ttext_view\x18\x14 \x01(\v2..industries.loosh.yutani.v1.TextViewPropertiesH\x00R\btextView\x12S\n" +
	"\vinput_field\x18\x15 \x01(\v20.industries.loosh.yutani.v1.InputFieldPropertiesH\x00R\n" +
	"inputField\x12F\n" +
	"\x06button\x18\x16 \x01(\v2,.industries.loosh.yutani.v1.ButtonPropertiesH\x00R\x06button\x12L\n" +
	"\bcheckbox\x18\x17 \x01(\v2..industries.loosh.yutani.v1.CheckboxPropertiesH\x00R\bcheckbox\x12@\n" +
	"\x04list\x18\x18 \x01(\v2*.industries.loosh.yutani.v1.ListPropertiesH\x00R\x04list\x12C\n" +
	"\x05table\x18\x19 \x01(\v2+.industries.loosh.yutani.v1.TablePropertiesH\x00R\x05table\x12@\n" +
	"\x04flex\x18\x1a \x01(\v2*.industries.loosh.yutani.v1.FlexPropertiesH\x00R\x04flex\x12@\n" +
	"\x04grid\x18\x1b \x01(\v2*.industries.loosh.yutani.v1.GridPropertiesH\x00R\x04grid\x12@\n" +
	"\x04tree\x18\x1c \x01(\v2*.industries.loosh.yutani.v1.TreePropertiesH\x00R\x04tree\x12@\n" +
	"\x04form\x18\x1d \x01(\v2*.industries.loosh.yutani.v1.FormPropertiesH\x00R\x04form\x12C\n" +
	"\x05pages\x18\x1e \x01(\v2+.industries.loosh.yutani.v1.PagesPropertiesH\x00R\x05pagesB\x11\n" +
	"\x0ftype_propertiesB\a\n" +
	"\x05_rectB\t\n" +
	"\a_borderB\b\n" +
	"\x06_titleB\x0e\n" +
	"\f_title_alignB\x13\n" +
	"\x11_background_colorB\x0f\n" +
	"\r_border_colorB\x0e\n" +
	"\f_title_colorB\n" +
	"\n" +
	"\b_padding\"\xdf\x02\n" +
	"\x12TextViewProperties\x12\x17\n" +
	"\x04text\x18\x01 \x01(\tH\x00R\x04text\x88\x01\x01\x12*\n" +
	"\x0edynamic_colors\x18\x02 \x01(\bH\x01R\rdynamicColors\x88\x01\x01\x12 \n" +
	"\tword_wrap\x18\x03 \x01(\bH\x02R\bwordWrap\x88\x01\x01\x12#\n" +
	"\n" +
	"scrollable\x18\x04 \x01(\bH\x03R\n" +
	"scrollable\x88\x01\x01\x12 \n" +
	"\tmax_lines\x18\x05 \x01(\x05H\x04R\bmaxLines\x88\x01\x01\x12E\n" +
	"\n" +
	"text_color\x18\x06 \x01(\v2!.industries.loosh.yutani.v1.ColorH\x05R\ttextColor\x88\x01\x01B\a\n" +
	"\x05_textB\x11\n" +
	"\x0f_dynamic_colorsB\f\n" +
	"\n" +
	"_word_wrapB\r\n" +
	"\v_scrollableB\f\n" +
	"\n" +
	"_max_linesB\r\n" +
	"\v_text_color\"\xea\x04\n" +
	"\x14InputFieldProperties\x12\x19\n" +
	"\x05label\x18\x01 \x01(\tH\x00R\x05label\x88\x01\x01\x12%\n" +
	"\vplaceholder\x18\x02 \x01(\tH\x01R\vplaceholder\x88\x01\x01\x12\x17\n" +
	"\x04text\x18\x03 \x01(\tH\x02R\x04text\x88\x01\x01\x12$\n" +
	"\vfield_width\x18\x04 \x01(\x05H\x03R\n" +
	"fieldWidth\x88\x01\x01\x12\x1b\n" +
	"\x06masked\x18\x05 \x01(\bH\x04R\x06masked\x88\x01\x01\x12*\n" +
	"\x0emask_character\x18\x06 \x01(\tH\x05R\rmaskCharacter\x88\x01\x01\x12G\n" +
	"\vlabel_color\x18\a \x01(\v2!.industries.loosh.yutani.v1.ColorH\x06R\n" +
	"labelColor\x88\x01\x01\x12P\n" +
	"\x10field_text_color\x18\b \x01(\v2!.industries.loosh.yutani.v1.ColorH\aR\x0efieldTextColor\x88\x01\x01\x12\\\n" +
	"\x16field_background_color\x18\t \x01(\v2!.industries.loosh.yutani.v1.ColorH\bR\x14fieldBackgroundColor\x88\x01\x01B\b\n" +
	"\x06_labelB\x0e\n" +
	"\f_placeholderB\a\n" +
	"\x05_textB\x0e\n" +
	"\f_field_widthB\t\n" +
	"\a_maskedB\x11\n" +
	"\x0f_mask_characterB\x0e\n" +
	"\f_label_colorB\x13\n" +
	"\x11_field_text_colorB\x19\n" +
	"\x17_field_background_color\"\xdd\x02\n" +
	"\x10ButtonProperties\x12\x19\n" +
	"\x05label\x18\x01 \x01(\tH\x00R\x05label\x88\x01\x01\x12G\n" +
	"\vlabel_color\x18\x02 \x01(\v2!.industries.loosh.yutani.v1.ColorH\x01R\n" +
	"labelColor\x88\x01\x01\x12Q\n" +
	"\x10background_color\x18\x03 \x01(\v2!.industries.loosh.yutani.v1.ColorH\x02R\x0fbackgroundColor\x88\x01\x01\x12O\n" +
	"\x0factivated_color\x18\x04 \x01(\v2!.industries.loosh.yutani.v1.ColorH\x03R\x0eactivatedColor\x88\x01\x01B\b\n" +
	"\x06_labelB\x0e\n" +
	"\f_label_colorB\x13\n" +
	"\x11_background_colorB\x12\n" +
	"\x10_activated_color\"\x9c\x02\n" +
	"\x12CheckboxProperties\x12\x19\n" +
	"\x05label\x18\x01 \x01(\tH\x00R\x05label\x88\x01\x01\x12\x1d\n" +
	"\achecked\x18\x02 \x01(\bH\x01R\achecked\x88\x01\x01\x12G\n" +
	"\vlabel_color\x18\x03 \x01(\v2!.industries.loosh.yutani.v1.ColorH\x02R\n" +
	"labelColor\x88\x01\x01\x12K\n" +
	"\rchecked_color\x18\x04 \x01(\v2!.industries.loosh.yutani.v1.ColorH\x03R\fcheckedColor\x88\x01\x01B\b\n" +
	"\x06_labelB\n" +
	"\n" +
	"\b_checkedB\x0e\n" +
	"\f_label_colorB\x10\n" +
	"\x0e_checked_color\"\xa6\x04\n" +
	"\x0eListProperties\x123\n" +
	"\x13show_secondary_text\x18\x01 \x01(\bH\x00R\x11showSecondaryText\x88\x01\x01\x12N\n" +
	"\x0fmain_text_color\x18\x02 \x01(\v2!.industries.loosh.yutani.v1.ColorH\x01R\rmainTextColor\x88\x01\x01\x12X\n" +
	"\x14secondary_text_color\x18\x03 \x01(\v2!.industries.loosh.yutani.v1.ColorH\x02R\x12secondaryTextColor\x88\x01\x01\x12V\n" +
	"\x13selected_text_color\x18\x04 \x01(\v2!.industries.loosh.yutani.v1.ColorH\x03R\x11selectedTextColor\x88\x01\x01\x12b\n" +
	"\x19selected_background_color\x18\x05 \x01(\v2!.industries.loosh.yutani.v1.ColorH\x04R\x17selectedBackgroundColor\x88\x01\x01B\x16\n" +
	"\x14_show_secondary_textB\x12\n" +
	"\x10_main_text_colorB\x17\n" +
	"\x15_secondary_text_colorB\x16\n" +
	"\x14_selected_text_colorB\x1c\n" +
	"\x1a_selected_background_color\"\x8b\x02\n" +
	"\x0fTableProperties\x12\x1d\n" +
	"\aborders\x18\x01 \x01(\bH\x00R\aborders\x88\x01\x01\x12(\n" +
	"\rfixed_columns\x18\x02 \x01(\bH\x01R\ffixedColumns\x88\x01\x01\x12#\n" +
	"\n" +
	"selectable\x18\x03 \x01(\bH\x02R\n" +
	"selectable\x88\x01\x01\x12K\n" +
	"\rborders_color\x18\x04 \x01(\v2!.industries.loosh.yutani.v1.ColorH\x03R\fbordersColor\x88\x01\x01B\n" +
	"\n" +
	"\b_bordersB\x10\n" +
	"\x0e_fixed_columnsB\r\n" +
	"\v_selectableB\x10\n" +
	"\x0e_borders_color\"\xa2\x01\n" +
	"\x0eFlexProperties\x12L\n" +
	"\tdirection\x18\x01 \x01(\x0e2).industries.loosh.yutani.v1.FlexDirectionH\x00R\tdirection\x88\x01\x01\x12$\n" +
	"\vfull_screen\x18\x02 \x01(\bH\x01R\n" +
	"fullScreen\x88\x01\x01B\f\n" +
	"\n" +
	"_directionB\x0e\n" +
	"\f_full_screen\"\xc0\x01\n" +
	"\x0eGridProperties\x12\x17\n" +
	"\x04rows\x18\x01 \x01(\x05H\x00R\x04rows\x88\x01\x01\x12\x1d\n" +
	"\acolumns\x18\x02 \x01(\x05H\x01R\acolumns\x88\x01\x01\x12 \n" +
	"\tmin_width\x18\x03 \x01(\x05H\x02R\bminWidth\x88\x01\x01\x12\"\n" +
	"\n" +
	"min_height\x18\x04 \x01(\x05H\x03R\tminHeight\x88\x01\x01B\a\n" +
	"\x05_rowsB\n" +
	"\n" +
	"\b_columnsB\f\n" +
	"\n" +
	"_min_widthB\r\n" +
	"\v_min_height\"\xe6\x03\n" +
	"\x0eTreeProperties\x12N\n" +
	"\x0fnode_text_color\x18\x01 \x01(\v2!.industries.loosh.yutani.v1.ColorH\x00R\rnodeTextColor\x88\x01\x01\x12V\n" +
	"\x13selected_text_color\x18\x02 \x01(\v2!.industries.loosh.yutani.v1.ColorH\x01R\x11selectedTextColor\x88\x01\x01\x12b\n" +
	"\x19selected_background_color\x18\x03 \x01(\v2!.industries.loosh.yutani.v1.ColorH\x02R\x17selectedBackgroundColor\x88\x01\x01\x12-\n" +
	"\x10top_level_prefix\x18\x04 \x01(\tH\x03R\x0etopLevelPrefix\x88\x01\x01\x12(\n" +
	"\rshow_graphics\x18\x05 \x01(\bH\x04R\fshowGraphics\x88\x01\x01B\x12\n" +
	"\x10_node_text_colorB\x16\n" +
	"\x14_selected_text_colorB\x1c\n" +
	"\x1a_selected_background_colorB\x13\n" +
	"\x11_top_level_prefixB\x10\n" +
	"\x0e_show_graphics\"\xcf\x05\n" +
	"\x0eFormProperties\x12$\n" +
	"\vlabel_width\x18\x01 \x01(\x05H\x00R\n" +
	"labelWidth\x88\x01\x01\x12$\n" +
	"\vfield_width\x18\x02 \x01(\x05H\x01R\n" +
	"fieldWidth\x88\x01\x01\x12G\n" +
	"\vlabel_color\x18\x03 \x01(\v2!.industries.loosh.yutani.v1.ColorH\x02R\n" +
	"labelColor\x88\x01\x01\x12P\n" +
	"\x10field_text_color\x18\x04 \x01(\v2!.industries.loosh.yutani.v1.ColorH\x03R\x0efieldTextColor\x88\x01\x01\x12\\\n" +
	"\x16field_background_color\x18\x05 \x01(\v2!.industries.loosh.yutani.v1.ColorH\x04R\x14fieldBackgroundColor\x88\x01\x01\x12^\n" +
	"\x17button_background_color\x18\x06 \x01(\v2!.industries.loosh.yutani.v1.ColorH\x05R\x15buttonBackgroundColor\x88\x01\x01\x12R\n" +
	"\x11button_text_color\x18\a \x01(\v2!.industries.loosh.yutani.v1.ColorH\x06R\x0fbuttonTextColor\x88\x01\x01\x12#\n" +
	"\n" +
	"horizontal\x18\b \x01(\bH\aR\n" +
	"horizontal\x88\x01\x01B\x0e\n" +
	"\f_label_widthB\x0e\n" +
	"\f_field_widthB\x0e\n" +
	"\f_label_colorB\x13\n" +
	"\x11_field_text_colorB\x19\n" +
	"\x17_field_background_colorB\x1a\n" +
	"\x18_button_background_colorB\x14\n" +
	"\x12_button_text_colorB\r\n" +
	"\v_horizontal\"\xb6\x01\n" +
	"\x0fPagesProperties\x12+\n" +
	"\x0fshow_page_names\x18\x01 \x01(\bH\x00R\rshowPageNames\x88\x01\x01\x12N\n" +
	"\x0fpage_name_color\x18\x02 \x01(\v2!.industries.loosh.yutani.v1.ColorH\x01R\rpageNameColor\x88\x01\x01B\x12\n" +
	"\x10_show_page_namesB\x12\n" +
	"\x10_page_name_color*\x96\x01\n" +
	"\tAttribute\x12\r\n" +
	"\tATTR_NONE\x10\x00\x12\r\n" +
	"\tATTR_BOLD\x10\x01\x12\x0f\n" +
	"\vATTR_ITALIC\x10\x02\x12\x12\n" +
	"\x0eATTR_UNDERLINE\x10\x03\x12\x10\n" +
	"\fATTR_REVERSE\x10\x04\x12\x0e\n" +
	"\n" +
	"ATTR_BLINK\x10\x05\x12\f\n" +
	"\bATTR_DIM\x10\x06\x12\x16\n" +
	"\x12ATTR_STRIKETHROUGH\x10\a*\xbf\x02\n" +
	"\n" +
	"WidgetType\x12\x0e\n" +
	"\n" +
	"WIDGET_BOX\x10\x00\x12\x14\n" +
	"\x10WIDGET_TEXT_VIEW\x10\x01\x12\x16\n" +
	"\x12WIDGET_INPUT_FIELD\x10\x02\x12\x14\n" +
	"\x10WIDGET_TEXT_AREA\x10\x03\x12\x11\n" +
	"\rWIDGET_BUTTON\x10\x04\x12\x13\n" +
	"\x0fWIDGET_CHECKBOX\x10\x05\x12\x13\n" +
	"\x0fWIDGET_DROPDOWN\x10\x06\x12\x0f\n" +
	"\vWIDGET_LIST\x10\a\x12\x10\n" +
	"\fWIDGET_TABLE\x10\b\x12\x14\n" +
	"\x10WIDGET_TREE_VIEW\x10\t\x12\x0f\n" +
	"\vWIDGET_FORM\x10\n" +
	"\x12\x0f\n" +
	"\vWIDGET_FLEX\x10\v\x12\x0f\n" +
	"\vWIDGET_GRID\x10\f\x12\x10\n" +
	"\fWIDGET_PAGES\x10\r\x12\x10\n" +
	"\fWIDGET_MODAL\x10\x0e\x12\x10\n" +
	"\fWIDGET_IMAGE\x10\x0f*>\n" +
	"\tAlignment\x12\x0e\n" +
	"\n" +
	"ALIGN_LEFT\x10\x00\x12\x10\n" +
	"\fALIGN_CENTER\x10\x01\x12\x0f\n" +
	"\vALIGN_RIGHT\x10\x02*.\n" +
	"\rFlexDirection\x12\f\n" +
	"\bFLEX_ROW\x10\x00\x12\x0f\n" +
	"\vFLEX_COLUMN\x10\x01*\x84\x03\n" +
	"\x03Key\x12\f\n" +
	"\bKEY_RUNE\x10\x00\x12\n" +
	"\n" +
	"\x06KEY_UP\x10\x01\x12\f\n" +
	"\bKEY_DOWN\x10\x02\x12\f\n" +
	"\bKEY_LEFT\x10\x03\x12\r\n" +
	"\tKEY_RIGHT\x10\x04\x12\r\n" +
	"\tKEY_ENTER\x10\x05\x12\x0e\n" +
	"\n" +
	"KEY_ESCAPE\x10\x06\x12\v\n" +
	"\aKEY_TAB\x10\a\x12\x0f\n" +
	"\vKEY_BACKTAB\x10\b\x12\x11\n" +
	"\rKEY_BACKSPACE\x10\t\x12\x0e\n" +
	"\n" +
	"KEY_DELETE\x10\n" +
	"\x12\x0e\n" +
	"\n" +
	"KEY_INSERT\x10\v\x12\f\n" +
	"\bKEY_HOME\x10\f\x12\v\n" +
	"\aKEY_END\x10\r\x12\f\n" +
	"\bKEY_PGUP\x10\x0e\x12\f\n" +
	"\bKEY_PGDN\x10\x0f\x12\n" +
	"\n" +
	"\x06KEY_F1\x10\x10\x12\n" +
	"\n" +
	"\x06KEY_F2\x10\x11\x12\n" +
	"\n" +
	"\x06KEY_F3\x10\x12\x12\n" +
	"\n" +
	"\x06KEY_F4\x10\x13\x12\n" +
	"\n" +
	"\x06KEY_F5\x10\x14\x12\n" +
	"\n" +
	"\x06KEY_F6\x10\x15\x12\n" +
	"\n" +
	"\x06KEY_F7\x10\x16\x12\n" +
	"\n" +
	"\x06KEY_F8\x10\x17\x12\n" +
	"\n" +
	"\x06KEY_F9\x10\x18\x12\v\n" +
	"\aKEY_F10\x10\x19\x12\v\n" +
	"\aKEY_F11\x10\x1a\x12\v\n" +
	"\aKEY_F12\x10\x1b*P\n" +
	"\bModifier\x12\f\n" +
	"\bMOD_NONE\x10\x00\x12\r\n" +
	"\tMOD_SHIFT\x10\x01\x12\f\n" +
	"\bMOD_CTRL\x10\x02\x12\v\n" +
	"\aMOD_ALT\x10\x03\x12\f\n" +
	"\bMOD_META\x10\x04B*Z(github.com/chazu/yutani/pkg/proto/yutanib\x06proto3"

var (
	file_industries_loosh_yutani_v1_types_proto_rawDescOnce sync.Once
	file_industries_loosh_yutani_v1_types_proto_rawDescData []byte
)

func file_industries_loosh_yutani_v1_types_proto_rawDescGZIP() []byte {
	file_industries_loosh_yutani_v1_types_proto_rawDescOnce.Do(func() {
		file_industries_loosh_yutani_v1_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_industries_loosh_yutani_v1_types_proto_rawDesc), len(file_industries_loosh_yutani_v1_types_proto_rawDesc)))
	})
	return file_industries_loosh_yutani_v1_types_proto_rawDescData
}

var file_industries_loosh_yutani_v1_types_proto_enumTypes = make([]protoimpl.EnumInfo, 6)
var file_industries_loosh_yutani_v1_types_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_industries_loosh_yutani_v1_types_proto_goTypes = []any{
	(Attribute)(0),               // 0: industries.loosh.yutani.v1.Attribute
	(WidgetType)(0),              // 1: industries.loosh.yutani.v1.WidgetType
	(Alignment)(0),               // 2: industries.loosh.yutani.v1.Alignment
	(FlexDirection)(0),           // 3: industries.loosh.yutani.v1.FlexDirection
	(Key)(0),                     // 4: industries.loosh.yutani.v1.Key
	(Modifier)(0),                // 5: industries.loosh.yutani.v1.Modifier
	(*Position)(nil),             // 6: industries.loosh.yutani.v1.Position
	(*Size)(nil),                 // 7: industries.loosh.yutani.v1.Size
	(*Rect)(nil),                 // 8: industries.loosh.yutani.v1.Rect
	(*Color)(nil),                // 9: industries.loosh.yutani.v1.Color
	(*RGB)(nil),                  // 10: industries.loosh.yutani.v1.RGB
	(*Style)(nil),                // 11: industries.loosh.yutani.v1.Style
	(*Cell)(nil),                 // 12: industries.loosh.yutani.v1.Cell
	(*SessionId)(nil),            // 13: industries.loosh.yutani.v1.SessionId
	(*WidgetId)(nil),             // 14: industries.loosh.yutani.v1.WidgetId
	(*Padding)(nil),              // 15: industries.loosh.yutani.v1.Padding
	(*WidgetProperties)(nil),     // 16: industries.loosh.yutani.v1.WidgetProperties
	(*TextViewProperties)(nil),   // 17: industries.loosh.yutani.v1.TextViewProperties
	(*InputFieldProperties)(nil), // 18: industries.loosh.yutani.v1.InputFieldProperties
	(*ButtonProperties)(nil),     // 19: industries.loosh.yutani.v1.ButtonProperties
	(*CheckboxProperties)(nil),   // 20: industries.loosh.yutani.v1.CheckboxProperties
	(*ListProperties)(nil),       // 21: industries.loosh.yutani.v1.ListProperties
	(*TableProperties)(nil),      // 22: industries.loosh.yutani.v1.TableProperties
	(*FlexProperties)(nil),       // 23: industries.loosh.yutani.v1.FlexProperties
	(*GridProperties)(nil),       // 24: industries.loosh.yutani.v1.GridProperties
	(*TreeProperties)(nil),       // 25: industries.loosh.yutani.v1.TreeProperties
	(*FormProperties)(nil),       // 26: industries.loosh.yutani.v1.FormProperties
	(*PagesProperties)(nil),      // 27: industries.loosh.yutani.v1.PagesProperties
}
var file_industries_loosh_yutani_v1_types_proto_depIdxs = []int32{
	10, // 0: industries.loosh.yutani.v1.Color.rgb:type_name -> industries.loosh.yutani.v1.RGB
	9,  // 1: industries.loosh.yutani.v1.Style.foreground:type_name -> industries.loosh.yutani.v1.Color
	9,  // 2: industries.loosh.yutani.v1.Style.background:type_name -> industries.loosh.yutani.v1.Color
	0,  // 3: industries.loosh.yutani.v1.Style.attributes:type_name -> industries.loosh.yutani.v1.Attribute
	11, // 4: industries.loosh.yutani.v1.Cell.style:type_name -> industries.loosh.yutani.v1.Style
	8,  // 5: industries.loosh.yutani.v1.WidgetProperties.rect:type_name -> industries.loosh.yutani.v1.Rect
	2,  // 6: industries.loosh.yutani.v1.WidgetProperties.title_align:type_name -> industries.loosh.yutani.v1.Alignment
	9,  // 7: industries.loosh.yutani.v1.WidgetProperties.background_color:type_name -> industries.loosh.yutani.v1.Color
	9,  // 8: industries.loosh.yutani.v1.WidgetProperties.border_color:type_name -> industries.loosh.yutani.v1.Color
	9,  // 9: industries.loosh.yutani.v1.WidgetProperties.title_color:type_name -> industries.loosh.yutani.v1.Color
	15, // 10: industries.loosh.yutani.v1.WidgetProperties.padding:type_name -> industries.loosh.yutani.v1.Padding
	17, // 11: industries.loosh.yutani.v1.WidgetProperties.text_view:type_name -> industries.loosh.yutani.v1.TextViewProperties
	18, // 12: industries.loosh.yutani.v1.WidgetProperties.input_field:type_name -> industries.loosh.yutani.v1.InputFieldProperties
	19, // 13: industries.loosh.yutani.v1.WidgetProperties.button:type_name -> industries.loosh.yutani.v1.ButtonProperties
	20, // 14: industries.loosh.yutani.v1.WidgetProperties.checkbox:type_name -> industries.loosh.yutani.v1.CheckboxProperties
	21, // 15: industries.loosh.yutani.v1.WidgetProperties.list:type_name -> industries.loosh.yutani.v1.ListProperties
	22, // 16: industries.loosh.yutani.v1.WidgetProperties.table:type_name -> industries.loosh.yutani.v1.TableProperties
	23, // 17: industries.loosh.yutani.v1.WidgetProperties.flex:type_name -> industries.loosh.yutani.v1.FlexProperties
	24, // 18: industries.loosh.yutani.v1.WidgetProperties.grid:type_name -> industries.loosh.yutani.v1.GridProperties
	25, // 19: industries.loosh.yutani.v1.WidgetProperties.tree:type_name -> industries.loosh.yutani.v1.TreeProperties
	26, // 20: industries.loosh.yutani.v1.WidgetProperties.form:type_name -> industries.loosh.yutani.v1.FormProperties
	27, // 21: industries.loosh.yutani.v1.WidgetProperties.pages:type_name -> industries.loosh.yutani.v1.PagesProperties
	9,  // 22: industries.loosh.yutani.v1.TextViewProperties.text_color:type_name -> industries.loosh.yutani.v1.Color
	9,  // 23: industries.loosh.yutani.v1.InputFieldProperties.label_color:type_name -> industries.loosh.yutani.v1.Color
	9,  // 24: industries.loosh.yutani.v1.InputFieldProperties.field_text_color:type_name -> industries.loosh.yutani.v1.Color
	9,  // 25: industries.loosh.yutani.v1.InputFieldProperties.field_background_color:type_name -> industries.loosh.yutani.v1.Color
	9,  // 26: industries.loosh.yutani.v1.ButtonProperties.label_color:type_name -> industries.loosh.yutani.v1.Color
	9,  // 27: industries.loosh.yutani.v1.ButtonProperties.background_color:type_name -> industries.loosh.yutani.v1.Color
	9,  // 28: industries.loosh.yutani.v1.ButtonProperties.activated_color:type_name -> industries.loosh.yutani.v1.Color
	9,  // 29: industries.loosh.yutani.v1.CheckboxProperties.label_color:type_name -> industries.loosh.yutani.v1.Color
	9,  // 30: industries.loosh.yutani.v1.CheckboxProperties.checked_color:type_name -> industries.loosh.yutani.v1.Color
	9,  // 31: industries.loosh.yutani.v1.ListProperties.main_text_color:type_name -> industries.loosh.yutani.v1.Color
	9,  // 32: industries.loosh.yutani.v1.ListProperties.secondary_text_color:type_name -> industries.loosh.yutani.v1.Color
	9,  // 33: industries.loosh.yutani.v1.ListProperties.selected_text_color:type_name -> industries.loosh.yutani.v1.Color
	9,  // 34: industries.loosh.yutani.v1.ListProperties.selected_background_color:type_name -> industries.loosh.yutani.v1.Color
	9,  // 35: industries.loosh.yutani.v1.TableProperties.borders_color:type_name -> industries.loosh.yutani.v1.Color
	3,  // 36: industries.loosh.yutani.v1.FlexProperties.direction:type_name -> industries.loosh.yutani.v1.FlexDirection
	9,  // 37: industries.loosh.yutani.v1.TreeProperties.node_text_color:type_name -> industries.loosh.yutani.v1.Color
	9,  // 38: industries.loosh.yutani.v1.TreeProperties.selected_text_color:type_name -> industries.loosh.yutani.v1.Color
	9,  // 39: industries.loosh.yutani.v1.TreeProperties.selected_background_color:type_name -> industries.loosh.yutani.v1.Color
	9,  // 40: industries.loosh.yutani.v1.FormProperties.label_color:type_name -> industries.loosh.yutani.v1.Color
	9,  // 41: industries.loosh.yutani.v1.FormProperties.field_text_color:type_name -> industries.loosh.yutani.v1.Color
	9,  // 42: industries.loosh.yutani.v1.FormProperties.field_background_color:type_name -> industries.loosh.yutani.v1.Color
	9,  // 43: industries.loosh.yutani.v1.FormProperties.button_background_color:type_name -> industries.loosh.yutani.v1.Color
	9,  // 44: industries.loosh.yutani.v1.FormProperties.button_text_color:type_name -> industries.loosh.yutani.v1.Color
	9,  // 45: industries.loosh.yutani.v1.PagesProperties.page_name_color:type_name -> industries.loosh.yutani.v1.Color
	46, // [46:46] is the sub-list for method output_type
	46, // [46:46] is the sub-list for method input_type
	46, // [46:46] is the sub-list for extension type_name
	46, // [46:46] is the sub-list for extension extendee
	0,  // [0:46] is the sub-list for field type_name
}

func init() { file_industries_loosh_yutani_v1_types_proto_init() }
func file_industries_loosh_yutani_v1_types_proto_init() {
	if File_industries_loosh_yutani_v1_types_proto != nil {
		return
	}
	file_industries_loosh_yutani_v1_types_proto_msgTypes[3].OneofWrappers = []any{
		(*Color_Name)(nil),
		(*Color_Index)(nil),
		(*Color_Rgb)(nil),
	}
	file_industries_loosh_yutani_v1_types_proto_msgTypes[10].OneofWrappers = []any{
		(*WidgetProperties_TextView)(nil),
		(*WidgetProperties_InputField)(nil),
		(*WidgetProperties_Button)(nil),
		(*WidgetProperties_Checkbox)(nil),
		(*WidgetProperties_List)(nil),
		(*WidgetProperties_Table)(nil),
		(*WidgetProperties_Flex)(nil),
		(*WidgetProperties_Grid)(nil),
		(*WidgetProperties_Tree)(nil),
		(*WidgetProperties_Form)(nil),
		(*WidgetProperties_Pages)(nil),
	}
	file_industries_loosh_yutani_v1_types_proto_msgTypes[11].OneofWrappers = []any{}
	file_industries_loosh_yutani_v1_types_proto_msgTypes[12].OneofWrappers = []any{}
	file_industries_loosh_yutani_v1_types_proto_msgTypes[13].OneofWrappers = []any{}
	file_industries_loosh_yutani_v1_types_proto_msgTypes[14].OneofWrappers = []any{}
	file_industries_loosh_yutani_v1_types_proto_msgTypes[15].OneofWrappers = []any{}
	file_industries_loosh_yutani_v1_types_proto_msgTypes[16].OneofWrappers = []any{}
	file_industries_loosh_yutani_v1_types_proto_msgTypes[17].OneofWrappers = []any{}
	file_industries_loosh_yutani_v1_types_proto_msgTypes[18].OneofWrappers = []any{}
	file_industries_loosh_yutani_v1_types_proto_msgTypes[19].OneofWrappers = []any{}
	file_industries_loosh_yutani_v1_types_proto_msgTypes[20].OneofWrappers = []any{}
	file_industries_loosh_yutani_v1_types_proto_msgTypes[21].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_industries_loosh_yutani_v1_types_proto_rawDesc), len(file_industries_loosh_yutani_v1_types_proto_rawDesc)),
			NumEnums:      6,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_industries_loosh_yutani_v1_types_proto_goTypes,
		DependencyIndexes: file_industries_loosh_yutani_v1_types_proto_depIdxs,
		EnumInfos:         file_industries_loosh_yutani_v1_types_proto_enumTypes,
		MessageInfos:      file_industries_loosh_yutani_v1_types_proto_msgTypes,
	}.Build()
	File_industries_loosh_yutani_v1_types_proto = out.File
	file_industries_loosh_yutani_v1_types_proto_goTypes = nil
	file_industries_loosh_yutani_v1_types_proto_depIdxs = nil
}
