// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: industries/loosh/yutani/v1/widget.proto

package yutani

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateWidgetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     *SessionId             `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Type          WidgetType             `protobuf:"varint,2,opt,name=type,proto3,enum=industries.loosh.yutani.v1.WidgetType" json:"type,omitempty"`
	Properties    *WidgetProperties      `protobuf:"bytes,3,opt,name=properties,proto3,oneof" json:"properties,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWidgetRequest) Reset() {
	*x = CreateWidgetRequest{}
	mi := &file_industries_loosh_yutani_v1_widget_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWidgetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWidgetRequest) ProtoMessage() {}

func (x *CreateWidgetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_industries_loosh_yutani_v1_widget_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWidgetRequest.ProtoReflect.Descriptor instead.
func (*CreateWidgetRequest) Descriptor() ([]byte, []int) {
	return file_industries_loosh_yutani_v1_widget_proto_rawDescGZIP(), []int{0}
}

func (x *CreateWidgetRequest) GetSessionId() *SessionId {
	if x != nil {
		return x.SessionId
	}
	return nil
}

func (x *CreateWidgetRequest) GetType() WidgetType {
	if x != nil {
		return x.Type
	}
	return WidgetType_WIDGET_BOX
}

func (x *CreateWidgetRequest) GetProperties() *WidgetProperties {
	if x != nil {
		return x.Properties
	}
	return nil
}

type CreateWidgetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WidgetId      *WidgetId              `protobuf:"bytes,1,opt,name=widget_id,json=widgetId,proto3" json:"widget_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWidgetResponse) Reset() {
	*x = CreateWidgetResponse{}
	mi := &file_industries_loosh_yutani_v1_widget_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWidgetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWidgetResponse) ProtoMessage() {}

func (x *CreateWidgetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_industries_loosh_yutani_v1_widget_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWidgetResponse.ProtoReflect.Descriptor instead.
func (*CreateWidgetResponse) Descriptor() ([]byte, []int) {
	return file_industries_loosh_yutani_v1_widget_proto_rawDescGZIP(), []int{1}
}

func (x *CreateWidgetResponse) GetWidgetId() *WidgetId {
	if x != nil {
		return x.WidgetId
	}
	return nil
}

func (x *CreateWidgetResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type DeleteWidgetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     *SessionId             `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	WidgetId      *WidgetId              `protobuf:"bytes,2,opt,name=widget_id,json=widgetId,proto3" json:"widget_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteWidgetRequest) Reset() {
	*x = DeleteWidgetRequest{}
	mi := &file_industries_loosh_yutani_v1_widget_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteWidgetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWidgetRequest) ProtoMessage() {}

func (x *DeleteWidgetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_industries_loosh_yutani_v1_widget_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWidgetRequest.ProtoReflect.Descriptor instead.
func (*DeleteWidgetRequest) Descriptor() ([]byte, []int) {
	return file_industries_loosh_yutani_v1_widget_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteWidgetRequest) GetSessionId() *SessionId {
	if x != nil {
		return x.SessionId
	}
	return nil
}

func (x *DeleteWidgetRequest) GetWidgetId() *WidgetId {
	if x != nil {
		return x.WidgetId
	}
	return nil
}

type DeleteWidgetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteWidgetResponse) Reset() {
	*x = DeleteWidgetResponse{}
	mi := &file_industries_loosh_yutani_v1_widget_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteWidgetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWidgetResponse) ProtoMessage() {}

func (x *DeleteWidgetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_industries_loosh_yutani_v1_widget_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWidgetResponse.ProtoReflect.Descriptor instead.
func (*DeleteWidgetResponse) Descriptor() ([]byte, []int) {
	return file_industries_loosh_yutani_v1_widget_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteWidgetResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type SetPropertiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     *SessionId             `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	WidgetId      *WidgetId              `protobuf:"bytes,2,opt,name=widget_id,json=widgetId,proto3" json:"widget_id,omitempty"`
	Properties    *WidgetProperties      `protobuf:"bytes,3,opt,name=properties,proto3" json:"properties,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetPropertiesRequest) Reset() {
	*x = SetPropertiesRequest{}
	mi := &file_industries_loosh_yutani_v1_widget_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetPropertiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPropertiesRequest) ProtoMessage() {}

func (x *SetPropertiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_industries_loosh_yutani_v1_widget_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPropertiesRequest.ProtoReflect.Descriptor instead.
func (*SetPropertiesRequest) Descriptor() ([]byte, []int) {
	return file_industries_loosh_yutani_v1_widget_proto_rawDescGZIP(), []int{4}
}

func (x *SetPropertiesRequest) GetSessionId() *SessionId {
	if x != nil {
		return x.SessionId
	}
	return nil
}

func (x *SetPropertiesRequest) GetWidgetId() *WidgetId {
	if x != nil {
		return x.WidgetId
	}
	return nil
}

func (x *SetPropertiesRequest) GetProperties() *WidgetProperties {
	if x != nil {
		return x.Properties
	}
	return nil
}

type SetPropertiesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetPropertiesResponse) Reset() {
	*x = SetPropertiesResponse{}
	mi := &file_industries_loosh_yutani_v1_widget_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetPropertiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPropertiesResponse) ProtoMessage() {}

func (x *SetPropertiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_industries_loosh_yutani_v1_widget_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPropertiesResponse.ProtoReflect.Descriptor instead.
func (*SetPropertiesResponse) Descriptor() ([]byte, []int) {
	return file_industries_loosh_yutani_v1_widget_proto_rawDescGZIP(), []int{5}
}

func (x *SetPropertiesResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetPropertiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     *SessionId             `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	WidgetId      *WidgetId              `protobuf:"bytes,2,opt,name=widget_id,json=widgetId,proto3" json:"widget_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPropertiesRequest) Reset() {
	*x = GetPropertiesRequest{}
	mi := &file_industries_loosh_yutani_v1_widget_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPropertiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPropertiesRequest) ProtoMessage() {}

func (x *GetPropertiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_industries_loosh_yutani_v1_widget_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPropertiesRequest.ProtoReflect.Descriptor instead.
func (*GetPropertiesRequest) Descriptor() ([]byte, []int) {
	return file_industries_loosh_yutani_v1_widget_proto_rawDescGZIP(), []int{6}
}

func (x *GetPropertiesRequest) GetSessionId() *SessionId {
	if x != nil {
		return x.SessionId
	}
	return nil
}

func (x *GetPropertiesRequest) GetWidgetId() *WidgetId {
	if x != nil {
		return x.WidgetId
	}
	return nil
}

type GetPropertiesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Properties    *WidgetProperties      `protobuf:"bytes,1,opt,name=properties,proto3" json:"properties,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPropertiesResponse) Reset() {
	*x = GetPropertiesResponse{}
	mi := &file_industries_loosh_yutani_v1_widget_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPropertiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPropertiesResponse) ProtoMessage() {}

func (x *GetPropertiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_industries_loosh_yutani_v1_widget_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPropertiesResponse.ProtoReflect.Descriptor instead.
func (*GetPropertiesResponse) Descriptor() ([]byte, []int) {
	return file_industries_loosh_yutani_v1_widget_proto_rawDescGZIP(), []int{7}
}

func (x *GetPropertiesResponse) GetProperties() *WidgetProperties {
	if x != nil {
		return x.Properties
	}
	return nil
}

type SetRootRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     *SessionId             `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	WidgetId      *WidgetId              `protobuf:"bytes,2,opt,name=widget_id,json=widgetId,proto3" json:"widget_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetRootRequest) Reset() {
	*x = SetRootRequest{}
	mi := &file_industries_loosh_yutani_v1_widget_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetRootRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRootRequest) ProtoMessage() {}

func (x *SetRootRequest) ProtoReflect() protoreflect.Message {
	mi := &file_industries_loosh_yutani_v1_widget_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRootRequest.ProtoReflect.Descriptor instead.
func (*SetRootRequest) Descriptor() ([]byte, []int) {
	return file_industries_loosh_yutani_v1_widget_proto_rawDescGZIP(), []int{8}
}

func (x *SetRootRequest) GetSessionId() *SessionId {
	if x != nil {
		return x.SessionId
	}
	return nil
}

func (x *SetRootRequest) GetWidgetId() *WidgetId {
	if x != nil {
		return x.WidgetId
	}
	return nil
}

type SetRootResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetRootResponse) Reset() {
	*x = SetRootResponse{}
	mi := &file_industries_loosh_yutani_v1_widget_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetRootResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRootResponse) ProtoMessage() {}

func (x *SetRootResponse) ProtoReflect() protoreflect.Message {
	mi := &file_industries_loosh_yutani_v1_widget_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRootResponse.ProtoReflect.Descriptor instead.
func (*SetRootResponse) Descriptor() ([]byte, []int) {
	return file_industries_loosh_yutani_v1_widget_proto_rawDescGZIP(), []int{9}
}

func (x *SetRootResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type AddChildRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     *SessionId             `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ParentId      *WidgetId              `protobuf:"bytes,2,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	ChildId       *WidgetId              `protobuf:"bytes,3,opt,name=child_id,json=childId,proto3" json:"child_id,omitempty"`
	Index         *int32                 `protobuf:"varint,4,opt,name=index,proto3,oneof" json:"index,omitempty"` // Position in parent's children, -1 or omitted for append
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddChildRequest) Reset() {
	*x = AddChildRequest{}
	mi := &file_industries_loosh_yutani_v1_widget_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddChildRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddChildRequest) ProtoMessage() {}

func (x *AddChildRequest) ProtoReflect() protoreflect.Message {
	mi := &file_industries_loosh_yutani_v1_widget_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddChildRequest.ProtoReflect.Descriptor instead.
func (*AddChildRequest) Descriptor() ([]byte, []int) {
	return file_industries_loosh_yutani_v1_widget_proto_rawDescGZIP(), []int{10}
}

func (x *AddChildRequest) GetSessionId() *SessionId {
	if x != nil {
		return x.SessionId
	}
	return nil
}

func (x *AddChildRequest) GetParentId() *WidgetId {
	if x != nil {
		return x.ParentId
	}
	return nil
}

func (x *AddChildRequest) GetChildId() *WidgetId {
	if x != nil {
		return x.ChildId
	}
	return nil
}

func (x *AddChildRequest) GetIndex() int32 {
	if x != nil && x.Index != nil {
		return *x.Index
	}
	return 0
}

type AddChildResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddChildResponse) Reset() {
	*x = AddChildResponse{}
	mi := &file_industries_loosh_yutani_v1_widget_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddChildResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddChildResponse) ProtoMessage() {}

func (x *AddChildResponse) ProtoReflect() protoreflect.Message {
	mi := &file_industries_loosh_yutani_v1_widget_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddChildResponse.ProtoReflect.Descriptor instead.
func (*AddChildResponse) Descriptor() ([]byte, []int) {
	return file_industries_loosh_yutani_v1_widget_proto_rawDescGZIP(), []int{11}
}

func (x *AddChildResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type RemoveChildRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     *SessionId             `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ParentId      *WidgetId              `protobuf:"bytes,2,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	ChildId       *WidgetId              `protobuf:"bytes,3,opt,name=child_id,json=childId,proto3" json:"child_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveChildRequest) Reset() {
	*x = RemoveChildRequest{}
	mi := &file_industries_loosh_yutani_v1_widget_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveChildRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveChildRequest) ProtoMessage() {}

func (x *RemoveChildRequest) ProtoReflect() protoreflect.Message {
	mi := &file_industries_loosh_yutani_v1_widget_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveChildRequest.ProtoReflect.Descriptor instead.
func (*RemoveChildRequest) Descriptor() ([]byte, []int) {
	return file_industries_loosh_yutani_v1_widget_proto_rawDescGZIP(), []int{12}
}

func (x *RemoveChildRequest) GetSessionId() *SessionId {
	if x != nil {
		return x.SessionId
	}
	return nil
}

func (x *RemoveChildRequest) GetParentId() *WidgetId {
	if x != nil {
		return x.ParentId
	}
	return nil
}

func (x *RemoveChildRequest) GetChildId() *WidgetId {
	if x != nil {
		return x.ChildId
	}
	return nil
}

type RemoveChildResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveChildResponse) Reset() {
	*x = RemoveChildResponse{}
	mi := &file_industries_loosh_yutani_v1_widget_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveChildResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveChildResponse) ProtoMessage() {}

func (x *RemoveChildResponse) ProtoReflect() protoreflect.Message {
	mi := &file_industries_loosh_yutani_v1_widget_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveChildResponse.ProtoReflect.Descriptor instead.
func (*RemoveChildResponse) Descriptor() ([]byte, []int) {
	return file_industries_loosh_yutani_v1_widget_proto_rawDescGZIP(), []int{13}
}

func (x *RemoveChildResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type SetFocusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     *SessionId             `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	WidgetId      *WidgetId              `protobuf:"bytes,2,opt,name=widget_id,json=widgetId,proto3" json:"widget_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetFocusRequest) Reset() {
	*x = SetFocusRequest{}
	mi := &file_industries_loosh_yutani_v1_widget_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetFocusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetFocusRequest) ProtoMessage() {}

func (x *SetFocusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_industries_loosh_yutani_v1_widget_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetFocusRequest.ProtoReflect.Descriptor instead.
func (*SetFocusRequest) Descriptor() ([]byte, []int) {
	return file_industries_loosh_yutani_v1_widget_proto_rawDescGZIP(), []int{14}
}

func (x *SetFocusRequest) GetSessionId() *SessionId {
	if x != nil {
		return x.SessionId
	}
	return nil
}

func (x *SetFocusRequest) GetWidgetId() *WidgetId {
	if x != nil {
		return x.WidgetId
	}
	return nil
}

type SetFocusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetFocusResponse) Reset() {
	*x = SetFocusResponse{}
	mi := &file_industries_loosh_yutani_v1_widget_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetFocusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetFocusResponse) ProtoMessage() {}

func (x *SetFocusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_industries_loosh_yutani_v1_widget_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetFocusResponse.ProtoReflect.Descriptor instead.
func (*SetFocusResponse) Descriptor() ([]byte, []int) {
	return file_industries_loosh_yutani_v1_widget_proto_rawDescGZIP(), []int{15}
}

func (x *SetFocusResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetFocusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     *SessionId             `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFocusRequest) Reset() {
	*x = GetFocusRequest{}
	mi := &file_industries_loosh_yutani_v1_widget_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFocusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFocusRequest) ProtoMessage() {}

func (x *GetFocusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_industries_loosh_yutani_v1_widget_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFocusRequest.ProtoReflect.Descriptor instead.
func (*GetFocusRequest) Descriptor() ([]byte, []int) {
	return file_industries_loosh_yutani_v1_widget_proto_rawDescGZIP(), []int{16}
}

func (x *GetFocusRequest) GetSessionId() *SessionId {
	if x != nil {
		return x.SessionId
	}
	return nil
}

type GetFocusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WidgetId      *WidgetId              `protobuf:"bytes,1,opt,name=widget_id,json=widgetId,proto3,oneof" json:"widget_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFocusResponse) Reset() {
	*x = GetFocusResponse{}
	mi := &file_industries_loosh_yutani_v1_widget_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFocusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFocusResponse) ProtoMessage() {}

func (x *GetFocusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_industries_loosh_yutani_v1_widget_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFocusResponse.ProtoReflect.Descriptor instead.
func (*GetFocusResponse) Descriptor() ([]byte, []int) {
	return file_industries_loosh_yutani_v1_widget_proto_rawDescGZIP(), []int{17}
}

func (x *GetFocusResponse) GetWidgetId() *WidgetId {
	if x != nil {
		return x.WidgetId
	}
	return nil
}

type ListWidgetsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     *SessionId             `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWidgetsRequest) Reset() {
	*x = ListWidgetsRequest{}
	mi := &file_industries_loosh_yutani_v1_widget_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWidgetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWidgetsRequest) ProtoMessage() {}

func (x *ListWidgetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_industries_loosh_yutani_v1_widget_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWidgetsRequest.ProtoReflect.Descriptor instead.
func (*ListWidgetsRequest) Descriptor() ([]byte, []int) {
	return file_industries_loosh_yutani_v1_widget_proto_rawDescGZIP(), []int{18}
}

func (x *ListWidgetsRequest) GetSessionId() *SessionId {
	if x != nil {
		return x.SessionId
	}
	return nil
}

type ListWidgetsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Widgets       []*WidgetInfo          `protobuf:"bytes,1,rep,name=widgets,proto3" json:"widgets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWidgetsResponse) Reset() {
	*x = ListWidgetsResponse{}
	mi := &file_industries_loosh_yutani_v1_widget_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWidgetsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWidgetsResponse) ProtoMessage() {}

func (x *ListWidgetsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_industries_loosh_yutani_v1_widget_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWidgetsResponse.ProtoReflect.Descriptor instead.
func (*ListWidgetsResponse) Descriptor() ([]byte, []int) {
	return file_industries_loosh_yutani_v1_widget_proto_rawDescGZIP(), []int{19}
}

func (x *ListWidgetsResponse) GetWidgets() []*WidgetInfo {
	if x != nil {
		return x.Widgets
	}
	return nil
}

type WidgetInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WidgetId      *WidgetId              `protobuf:"bytes,1,opt,name=widget_id,json=widgetId,proto3" json:"widget_id,omitempty"`
	Type          WidgetType             `protobuf:"varint,2,opt,name=type,proto3,enum=industries.loosh.yutani.v1.WidgetType" json:"type,omitempty"`
	ParentId      *WidgetId              `protobuf:"bytes,3,opt,name=parent_id,json=parentId,proto3,oneof" json:"parent_id,omitempty"`
	Children      []*WidgetId            `protobuf:"bytes,4,rep,name=children,proto3" json:"children,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WidgetInfo) Reset() {
	*x = WidgetInfo{}
	mi := &file_industries_loosh_yutani_v1_widget_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WidgetInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WidgetInfo) ProtoMessage() {}

func (x *WidgetInfo) ProtoReflect() protoreflect.Message {
	mi := &file_industries_loosh_yutani_v1_widget_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WidgetInfo.ProtoReflect.Descriptor instead.
func (*WidgetInfo) Descriptor() ([]byte, []int) {
	return file_industries_loosh_yutani_v1_widget_proto_rawDescGZIP(), []int{20}
}

func (x *WidgetInfo) GetWidgetId() *WidgetId {
	if x != nil {
		return x.WidgetId
	}
	return nil
}

func (x *WidgetInfo) GetType() WidgetType {
	if x != nil {
		return x.Type
	}
	return WidgetType_WIDGET_BOX
}

func (x *WidgetInfo) GetParentId() *WidgetId {
	if x != nil {
		return x.ParentId
	}
	return nil
}

func (x *WidgetInfo) GetChildren() []*WidgetId {
	if x != nil {
		return x.Children
	}
	return nil
}

var File_industries_loosh_yutani_v1_widget_proto protoreflect.FileDescriptor

const file_industries_loosh_yutani_v1_widget_proto_rawDesc = "" +
	"\n" +
	"'industries/loosh/yutani/v1/widget.proto\x12\x1aindustries.loosh.yutani.v1\x1a&industries/loosh/yutani/v1/types.proto\"\xf9\x01\n" +
	"\x13CreateWidgetRequest\x12D\n" +
	"\n" +
	"session_id\x18\x01 \x01(\v2%.industries.loosh.yutani.v1.SessionIdR\tsessionId\x12:\n" +
	"\x04type\x18\x02 \x01(\x0e2&.industries.loosh.yutani.v1.WidgetTypeR\x04type\x12Q\n" +
	"\n" +
	"properties\x18\x03 \x01(\v2,.industries.loosh.yutani.v1.WidgetPropertiesH\x00R\n" +
	"properties\x88\x01\x01B\r\n" +
	"\v_properties\"s\n" +
	"\x14CreateWidgetResponse\x12A\n" +
	"\twidget_id\x18\x01 \x01(\v2$.industries.loosh.yutani.v1.WidgetIdR\bwidgetId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\"\x9e\x01\n" +
	"\x13DeleteWidgetRequest\x12D\n" +
	"\n" +
	"session_id\x18\x01 \x01(\v2%.industries.loosh.yutani.v1.SessionIdR\tsessionId\x12A\n" +
	"\twidget_id\x18\x02 \x01(\v2$.industries.loosh.yutani.v1.WidgetIdR\bwidgetId\"0\n" +
	"\x14DeleteWidgetResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xed\x01\n" +
	"\x14SetPropertiesRequest\x12D\n" +
	"\n" +
	"session_id\x18\x01 \x01(\v2%.industries.loosh.yutani.v1.SessionIdR\tsessionId\x12A\n" +
	"\twidget_id\x18\x02 \x01(\v2$.industries.loosh.yutani.v1.WidgetIdR\bwidgetId\x12L\n" +
	"\n" +
	"properties\x18\x03 \x01(\v2,.industries.loosh.yutani.v1.WidgetPropertiesR\n" +
	"properties\"1\n" +
	"\x15SetPropertiesResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x9f\x01\n" +
	"\x14GetPropertiesRequest\x12D\n" +
	"\n" +
	"session_id\x18\x01 \x01(\v2%.industries.loosh.yutani.v1.SessionIdR\tsessionId\x12A\n" +
	"\twidget_id\x18\x02 \x01(\v2$.industries.loosh.yutani.v1.WidgetIdR\bwidgetId\"e\n" +
	"\x15GetPropertiesResponse\x12L\n" +
	"\n" +
	"properties\x18\x01 \x01(\v2,.industries.loosh.yutani.v1.WidgetPropertiesR\n" +
	"properties\"\x99\x01\n" +
	"\x0eSetRootRequest\x12D\n" +
	"\n" +
	"session_id\x18\x01 \x01(\v2%.industries.loosh.yutani.v1.SessionIdR\tsessionId\x12A\n" +
	"\twidget_id\x18\x02 \x01(\v2$.industries.loosh.yutani.v1.WidgetIdR\bwidgetId\"+\n" +
	"\x0fSetRootResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x80\x02\n" +
	"\x0fAddChildRequest\x12D\n" +
	"\n" +
	"session_id\x18\x01 \x01(\v2%.industries.loosh.yutani.v1.SessionIdR\tsessionId\x12A\n" +
	"\tparent_id\x18\x02 \x01(\v2$.industries.loosh.yutani.v1.WidgetIdR\bparentId\x12?\n" +
	"\bchild_id\x18\x03 \x01(\v2$.industries.loosh.yutani.v1.WidgetIdR\achildId\x12\x19\n" +
	"\x05index\x18\x04 \x01(\x05H\x00R\x05index\x88\x01\x01B\b\n" +
	"\x06_index\",\n" +
	"\x10AddChildResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xde\x01\n" +
	"\x12RemoveChildRequest\x12D\n" +
	"\n" +
	"session_id\x18\x01 \x01(\v2%.industries.loosh.yutani.v1.SessionIdR\tsessionId\x12A\n" +
	"\tparent_id\x18\x02 \x01(\v2$.industries.loosh.yutani.v1.WidgetIdR\bparentId\x12?\n" +
	"\bchild_id\x18\x03 \x01(\v2$.industries.loosh.yutani.v1.WidgetIdR\achildId\"/\n" +
	"\x13RemoveChildResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x9a\x01\n" +
	"\x0fSetFocusRequest\x12D\n" +
	"\n" +
	"session_id\x18\x01 \x01(\v2%.industries.loosh.yutani.v1.SessionIdR\tsessionId\x12A\n" +
	"\twidget_id\x18\x02 \x01(\v2$.industries.loosh.yutani.v1.WidgetIdR\bwidgetId\",\n" +
	"\x10SetFocusResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"W\n" +
	"\x0fGetFocusRequest\x12D\n" +
	"\n" +
	"session_id\x18\x01 \x01(\v2%.industries.loosh.yutani.v1.SessionIdR\tsessionId\"h\n" +
	"\x10GetFocusResponse\x12F\n" +
	"\twidget_id\x18\x01 \x01(\v2$.industries.loosh.yutani.v1.WidgetIdH\x00R\bwidgetId\x88\x01\x01B\f\n" +
	"\n" +
	"_widget_id\"Z\n" +
	"\x12ListWidgetsRequest\x12D\n" +
	"\n" +
	"session_id\x18\x01 \x01(\v2%.industries.loosh.yutani.v1.SessionIdR\tsessionId\"W\n" +
	"\x13ListWidgetsResponse\x12@\n" +
	"\awidgets\x18\x01 \x03(\v2&.industries.loosh.yutani.v1.WidgetInfoR\awidgets\"\xa3\x02\n" +
	"\n" +
	"WidgetInfo\x12A\n" +
	"\twidget_id\x18\x01 \x01(\v2$.industries.loosh.yutani.v1.WidgetIdR\bwidgetId\x12:\n" +
	"\x04type\x18\x02 \x01(\x0e2&.industries.loosh.yutani.v1.WidgetTypeR\x04type\x12F\n" +
	"\tparent_id\x18\x03 \x01(\v2$.industries.loosh.yutani.v1.WidgetIdH\x00R\bparentId\x88\x01\x01\x12@\n" +
	"\bchildren\x18\x04 \x03(\v2$.industries.loosh.yutani.v1.WidgetIdR\bchildrenB\f\n" +
	"\n" +
	"_parent_id2\xda\b\n" +
	"\rWidgetService\x12q\n" +
	"\fCreateWidget\x12/.industries.loosh.yutani.v1.CreateWidgetRequest\x1a0.industries.loosh.yutani.v1.CreateWidgetResponse\x12q\n" +
	"\fDeleteWidget\x12/.industries.loosh.yutani.v1.DeleteWidgetRequest\x1a0.industries.loosh.yutani.v1.DeleteWidgetResponse\x12t\n" +
	"\rSetProperties\x120.industries.loosh.yutani.v1.SetPropertiesRequest\x1a1.industries.loosh.yutani.v1.SetPropertiesResponse\x12t\n" +
	"\rGetProperties\x120.industries.loosh.yutani.v1.GetPropertiesRequest\x1a1.industries.loosh.yutani.v1.GetPropertiesResponse\x12b\n" +
	"\aSetRoot\x12*.industries.loosh.yutani.v1.SetRootRequest\x1a+.industries.loosh.yutani.v1.SetRootResponse\x12e\n" +
	"\bAddChild\x12+.industries.loosh.yutani.v1.AddChildRequest\x1a,.industries.loosh.yutani.v1.AddChildResponse\x12n\n" +
	"\vRemoveChild\x12..industries.loosh.yutani.v1.RemoveChildRequest\x1a/.industries.loosh.yutani.v1.RemoveChildResponse\x12e\n" +
	"\bSetFocus\x12+.industries.loosh.yutani.v1.SetFocusRequest\x1a,.industries.loosh.yutani.v1.SetFocusResponse\x12e\n" +
	"\bGetFocus\x12+.industries.loosh.yutani.v1.GetFocusRequest\x1a,.industries.loosh.yutani.v1.GetFocusResponse\x12n\n" +
	"\vListWidgets\x12..industries.loosh.yutani.v1.ListWidgetsRequest\x1a/.industries.loosh.yutani.v1.ListWidgetsResponseB*Z(github.com/chazu/yutani/pkg/proto/yutanib\x06proto3"

var (
	file_industries_loosh_yutani_v1_widget_proto_rawDescOnce sync.Once
	file_industries_loosh_yutani_v1_widget_proto_rawDescData []byte
)

func file_industries_loosh_yutani_v1_widget_proto_rawDescGZIP() []byte {
	file_industries_loosh_yutani_v1_widget_proto_rawDescOnce.Do(func() {
		file_industries_loosh_yutani_v1_widget_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_industries_loosh_yutani_v1_widget_proto_rawDesc), len(file_industries_loosh_yutani_v1_widget_proto_rawDesc)))
	})
	return file_industries_loosh_yutani_v1_widget_proto_rawDescData
}

var file_industries_loosh_yutani_v1_widget_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_industries_loosh_yutani_v1_widget_proto_goTypes = []any{
	(*CreateWidgetRequest)(nil),   // 0: industries.loosh.yutani.v1.CreateWidgetRequest
	(*CreateWidgetResponse)(nil),  // 1: industries.loosh.yutani.v1.CreateWidgetResponse
	(*DeleteWidgetRequest)(nil),   // 2: industries.loosh.yutani.v1.DeleteWidgetRequest
	(*DeleteWidgetResponse)(nil),  // 3: industries.loosh.yutani.v1.DeleteWidgetResponse
	(*SetPropertiesRequest)(nil),  // 4: industries.loosh.yutani.v1.SetPropertiesRequest
	(*SetPropertiesResponse)(nil), // 5: industries.loosh.yutani.v1.SetPropertiesResponse
	(*GetPropertiesRequest)(nil),  // 6: industries.loosh.yutani.v1.GetPropertiesRequest
	(*GetPropertiesResponse)(nil), // 7: industries.loosh.yutani.v1.GetPropertiesResponse
	(*SetRootRequest)(nil),        // 8: industries.loosh.yutani.v1.SetRootRequest
	(*SetRootResponse)(nil),       // 9: industries.loosh.yutani.v1.SetRootResponse
	(*AddChildRequest)(nil),       // 10: industries.loosh.yutani.v1.AddChildRequest
	(*AddChildResponse)(nil),      // 11: industries.loosh.yutani.v1.AddChildResponse
	(*RemoveChildRequest)(nil),    // 12: industries.loosh.yutani.v1.RemoveChildRequest
	(*RemoveChildResponse)(nil),   // 13: industries.loosh.yutani.v1.RemoveChildResponse
	(*SetFocusRequest)(nil),       // 14: industries.loosh.yutani.v1.SetFocusRequest
	(*SetFocusResponse)(nil),      // 15: industries.loosh.yutani.v1.SetFocusResponse
	(*GetFocusRequest)(nil),       // 16: industries.loosh.yutani.v1.GetFocusRequest
	(*GetFocusResponse)(nil),      // 17: industries.loosh.yutani.v1.GetFocusResponse
	(*ListWidgetsRequest)(nil),    // 18: industries.loosh.yutani.v1.ListWidgetsRequest
	(*ListWidgetsResponse)(nil),   // 19: industries.loosh.yutani.v1.ListWidgetsResponse
	(*WidgetInfo)(nil),            // 20: industries.loosh.yutani.v1.WidgetInfo
	(*SessionId)(nil),             // 21: industries.loosh.yutani.v1.SessionId
	(WidgetType)(0),               // 22: industries.loosh.yutani.v1.WidgetType
	(*WidgetProperties)(nil),      // 23: industries.loosh.yutani.v1.WidgetProperties
	(*WidgetId)(nil),              // 24: industries.loosh.yutani.v1.WidgetId
}
var file_industries_loosh_yutani_v1_widget_proto_depIdxs = []int32{
	21, // 0: industries.loosh.yutani.v1.CreateWidgetRequest.session_id:type_name -> industries.loosh.yutani.v1.SessionId
	22, // 1: industries.loosh.yutani.v1.CreateWidgetRequest.type:type_name -> industries.loosh.yutani.v1.WidgetType
	23, // 2: industries.loosh.yutani.v1.CreateWidgetRequest.properties:type_name -> industries.loosh.yutani.v1.WidgetProperties
	24, // 3: industries.loosh.yutani.v1.CreateWidgetResponse.widget_id:type_name -> industries.loosh.yutani.v1.WidgetId
	21, // 4: industries.loosh.yutani.v1.DeleteWidgetRequest.session_id:type_name -> industries.loosh.yutani.v1.SessionId
	24, // 5: industries.loosh.yutani.v1.DeleteWidgetRequest.widget_id:type_name -> industries.loosh.yutani.v1.WidgetId
	21, // 6: industries.loosh.yutani.v1.SetPropertiesRequest.session_id:type_name -> industries.loosh.yutani.v1.SessionId
	24, // 7: industries.loosh.yutani.v1.SetPropertiesRequest.widget_id:type_name -> industries.loosh.yutani.v1.WidgetId
	23, // 8: industries.loosh.yutani.v1.SetPropertiesRequest.properties:type_name -> industries.loosh.yutani.v1.WidgetProperties
	21, // 9: industries.loosh.yutani.v1.GetPropertiesRequest.session_id:type_name -> industries.loosh.yutani.v1.SessionId
	24, // 10: industries.loosh.yutani.v1.GetPropertiesRequest.widget_id:type_name -> industries.loosh.yutani.v1.WidgetId
	23, // 11: industries.loosh.yutani.v1.GetPropertiesResponse.properties:type_name -> industries.loosh.yutani.v1.WidgetProperties
	21, // 12: industries.loosh.yutani.v1.SetRootRequest.session_id:type_name -> industries.loosh.yutani.v1.SessionId
	24, // 13: industries.loosh.yutani.v1.SetRootRequest.widget_id:type_name -> industries.loosh.yutani.v1.WidgetId
	21, // 14: industries.loosh.yutani.v1.AddChildRequest.session_id:type_name -> industries.loosh.yutani.v1.SessionId
	24, // 15: industries.loosh.yutani.v1.AddChildRequest.parent_id:type_name -> industries.loosh.yutani.v1.WidgetId
	24, // 16: industries.loosh.yutani.v1.AddChildRequest.child_id:type_name -> industries.loosh.yutani.v1.WidgetId
	21, // 17: industries.loosh.yutani.v1.RemoveChildRequest.session_id:type_name -> industries.loosh.yutani.v1.SessionId
	24, // 18: industries.loosh.yutani.v1.RemoveChildRequest.parent_id:type_name -> industries.loosh.yutani.v1.WidgetId
	24, // 19: industries.loosh.yutani.v1.RemoveChildRequest.child_id:type_name -> industries.loosh.yutani.v1.WidgetId
	21, // 20: industries.loosh.yutani.v1.SetFocusRequest.session_id:type_name -> industries.loosh.yutani.v1.SessionId
	24, // 21: industries.loosh.yutani.v1.SetFocusRequest.widget_id:type_name -> industries.loosh.yutani.v1.WidgetId
	21, // 22: industries.loosh.yutani.v1.GetFocusRequest.session_id:type_name -> industries.loosh.yutani.v1.SessionId
	24, // 23: industries.loosh.yutani.v1.GetFocusResponse.widget_id:type_name -> industries.loosh.yutani.v1.WidgetId
	21, // 24: industries.loosh.yutani.v1.ListWidgetsRequest.session_id:type_name -> industries.loosh.yutani.v1.SessionId
	20, // 25: industries.loosh.yutani.v1.ListWidgetsResponse.widgets:type_name -> industries.loosh.yutani.v1.WidgetInfo
	24, // 26: industries.loosh.yutani.v1.WidgetInfo.widget_id:type_name -> industries.loosh.yutani.v1.WidgetId
	22, // 27: industries.loosh.yutani.v1.WidgetInfo.type:type_name -> industries.loosh.yutani.v1.WidgetType
	24, // 28: industries.loosh.yutani.v1.WidgetInfo.parent_id:type_name -> industries.loosh.yutani.v1.WidgetId
	24, // 29: industries.loosh.yutani.v1.WidgetInfo.children:type_name -> industries.loosh.yutani.v1.WidgetId
	0,  // 30: industries.loosh.yutani.v1.WidgetService.CreateWidget:input_type -> industries.loosh.yutani.v1.CreateWidgetRequest
	2,  // 31: industries.loosh.yutani.v1.WidgetService.DeleteWidget:input_type -> industries.loosh.yutani.v1.DeleteWidgetRequest
	4,  // 32: industries.loosh.yutani.v1.WidgetService.SetProperties:input_type -> industries.loosh.yutani.v1.SetPropertiesRequest
	6,  // 33: industries.loosh.yutani.v1.WidgetService.GetProperties:input_type -> industries.loosh.yutani.v1.GetPropertiesRequest
	8,  // 34: industries.loosh.yutani.v1.WidgetService.SetRoot:input_type -> industries.loosh.yutani.v1.SetRootRequest
	10, // 35: industries.loosh.yutani.v1.WidgetService.AddChild:input_type -> industries.loosh.yutani.v1.AddChildRequest
	12, // 36: industries.loosh.yutani.v1.WidgetService.RemoveChild:input_type -> industries.loosh.yutani.v1.RemoveChildRequest
	14, // 37: industries.loosh.yutani.v1.WidgetService.SetFocus:input_type -> industries.loosh.yutani.v1.SetFocusRequest
	16, // 38: industries.loosh.yutani.v1.WidgetService.GetFocus:input_type -> industries.loosh.yutani.v1.GetFocusRequest
	18, // 39: industries.loosh.yutani.v1.WidgetService.ListWidgets:input_type -> industries.loosh.yutani.v1.ListWidgetsRequest
	1,  // 40: industries.loosh.yutani.v1.WidgetService.CreateWidget:output_type -> industries.loosh.yutani.v1.CreateWidgetResponse
	3,  // 41: industries.loosh.yutani.v1.WidgetService.DeleteWidget:output_type -> industries.loosh.yutani.v1.DeleteWidgetResponse
	5,  // 42: industries.loosh.yutani.v1.WidgetService.SetProperties:output_type -> industries.loosh.yutani.v1.SetPropertiesResponse
	7,  // 43: industries.loosh.yutani.v1.WidgetService.GetProperties:output_type -> industries.loosh.yutani.v1.GetPropertiesResponse
	9,  // 44: industries.loosh.yutani.v1.WidgetService.SetRoot:output_type -> industries.loosh.yutani.v1.SetRootResponse
	11, // 45: industries.loosh.yutani.v1.WidgetService.AddChild:output_type -> industries.loosh.yutani.v1.AddChildResponse
	13, // 46: industries.loosh.yutani.v1.WidgetService.RemoveChild:output_type -> industries.loosh.yutani.v1.RemoveChildResponse
	15, // 47: industries.loosh.yutani.v1.WidgetService.SetFocus:output_type -> industries.loosh.yutani.v1.SetFocusResponse
	17, // 48: industries.loosh.yutani.v1.WidgetService.GetFocus:output_type -> industries.loosh.yutani.v1.GetFocusResponse
	19, // 49: industries.loosh.yutani.v1.WidgetService.ListWidgets:output_type -> industries.loosh.yutani.v1.ListWidgetsResponse
	40, // [40:50] is the sub-list for method output_type
	30, // [30:40] is the sub-list for method input_type
	30, // [30:30] is the sub-list for extension type_name
	30, // [30:30] is the sub-list for extension extendee
	0,  // [0:30] is the sub-list for field type_name
}

func init() { file_industries_loosh_yutani_v1_widget_proto_init() }
func file_industries_loosh_yutani_v1_widget_proto_init() {
	if File_industries_loosh_yutani_v1_widget_proto != nil {
		return
	}
	file_industries_loosh_yutani_v1_types_proto_init()
	file_industries_loosh_yutani_v1_widget_proto_msgTypes[0].OneofWrappers = []any{}
	file_industries_loosh_yutani_v1_widget_proto_msgTypes[10].OneofWrappers = []any{}
	file_industries_loosh_yutani_v1_widget_proto_msgTypes[17].OneofWrappers = []any{}
	file_industries_loosh_yutani_v1_widget_proto_msgTypes[20].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_industries_loosh_yutani_v1_widget_proto_rawDesc), len(file_industries_loosh_yutani_v1_widget_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_industries_loosh_yutani_v1_widget_proto_goTypes,
		DependencyIndexes: file_industries_loosh_yutani_v1_widget_proto_depIdxs,
		MessageInfos:      file_industries_loosh_yutani_v1_widget_proto_msgTypes,
	}.Build()
	File_industries_loosh_yutani_v1_widget_proto = out.File
	file_industries_loosh_yutani_v1_widget_proto_goTypes = nil
	file_industries_loosh_yutani_v1_widget_proto_depIdxs = nil
}
